#+TITLE: Automatic Constituent and Function Alignment for Parallel Treebanking
#+STARTUP: hidestars
#+SEQ_TODO: ULEST SKRIV FERDIG
#+AUTHOR: 
#Kevin Brubeck Unhammer
#+EMAIL: 
#Kevin.Unhammer hos student uib no
#+LANGUAGE: en
#+OPTIONS: H:4 toc:nil f:t skip:nil num:t
#+LaTeX_CLASS: TLT
#+LaTeX_HEADER: \newcommand{\xbar}{$\rm\overline{X}$}
#+LaTeX_HEADER: \newcommand{\F}[2]{\textsc{#1}\ensuremath{_{#2}}}
#+LaTeX_HEADER: \newcommand{\OBLben}{\F{obl}{ben}}
#+LaTeX_HEADER: \newcommand{\OBJben}{\F{obj}{ben}}
#+LaTeX_HEADER: \newcommand{\OBJ}{\F{obj}{}}
#+LaTeX_HEADER: \newcommand{\OBJs}{\F{obj~}{}}
#+LaTeX_HEADER: \newcommand{\ADJ}{\F{adj}{}}
#+LaTeX_HEADER: \newcommand{\ADJs}{\F{adj~}{}}
#+LaTeX_HEADER: \newcommand{\XCOMP}{\F{xcomp}{}}
#+LaTeX_HEADER: \newcommand{\XCOMPs}{\F{xcomp~}{}}
#+LaTeX_HEADER: \newcommand{\SUBJ}{\F{subj}{}}
#+LaTeX_HEADER: \newcommand{\SUBJs}{\F{subj~}{}}
#+LaTeX_HEADER: \newcommand{\PRED}{\F{pred}{}}
#+LaTeX_HEADER: \newcommand{\TOPIC}{\F{topic}{}}
#+LaTeX_HEADER: \newcommand{\falign}{\ensuremath{\operatorname{\emph{falign}}}}
#+LaTeX_HEADER: \newcommand{\fpairs}{\ensuremath{\operatorname{\emph{fpairs}}}}
#+LaTeX_HEADER: \newcommand{\Bleu}{\textsc{Bleu}}
#+LaTeX_HEADER: \usetikzlibrary{calc}
#+LaTeX_HEADER: \newcommand{\proj}[2]{\begin{tabular}{c}\footnotesize{#1}\\\normalsize{#2}\end{tabular}}
#+LaTeX_HEADER: \newcommand{\ua}{\ensuremath{\uparrow}}
#+LaTeX_HEADER: \newcommand{\da}{\ensuremath{\downarrow}}

\begin{abstract}
\noindent
This paper describes the development of an automatic phrase alignment
 method using parallel sentences parsed in Lexical-Functional Grammar
 as input, where similarity in analyses is used as evidence that
 constituents or functional elements \fxnote[inline,nomargin]{vil seie
 «f-struktur-element», men slik at ikkje-LFG-folk forstår det} may be
 linked. A set of principles for phrase alignment are formulated,
 based on the goals of the XPar-project \cite{dyvik2009lmp}, and an
 implementation is given.
\end{abstract}

\thispagestyle{empty}


* Introduction
Lexical-Functional Grammar (LFG) is a grammatical framework where a
 sentence is analysed as having both a constituent structure
 (c-structure) and functional structure (f-structure). The former is
 similar to traditional phrase structure trees, while the latter is an
 attribute-value matrix/graph which represents dependency relations
 between syntactic functions (subject, object, etc.), in addition to
 the grammatical features of these. The argument structure of
 predicates is embedded in the f-structure representation.

This work is part of the XPar-project, which involves developing a
 parallel treebank which will include links between corresponding
 constituents, as well as between corresponding syntactic
 functions. By utilising the information available in each monolingual
 LFG-parse of two parallel sentences, we are able to make precise and
 linguistically informative alignments on both the c-structure and
 f-structure level.

Although there exists many methods for automatic phrase alignment
 \cite{och2003scv}, most of these have been based on aligning any
 N-gram that is compatible with a word alignment, where none of these
 take into account syntactic features, and alignments may cross
 constituent borders. \cite{hearne2008ccd} describes a method for using
 statistical word-alignments as seeds to two separate constituent and
 dependency tree alignments; however, the goal here is to create a set
 of N-gram pairs for statistical machine translation, and the
 dependency and constituent alignments do not inform each other.

Our method is instead based on the fact that similar grammatical
 phenomena in different languages will have similar grammatical
 analyses, so structural similarity in the analyses should indicate
 that those parts of the analyses may be linked. How much structural
 similarity is required in order to link two elements is defined as a
 set of general constraints. This allows for a more top-down method of
 phrase alignment, which is more informative to the linguist since it
 links not only true constituents, but functional elements (which in
 LFG may even span discontiguous constituents). Word-alignments or
 translational dictionaries may be needed to automatically
 disambiguate in cases where the LFG parses do not give sufficient
 information; but the method will perform a large part of the
 alignment job even without /any/ parallel corpus available.

The principles and constraints for alignment are discussed in the next
 section, section \ref{SEC:implementation} describes the
 implementation, while section \ref{SEC:discussion} discusses the
 strengths and weaknesses of the method.

* Principles for Phrase Alignment
\label{SEC:principles}

We want our alignment links to be useful for treebank studies, in the
 XPar-project this includes studying the relationship between
 syntactic function and semantic roles across languages, thus the
 principles for alignment (or, constraints on possible alignments)
 have to take this goal into account.  An outline of the principles
 for phrase alignment used in the XPar-project are formulated in
 \cite[pp.~75--77]{dyvik2009lmp}, this section recounts the major
 points, and explains some relevant LFG-terminology and concepts.

# similar surroundings required, more?

To introduce the relevant LFG-terminology, consider figure
 \ref{fig:simple-links}. This shows two simplified LFG f-structures
 and c-structures, ready for alignment. The English word /slept/ is a
 verb phrase, and its nodes /project/ the f-structure $g$ (as seen by
 the \PRED{} value being the `semantic form' of /slept/,
 `\textbf{sleep}'). The projection from c-structure to f-structure,
 $\phi$, is a many-to-one mapping, and all the nodes S, VP and V
 together project $g$. Since the nodes project the same f-structure,
 they constitute a /functional domain/. We can see that they project
 the same f-structure by the $\ua{}=\da$ annotations, which are read
 as "my f-structure is the same as that of my mother node". The NP
 node has $\ua{}\SUBJ{}=\da$ instead, read as "my f-structure is the
 \SUBJ{} of my mother's f-structure"; the NP thus projects the value
 of the \SUBJ{} f-structure inside $g$.

The argument structures of the Norwegian and English verbs are shown
 in their \PRED{} values; both verbs take one argument, in the figure
 this is represented by an index. By looking up this index, we find
 that the one argument of `\textbf{sove}' is the subject of $f$, with
 `\textbf{eg}' as its \PRED{}; similarly `\textbf{I}', subject of $g$,
 is the only argument of `\textbf{sleep}'. Neither of these subjects
 take any arguments themselves.


The candidates we consider for alignment are c-structure phrases,
 individual words, and \PRED{} elements of f-structures[fn:1].  In
 figure \ref{fig:simple-links}, we can link the \PRED{} elements of
 $f$ and $g$; by doing this we consider their f-structures linked.
 The \PRED{} values of their arguments are also candidates for
 alignment, and in this case there would be no reason not to link
 them. As noted, the S, VP and V nodes in English constitute the
 functional domain of $g$, similarly IP, I' and V are the functional
 domain of $f$. Since their f-structures are linked, we have reason to
 link nodes from these functional domains. But we only want to link
 nodes if the material they dominate also corresponds: we would not
 want to link IP and S if the NP in Norwegian was linked to something
 that was not dominated by the S in English (or vice versa), since a
 c-structure link means that what is dominated by the linked nodes
 corresponds[fn:2]. However, translations often ommit or add material,
 so an /unlinked/ subordinate node (e.g. an adverbial only expressed
 in one language) should not interfere with the linking of IP and S.

#+BEGIN_LaTeX
 \begin{figure}[htp]
    \centering
    \begin{tikzpicture}
    {\avmoptions{}
     \node(src){
        \begin{avm}
          $f$ \[pred   &  `{\bf{}sove}<\@{1}>'\\
          tense  & pret  \\
	  subj & \@{1} \[pred & `{\bf{eg}}' \] \\
          ... \] 
       \end{avm}
      };
      \node[right of=src, node distance=5cm](trg){
        \begin{avm}
          $g$ \[pred   &  `{\bf{}sleep}<\@{2}>'\\
          tense  & pret  \\
          aspect & simple \\
	  subj & \@{2} \[pred & `{\bf{I}}' \] \\
          ... \]
        \end{avm}
      };
      }
%      \draw[dashed,-] (src.west) .. controls +(-1,3) and +(-1,2) .. node[above,sloped]{$l_f$} (trg.west) ;
%      \draw[-] ($(src.north)-(1,0.3)$) .. controls +(0,1.5) and +(0,1.5) .. node[above,sloped]{$l_p$} ($(trg.north)-(1,0.3)$) ;

      \begin{scope}[shift={(0,-2cm)}]
        \Tree  [.\node(VPs){IP}; [.\proj{\ua{}\SUBJ{}=\da}{NP} \edge[roof]; {eg} ] [.\proj{\ua{}=\da}{I'} [.\proj{\ua{}=\da}{V} \node(sov){sov};  ] ] ]
      \begin{scope}[shift={(5cm,0)}]
        \Tree  [.\node(VPt){S}; [.\proj{\ua{}\SUBJ{}=\da}{NP} \edge[roof]; {I} ] [.\proj{\ua{}=\da}{VP} [.\proj{\ua{}=\da}{V} \node(slept){slept};  ] ] ]
      \end{scope}
      \end{scope}
%      \draw[-] (VPs)..controls +(north:1.5) and +(north:1.5) .. node[above,sloped]{$l_c$} (VPt) ;
%      \draw[dashed,-] (sov)..controls +(north east:1.5) and +(north west:1.5) .. node[above,sloped]{$l_o$} (slept) ;
   \end{tikzpicture}
    
    \caption{Example of simple links between constituents,
   f-structures and words (Norwegian and English)}
   \label{fig:simple-links}
 \end{figure}
#+END_LaTeX

Similarly, on the f-structure level we allow adjuncts (adverbials) to
 remain unlinked; adjuncts differ from arguments mainly in being
 non-obligatory, while arguments /are/ required in order to express a
 certain sense of a predicate. So to link two predicates, we require
 all their arguments to find `linguistically predictable translations'
 (LPT) in the translation, where a source word $W_s$ is
 LPT-correspondent with a target word $W_t$ if "$W_t$ can in general
 (out of context) be taken to be among the semantically plausible
 translations of $W_s$" \cite[p.~74]{dyvik2009lmp}. Nouns and
 pronominal forms are also considered LPT-correspondent.

The argument structure of predicates in LFG is ordered, and this order
 typically reflects the semantic role hierarchy (agents being before
 themes, etc.). However, we do not require that linked arguments
 occupy the same positions in the argument structure of their
 predicates, since an English grammar may assign the first argument of
 the verb /like/ to the agent, while a Spanish grammar may assign the
 first argument of the translation, /gustar/, to the theme. As one of
 the goals of the XPar-project is to study the relationship between
 semantic role and syntactic function, the aligner cannot presume that
 the relationship always is straightforward.

If any of the arguments of two otherwise linkable predicates do not
 have LPT-correspondents among each other, we have evidence that the
 predicates themselves are used to express different propositions. But
 should we allow adjuncts as translations of arguments?  The examples
 in \ref{ex:vedde} are all translations of the same sentence; for the
 four different different languages, the grammar writers chose four
 different ways of dividing the participants in the verbal situation
 into arguments and adjuncts[fn:3]. but in this translation, the
 predicates clearly express the same proposition.  Thus we have to
 allow linking arguments to adjuncts; the monolingual evidence which
 informed the individual grammars may have suggested that a certain
 participant of a verbal situation should be analysed as an argument
 in one language, but as an adjunct in the other -- in a particular
 translation, however, they may still correspond semantically.

#+BEGIN_LaTeX
{\avmoptions{}
\ex. \label{ex:vedde}
\a. Adams veddet en sigarett med Browne \hfill{} (Norwegian Bokmål)\\ på at det regnet.\\
    $\\\begin{avm}\[pred & `{\bf{}vedde}<Abrams, cigarette, Browne, rain>' \\
                 adjunct & \{\}\]\end{avm}\\$
\b. abramsi brouns daenajleva sigaretze, rom cvimda. \hfill{} (Georgian)\\
    $\\\begin{avm}\[pred &  `{\bf{}da-najleveba}<Abrams, Browne, regne>'\\
    adjunct &  \{ \rm cigarette \}\]\end{avm}\\$ 
\c. Abrams hat mit Browne um eine Zigarette gewettet, \hfill{}(German)\\
    daß es regnet.\\
    $\\\begin{avm}\[pred & `{\bf{}wetten}<Abrams, regne>' \\
                  adjunct & \{ \rm Browne, cigarette \}\]\end{avm}\\$
\d. Abrams bet a cigarette with Brown that it was raining. \hfill{}(English)\\
    $\\\begin{avm}\[pred & `{\bf{}bet}<Abrams, sigarett, regne>'\\
                  adjunct & \{ \rm Browne \}\]\end{avm}$

}
#+END_LaTeX


More formally, these are the requirements for linking two f-structure
\PRED{} elements $p$ and $q$: 
\ex. \a. the word-forms of $p$ and $q$ have LPT-correspondence
     \b. all arguments of $p$ have LPT-correspondence with an argument
     or adjunct of $q$
     \c. all arguments of $q$ have LPT-correspondence with an argument
     or adjunct of $p$
     \d. the LPT-correspondences are one-to-one
     \e. no adjuncts of $p$ are linked to f-structures outside $q$ or
     vice versa

The one-to-one requirement \Last[d] is there to avoid linking two
 near-synonyms in one language into one word in the other language. We
 require all arguments of $p$ to have possible translations among the
 arguments and adjuncts of $q$, but we do not require \Last to be true
 of each argument of $p$; that is, an argument of $p$ may remain
 unlinked on the f-structure level. 
As mentioned, for adjuncts of $p$ we do not even require that they
 have LPT-correspondence with arguments/adjuncts of $q$, or vice
 versa, but \Last[e] ensures that they are not /linked/ outside of
 their predicates, which would imply that $p$ and $q$ did not contain
 corresponding linked material.

In order to link two c-structure nodes, \cite[p.~77]{dyvik2009lmp}
 defines the term /linked lexical nodes/, $LL$, where $LL(n)$ is the
 set of nodes dominated by $n$ which are word-linked. To link $n_s$
 and $n_t$ (whose projected f-structures must be linked), all nodes in
 $LL(n_s)$ must be linked to nodes in $LL(n_t)$. Unlinked nodes
 dominated by $n_s$ or $n_t$ are not an obstacle to linking these
 nodes. Thus in in figure \ref{fig:simple-links}, if the NP nodes are
 linked, we may link IP and S, while in figure
 \ref{fig:ikkje-c-lenkje-pro-drop}, the I' nodes may not be linked
 since the Icelandic I' node dominates an NP which is linked to a node
 /not/ dominated by the Norwegian I' node. Icelandic being a pro-drop
 language, the argument expressed by /det/ in Norwegian does not have
 to be overtly expressed in Icelandic[fn:5], but by the criterion
 above can still link the IP nodes, as they dominate the same sets of
 linked lexical nodes.

#+BEGIN_LaTeX
  \begin{figure}[htp]
  \centering
    \begin{tikzpicture}
    \tikzset{level distance=1.5cm}
    \Tree  [.\node(IPs){IP};  [.\node(OBJs){\proj{\ua OBJ=\da}{NP}}; \edge[roof]; {kjøttboller} ]
                              [.\node(I's){\proj{}{I'}};
                                      [.\node(Is){\proj{}{I}}; {regnar} ]
                                      [.\node(SUBJs){\proj{\ua SUBJ=\da}{NP}}; \edge[roof]; {det} ]
                                       ] ]
        \begin{scope}[shift={(2in,0in)}]
    \Tree  [.\node(IPt){IP};  
                              [.\node(I't){I'}; 
                                      [.\node(It){\proj{}{I}}; {rignir} ]
                                      [.\node(OBJt){\proj{\ua OBJ=\da}{NP}}; \edge[roof]; {kjötbollum} ] ]   ]
  \end{scope}
\draw[dashed,-] (I's)..controls +(north:1) and +(north:1) .. node[midway,sloped]{$\times$} (I't) ;
\draw[-] (OBJs)..controls +(north east:1.5) and +(north west:1.5) ..  (OBJt) ;
  
  \end{tikzpicture}
     \caption{C-structure links may not cross dominated links
     (Norwegian Nynorsk and Icelandic for ``it's raining meat balls'')}
     \label{fig:ikkje-c-lenkje-pro-drop}
    \end{figure}
#+END_LaTeX

#+BEGIN_LaTeX
  \begin{figure}[htp]
  \centering
    \begin{tikzpicture}
    \tikzset{level distance=1.5cm}
    \Tree  [.\node(IPs){IP};  [.\node(SUBJs){\proj{\ua SUBJ=\da}{NP}}; \edge[roof]; {de} ]
                              [.\node(I's){\proj{}{I'}};
                                      [.\node(Is){\proj{}{I}}; {hadde} ]
                                      [.\node(Ss){\proj{\ua=\da}{S}};
				         [.\node(){\proj{\ua SUBJ=\da}{VP}};  
					   [.\node(Vs){\proj{}{V}}; {snakket} ]
					   [.\node(Vs){\proj{}{PP}}; \edge[roof]; {om roboter} ]
]
				      ]
                                      
                                       ] ]
        \begin{scope}[shift={(2in,0in)}]
    \Tree  [.\node(IPt){IP};  [.\node(PPt){\proj{\ua SUBJ=\da}{PP}}; \edge[roof]; {gzaSi} ]
                              [.\node(IP2t){\proj{}{IP}};
                                      [.\node(PP2t){\proj{\ua=\da}{PP}}; \edge[roof]; {gzaSi} ]
                                      [.\node(Ss){\proj{\ua=\da}{S}};
				         [.\node(){\proj{\ua SUBJ=\da}{VP}};  
					   [.\node(Vs){\proj{}{V}}; {snakket} ]
					   [.\node(Vs){\proj{}{PP}}; \edge[roof]; {om roboter} ]
]
				      ]
                                      
                                       ] ]
  \end{scope}
\draw[dashed,-] (I's)..controls +(north:1) and +(north:1) .. node[midway,sloped]{$\times$} (I't) ;
\draw[-] (OBJs)..controls +(north east:1.5) and +(north west:1.5) ..  (OBJt) ;
  
  \end{tikzpicture}
     \caption{C-structure links may not cross dominated links
     (Norwegian Nynorsk and Icelandic for ``it's raining meat balls'')}
     \label{fig:ikkje-c-lenkje-pro-drop}
    \end{figure}
#+END_LaTeX

\fxnote{TODO: betre døme enn kjöttbollum:
gzaSi robotebze laparakobdnen
på.vegen robot.om snakka.om.3PL.past

de hadde snakket om roboter
}
We may want an alternative, stricter, criterion for linking
c-strukture nodes, where we also add linked f-structure arguments that
are not overtly expressed to $LL$. 

* Implementation
\label{SEC:implementation}

This section discusses a work-in-progress implementation of the above
alignment principles[fn:4]. 

* Discussion
\label{SEC:discussion}


* Conclusion
# tom inndeling for å halde bibliografien sist

\bibliography{master}






* Footnotes

[fn:1] We could consider aligning other f-structure elements, but only
 \PRED{} elements are sure to exist in both languages, while
 grammatical features such as \F{ASPECT}{} might not exist in both
 languages, or be possible to link in a one-to-one-manner.

[fn:2] Even if IP and S could not be linked, we could still link I'
 and VP, as these dominate the same linked material.

[fn:3] The f-structures here are highly simplified.

[fn:4] All code and some examples of input parses available from
       \fxnote[inline,nomargin]{http://example.com}.

[fn:5] The pro-subjects will be linked in f-structure, however.
