#+TITLE: Syntaktisk informert frasesamanstilling 
#+SEQ_TODO: ULEST SKRIV FERDIG
#+SEQ_TODO: TOGROK TODO DONE
#+TAGS: SPML(s) NORGLISH(n) ROTETE(r)
#+STARTUP: hidestars
#+AUTHOR: Kevin Brubeck Unhammer
#+EMAIL: Kevin.Unhammer hos student uib no
#+LANGUAGE: nn
#+OPTIONS: H:4 toc:t f:t skip:nil num:t
#+LaTeX_CLASS: masterdraft
#+LaTeX_HEADER: \newcommand{\xbar}{$\rm\overline{X}$}
#+LaTeX_HEADER: \newcommand{\F}[2]{\textsc{#1}\ensuremath{_{#2}}}
#+LaTeX_HEADER: \newcommand{\OBLben}{\F{obl}{ben}}
#+LaTeX_HEADER: \newcommand{\OBJben}{\F{obj}{ben}}
#+LaTeX_HEADER: \newcommand{\OBJ}{\F{obj}{}}
#+LaTeX_HEADER: \newcommand{\OBJs}{\F{obj~}{}}
#+LaTeX_HEADER: \newcommand{\ADJ}{\F{adj}{}}
#+LaTeX_HEADER: \newcommand{\ADJs}{\F{adj~}{}}
#+LaTeX_HEADER: \newcommand{\XCOMP}{\F{xcomp}{}}
#+LaTeX_HEADER: \newcommand{\XCOMPs}{\F{xcomp~}{}}
#+LaTeX_HEADER: \newcommand{\SUBJ}{\F{subj}{}}
#+LaTeX_HEADER: \newcommand{\SUBJs}{\F{subj~}{}}
#+LaTeX_HEADER: \newcommand{\PRED}{\F{pred}{}}
#+LaTeX_HEADER: \newcommand{\falign}{\ensuremath{\operatorname{\emph{falign}}}}
#+LaTeX_HEADER: \newcommand{\fpairs}{\ensuremath{\operatorname{\emph{fpairs}}}}
#+LaTeX_HEADER: \newcommand{\Bleu}{\textsc{Bleu}}
#+LaTeX_HEADER: \usetikzlibrary{calc}



* COMMENT Generell TODO
Nytt denne før INNLEVERING:
#+EXPORT_EXCLUDE_TAGS: ROTETE

\listoffixmes
 
nyttig sparse tree: SKRIV

[[file:~/Master/Master.org::*om%20samanstilling%20fr][skriv det om samanstilling frå forrige Xpar-møte]]


* Innleiing
\label{SEC:innleiing}

\fxnote{TODO: abstract/samandrag}

Denne masteroppgåva utforskar kva det vil seie at to uttrykk er
omsetjingar av kvarandre, og korleis me automatisk kan generere og
evaluere samanstilling (/alignment/) av uttrykk som
står i eit slikt omsetjingsforhold. 

Omsetjingsforhold finn me mellom setningar i kontekst på ulike språk,
men me kan au finne ulike typar ekvivalensforhold (samanstillingar)
mellom frasar innanfor setningane, og mellom lingvistiske
skildringar av setningane. I samanheng med XPar-prosjektet
\citep{xpar2008rcn} har eg sett på metodar for automatisk
frasesamanstilling – å finne omsetjingsforhold mellom grupper av
fleire ord. Resultatet blir ein /annotasjon/, endå ei lingvistisk
skildring av tekstene.


# to situerte setningar er omsetjingar av kvarandre, mellom
# lingvistiske skildringar finn me ekvivalens som me kan tolke i
# forhold til omsetjing...

Det at me kan omsetje mellom lingvistiske skildringar
(t.d. trekkstrukturane til dei grammatiske rammeverka HPSG eller LFG)
gjer det tydeleg at me arbeider med ein /modell/ av språket; ulike
skildringar kan vere sanne innanfor modellen, utan at modellen er lik
språket. Sjølve omsetjingsforholdet er au ein teoretisk storleik, og
me kan leggje ulike kriterium til grunn for å kalle to uttrykk
omsetjingar av kvarandre.

Kriteria avheng av formålet. Samanstillingsannotasjon kan t.d. nyttast
som grunnlag for statistisk eller eksempelbasert maskinomsetjing, i
tillegg til oppbygging av parallelle korpora for meir teoretiske
språkstudie.  For statistisk maskinomsetjing vil alle uttrykk vere
omsetjingar av kvarandre med eit visst sannsyn (kanskje null), ein
har vanlegvis ikkje kriterium som krev lingvistisk analyse. Når
samanstillinga skal nyttast i parallelle korpora for lingvistiske
undersøkingar vil ein kanskje ha krav om at uttrykk som skal lenkjast
er «like» på eit eller anna mål, utover at dei har opptredt saman
ofte; i den manuelle samanstillinga i \citet{samuelsson2006pap} har
dei t.d. ein del reint semantiske kriterium for å opprette
fraselenkjer i ein parallell trebank, men dei har ikkje krav om
syntaktisk likskap.

Xpar-prosjektet, som denne masteroppgåva er ein del av, har mellom
anna som mål å oppdage relasjonar mellom grammatiske funksjonar,
tematiske roller og kasusmarkering, ved hjelp av parallelle trebankar
annotert med djupe grammatiske analysar.  Samanstillinga planlagt der
krev i større grad syntaktisk likskap for å kalle to uttrykk
omsetjingar, men kan difor au tene på det at dei grammatiske analysane
er utvikla med tanke på å vere så parallelle som mogleg.  Dei
grammatiske analysane er gjort i leksikalsk-funksjonell grammatikk,
LFG \citep{bresnan2001lfs}. Ei grammatisk analyse i LFG involverer
både konstituentstruktur (c-struktur) og funksjonell struktur
(f-struktur). Konstituentstrukturen liknar på frasestrukturtrea frå
andre grammatiske tradisjonar. Dei funksjonelle strukturane er
trekkstrukturar, som mellom anna representerer avhengnadsforhold
mellom syntaktiske funksjonar som predikat, subjekt og objekt, i
tillegg til å halde informasjon om grammatiske trekk som genus, tal
eller kasus. Nodar i c-strukturen kan spesifisere informasjon på ulike
stader i f-strukturen[fn:19].

I XPar-prosjektet vil ein finne ut om metodar for frasesamanstilling
kan tene på det at LFG-grammatikkane for dei ulike språka er skrivne
med same prinsipp lagt til grunn; to parallellstilte setningar bør ha
f-strukturar som er like nok til at me kan samanstille frasar ved
hjelp av likskapen mellom f-strukturane. I \citet[s.~72]{dyvik2009lmp}
finn me følgjande hypotese:

\begin{quote}
On the basis of monolingual treebanks constructed from a parallel
corpus by means of parallel grammars it will be possible to achieve
automatic word and phrase alignment with significantly higher
precision and recall than hitherto achieved through other means.
\end{quote}
# todo: «precision and recall» ymtar jo om samanlikning med
# gullstandard som evalueringsgrunnlag

kor «parallel grammars» her krev parallellisme i både f-struktur og
c-struktur.

Men i tillegg til at ein kanskje kan få betre skåre på desse
kvantitative måla, vil lenkjer mellom f-strukturar gi informasjon som
er kvalitativt forskjellig frå det ein kan få med å berre sjå på
lenkjer mellom ord, N-gram eller konstituentar.

I denne masteroppgåva spesifiserer eg kva for lenkjer mellom
f-strukturar og c-strukturnodar me ønskjer, implementerer eit program
=lfgalign= som automatisk finn samanstillingar med slike lenkjer,
evaluerer resultatet av å køyre programmet mitt, og samanliknar dette
med kva me kan få frå andre metodar.

Programmet =lfgalign= opprettar frasesamanstillingar med hjelp av
f-strukturinformasjonen gitt av dei parallelle grammatikkane, og
bottom-up-informasjon om kva for ordsamanstillingar som er
moglege. F-strukturane avgrensar igjen kva for ordsamanstillingar som
er moglege, og kva for c-strukturnodar (syntaktiske frasar) som kan
lenkjast.


** Vegkart
I neste kapittel ser eg på andre metodar for frasesamanstilling.

I kapittel \ref{SEC:ideell} går eg gjennom kva me ønskjer av ei
frasesamanstilling når formålet m.a. er å oppdage relasjonane mellom
syntaktiske funksjonar, kasusmarkering og tematiske roller med hjelp
av ein parallell trebank. Dette ender opp i ei liste med «krav» som
samanstillingane må fylle for å vere lovlege, og som implementasjonen
av den automatiske frasesamanstillinga (kapittel
\ref{SEC:implementasjon}) må følgje.

Eg evaluerer samanstillingane som kjem ut av denne metoden i kapittel
\ref{SEC:diskusjon}, og samanliknar dei med det som er mogleg der me
berre har konstituentstruktur (syntaktiske tre) i tillegg til
ordsamanstilling.

Eg nyttar språka georgisk og norsk i evalueringa, hovudsakleg fordi
dei er svært ulike syntaktisk og morfologisk; Georgisk er mellom anna
eit pro-drop-språk, med friare ordfølgje og rikare morfologi enn
norsk.  \fxnote{fortelje om georgisk i kap.5 heller}

Sidan eg ikkje har tilgang på ferdig setningssamanstilt georgisk-norsk
parallelltekst, blir det vanskeleg å køyre den statistiske
ordsamanstillinga som er vanleg som første steg i N-grambaserte
metodar (utan ein god del forarbeid). Difor konsentrerer eg meg i
evalueringa om eit testkorpus kor eg manuelt gjer
ordsamanstillinga. Eg veit heller ikkje enno om nokon statistisk
parsar av høg kvalitet for georgisk, men testkorpuset er ferdig parsa
med LFG-parsaren frå \citet{meurer2008cgg}, c-strukturnodane avgrenser
då kva som er ein syntaktisk konstituent.


** SKRIV Frasesamanstilling frå f-struktur			     :ROTETE:
   \fxnote{limt inn frå prosjektskildringa, dette må omskrivast
   totalt/fjernast. Kan kanskje ta eit par setningar inn i kap.3, men
   innleiinga bør iallfall ha eit kort oversyn over metoden}

Om me har f-strukturane til to omsette setningar, burde det kanskje
vere mogleg å finne ei f-struktursamanstilling først og så finne
ordsamanstillinga ut frå denne. Tanken er at me frå to f-strukturar
som skildrar omsette setningar, kan
1. lage ei samanstilling mellom relevante deler av f-strukturane,
2. nytte denne funksjonelle samanstillinga til å finne ei
   frasesamanstilling, ved å følgje avbildinga frå f-struktur til
   c-struktur ($\phi{}^{-1}$).

Eitt problem som byr seg er hypotesemangfaldet: kva for «deler av
f-strukturane»? Korleis kan me avgrense søkjerommet? I det minste må
me kunne kople det opp mot c-strukturnodar; så \PRED-element bør i det
minste ha lenkjer, medan t.d. tempus og aspektuell informasjon kanskje
er mindre viktig. Men kva kan ignorerast? Vil det oppstå tilfelle då
me bør vekte visse element? (Dvs., må me nokon gong disambiguere med
slike andre element?)
# todo 

Vidare må me vite /korleis/ me samanstiller desse delene. Me kan
t.d. byrje med å kople ytterste \PRED{} frå kvart språk, og så
rekursivt kople \PRED{} i dei relevante
substrukturane\footnote{Dette~krev~sjølvsagt~at~ytre~\PRED{}~faktisk~korresponderer~i~samanstilte~setningar,~ein~ikkje-triviell~påstand.}. Gitt
ein funksjon $i$ som returnerer indeksen til ein f-(sub)struktur, kan
eit førsteutkast til ei /f-samanstilling/, samanstilling på
f-strukturnivå, sjå slik ut:

\[
\falign(f_{1}, f_{2}) =
\{ (i(f_{1}(\PRED)), i(f_{2}(\PRED))) \}
\cup
\bigcup_{g_{1},g_{2}\in \fpairs(f_{1},f_{2})} \falign(g_{1}, g_{2})
\]
# må eg skrive f_1(g_1) etc.?

\falign{} vil gi ei mengd av par av indeksar, kor kvart par altså er
samanstilt. Ein føresetnad her er at me i tillegg veit kva for par av
substrukturar som er «relevante» ($\fpairs(f_{1},f_{2})$).

#+BEGIN_LaTeX
Sjølv om f-strukturar abstraherer frå skilnadene i korleis ulike språk
nyttar ordgruppering og ordform til å kode syntaktiske forhold
\citep[s.~14]{bresnan2001lfs}, vil det likevel oppstå forskjellar i
f-strukturane til to parallellstilte setningar i eit korpus; både
pga. «omsetjarfridom» og det at ulike språk nyttar ulike syntaktiske
funksjonar til å uttrykkje det same konseptet. I
f-struktursamanstillinga til \citet[s.~40]{riezler2006gmt} får dei
t.d. ei lenkje frå ein \XCOMP{} på tysk til eit \OBJ{} på
engelsk. Skal ein algoritme gå frå f-strukturar til frasesamanstilling
må han i det minste vere robust nok til å takle slik mangel på
samsvar. Til å byrje med kan me tenkje oss at \fpairs{} gir alle par
av GF-ar som har same plass i
argumentstrukturen\footnote{Ved~å~nytte~argumentplass~kan~me~enkelt~få~til~lenkjer~mellom~GF-ar~med~ulike~namn,~som~vist~i~dømet.}
til predikatet, så viss 'sein$\langle$\SUBJ,\XCOMP$\rangle$' står i
$f_{1}$ og 'have$\langle$\SUBJ,\OBJ$\rangle$' i $f_{2}$, vil \fpairs{}
i det minste returnere
$\{(f_{1}(\SUBJ),f_{2}(\SUBJ)),(f_{1}(\XCOMP),f_{2}(\OBJ)),...\}$.
Men om me ikkje har slikt samsvar i argumentstrukturar, vil \fpairs{}
ha ein vanskelegare jobb.
#+END_LaTeX

Eit større problem er nok adverbial (elementa i \F{adjunct}{}), kor
f-strukturane ikkje gir like greie hint om kva for substrukturar som
høyrer
saman\footnote{Det~er~mogleg~at~f-samanstillinga~av~adverbial~kan~tene~på~informasjon~frå~(og~difor~bør~skje~etter)~samanstillinga~av~frasane~som~projiserer~argumentfunksjonane.}. Ein
del av masteroppgåva vil altså vere å komme med forslag til funksjonen
\fpairs{}.


f-samanstillinga kan nyttast til å gi ein samanstilling av frasane dei
representerer. $\phi^{-1}$ gir no ei samanstilling mellom funksjonelle
domene i c-strukturane, me har t.d. ei lenkje mellom domenet
$d_{1}=\{X, Y, Z\}$ på språk 1 og $d_{2}=\{U, V, W\}$ på språk 2. Kvar
node frå $d_{1}$ vil kunne (symmetrisk) samanstillast med ein (eller
ingen) frå $d_{2}$.

Her kan me utnytte det at frasestrukturane i dei ulike grammatikkane
er tufta på same X-bar-prinsipp. Ein $XP\in d_{1}$ skal sannsynlegvis
samanstillast med ein $YP\in d_{2}$ (der $X$ og $Y$ gjerne er same
symbol, men au kan vere t.d. $V$ og $I$). I tillegg skal høge nodar
sannsynlegvis samanstillast med andre høge nodar, der alt anna er
likt, medan mangel på samsvar i samanstillinga til døtre kan føre til
at mornodar ikkje skal samanstillast; ein formalisering dette steget,
med diskusjon rundt problema, vil au inngå i masteroppgåva.

* Bakgrunn og omgrepsavklaring
  \label{SEC:bakgrunn}

** SKRIV Relaterte metodar
Automatisk frasesamanstilling er eit nytt felt. Det finst allereie
veldig gode system for automatisk setningssamanstilling, og automatisk
samanstilling av ord har komme langt, men nivåa mellom ord og setning
ser ut til å by på fleire problem. \fxnote[inline,nomargin]{«by på
fleire problem» -- weasel wording, TODO omskriv.} Dei ulike tilnærmingane
som finst er prega av formåla til utviklarane. Det er verdt å merkje
seg at ordet «frase» ofte blir nytta i litteraturen om strenger av ord
(N-gram) som ikkje treng vere syntaktiske konstituentar, igjen
avhengig av formålet med metoden.

Innanfor korpuslingvistikken har t.d. \citet{piao2001mwu} nytta enkel
kollokasjonsinformasjon for å først finne sannsynlege nominale frasar
på engelsk og kinesisk (dvs. «chunking»), og så samanstille desse; her
er evalueringsgrunnlaget rett og slett ein manuell gjennomgang av dei
mest sannsynlege omsetjingane dei får. \fxnote{fleire slike? meir om
dette, algoritmen}

Den manuelle frasesamanstillinga i \citet{samuelsson2006pap}, nemnt
over, blei nytta som evalueringsstandard for den automatiske metoden i
\citet{samuelsson2007apa}.  Her kjem frasesamanstillinga frå ei
ordsamanstilling, der berre N-gram som svarer til ein syntaktisk node
blir lenkja som frasar (meir om denne metoden nedanfor). Formålet er å
lage ein parallell trebank, kor det altså er unyttig å lenkje «frasar»
som /ikkje/ er konstituentar.

Sjølv om fraselenkjer kan vere nyttige i korpuslingvistikken er det
hovudsakleg innanfor statistisk maskinomsetjing at ein har forska på
samanstilling av frasar. \citet{koehn2003spb} gir ei grundig
evaluering av ulike statistiske metodar for frasesamanstilling til
bruk i stokastisk maskinomsetjing. Dei nyttar \Bleu-skåren til å
rangere resultata
\citep[Papineni~et~al.,~2001,~i][s.~51]{koehn2003spb}, som gir ei
rangering ved (N-grambasert) samanlikning med ferdig omsett tekst.

Den første metoden, /AP/, er reint N-grambasert. Dei nyttar verktøyet
Giza++ \citep[Och~og~Ney,~2000,~i][s.~50]{koehn2003spb} til å indusere
ordsamanstilling frå eit setningssamanstilt korpus (vha. «modell 4»
for ordsamanstilling, utvikla ved IBM av \citet{brown1993msm}). Denne
samanstillinga er 1-til-n (t.d. eitt engelsk ord til to franske), så
dei finn ordsamanstilling for begge retningar og tek så snittet av alle
moglege N-gramsamanstillingar som ikkje er i konflikt med
ordsamanstillingane. Dei føyer så på ord frå unionen av desse
vha. nokre enkle heuristikkar.

Den andre metoden, /Syn/, tek berre med dei frasane som står under
syntaktiske nodar i eit parsa korpus; frasesamanstillinga til /Syn/ er
ein delmengd av den i /AP/. Denne syntaktisk informerte modellen gav
ein mykje dårlegare \Bleu-skåre enn den reint N-grambaserte modellen
(faktisk dårlegare enn omsetjingane frå den opphavlege modell 4 for
ordsamanstilling, utan frasesamanstilling). Dei forklarer dette med
den store mengda uttrykk som ikkje utgjer syntaktiske konstituentar i
følgje parsaren deira, men likevel konsekvent blir omsett til visse
uttrykk på det andre språket (t.d. «es gibt» på tysk til «there is» på
engelsk).

Seinare resultat har vist at ein /kombinasjon/ av syntaktisk
informerte metodar med reint N-grambaserte modellar (dvs. i motsetning
til å berre fjerne samanstillingar mellom ikkje-konstituentar) kan
auke skåren i ein maskinomsetjingsevaluering, både om ein som i
/Syn/-modellen nyttar frasestrukturinformasjon, men i endå større
grad om ein nyttar dependendsinformasjon
\citep{tinsley2007ept,hearne2008ccd}. Dette er interessant med tanke
på at LFG-analysane gir begge typar informasjon.

\citet{riezler2006gmt} utvikla ein metode for å kombinere frasebasert
statistisk maskinomsetjing med LFG-basert setningsgenerering. Dei finn
ei n-til-m-ordsamanstilling med Giza++ som i metodane over, men parsar
i tillegg setningane i LFG. Dei to moglege f-strukturane som liknar
mest blir valt ut, og frå ordsamanstillinga finn dei
mange-til-mange-korrespondansar mellom substrukturane i
f-strukturane. Ved å leggje til LFG-basert generering fekk det
kombinerte systemet betre resultat på langdistanseavhengnader og
generalisering til nye uttrykk med strukturell likskap til tidlegare
observerte uttrykk.
\fxnote{Dette er motsett retning av det mitt program gjer, nemne
seinare?}

Så langt har eg ikkje komme over metodar som går i motsett retning,
altså prøver å finne eller betre på frase- og ordsamanstilling ut frå
ein LFG-parse -- det er dette som er strategien til programmet
=lfgalign= i kapittel \ref{SEC:implementasjon} -- men det er stor
overlapp mellom krava som kjem i kapittel \ref{SEC:ideell} og dei gitt
i den første publiseringa i XPar-prosjektet, \citet{dyvik2009lmp}.


** SKRIV Eit kort oversyn over leksikalsk-funksjonell grammatikk og terminologi
\label{SEC:omgrepsavklaring}

I dei følgjande kapitla nyttar eg ein del LFG-terminologi (i tillegg
til eit par eigne termar). Difor gir eg her eit kort oversyn over det
som kan vere nytt for dei som er meir vand med andre grammatiske
rammeverk.

- modellteoretisk (vs derivasjonelt) :: LFG er eit modellteoretisk,
  ikkje-derivasjonelt, rammeverk for grammatikk.
  \citet{pullum2001dbm} gir ein god gjennomgang av forskjellen mellom
  derivasjonelle (enumerative) grammatikkar og modellteoretiske
  grammatikkar, kor førstnemnde definerer /mengder av uttrykk/ ved
  avleiing frå startsymbol, medan sistnemnde gir skildringar av
  /enkeltuttrykk/. Ein modellteoretisk grammatikk kan i tillegg
  skildre strukturen (eller dei moglege strukturane) til /fragment/ av
  setningar, og denne strukturen er lik det bidraget som fragmentet
  tilfører skildringa av heile setninga. Det tilsvarande er ikkje
  mogleg å gjere derivasjonelt. \citet[s.~32--33]{pullum2001dbm} gir
  t.d. eit fragment som kjem midt i eit høgreforgreina tre; ein
  derivasjonell skildring ville måtte skildre treet over eller under,
  men utan informasjon om kva som kjem til høgre eller venstre kan me
  ikkje (på ein ikkje-vilkårleg måte) skildre subtreet utanfor
  fragmentet heilt fram til terminal- eller startsymbol.

- f-struktur :: ...

- c-struktur :: ...

- endosentrisitetsprinsippa :: ...

- \xbar :: ...

- diskontinuerlege konstituentar :: ...

- $\phi$ :: c-struktur-f-strukturavbildinga $\phi$ ...
	    
- $\phi^{-1}$ :: Det funksjonelle domenet til ein f-struktur er gitt
  ved $\phi^{-1}$, inversen av c-til-f-strukturavbildinga, og
  tilsvarer dei nodane i c-strukturen som projiserer denne
  f-strukturen, t.d. ein VP-node med dominerande IP og CP
  \citep[s.~126]{bresnan2001lfs}. Sidan dette er inversen av ein
  funksjon, kan me ha diskontinuerlege konstituentar i same
  funksjonelle domene (på same måte som ulike argument til ein
  funksjon kan gi same verdi).

- fraselenkjer vs frasesamanstilling :: Eg nyttar her termane
  /lenkjing/ og /samanstilling/ i omtrent same tyding som dei engelske
  termane /link/ og /alignment/, kor ei samanstilling er ei mengd
  lenkjer. Merk at ei enkeltlenkje treng ikkje å vere ein-til-ein.
  Lenkjer og samanstillingar er ekvivalensforhold som me kan finne
  mellom lingvistiske /representasjonar/ (f-struktur, c-struktur)
  eller /uttrykk/ (ord, setningar); lenkjing mellom dei siste altså er
  meir ateoretisk / datanært.


* Krav til frasesamanstilling
\label{SEC:ideell}

** Innleiing
I denne delen prøver eg å finne fram til kva som er den best moglege
frasesamanstillinga. Eg argumenterer for at «best» her må tolkast i
forhold til eit formål, her å finne samsvar mellom kasusmarkering og
semantisk rolletildeling. Som utgangspunkt har eg visse krav for
ordsamanstilling gitt i \citet{thunes2003eal}, saman med krava for
frasesamanstilling i \citet{dyvik2009lmp}. Eg viser kvifor ein, for
våre formål, må revidere kravet til Thunes om likskap i
argumentstruktur. Eg gir nokre døme for å grunngje krava i
\citet{dyvik2009lmp}, i tillegg til å utdjupe dei for å gjere dei
enklare å implementere i kapittel \ref{SEC:implementasjon}. Dette
involverer au å omformulere krava for c-struktursamanstilling slik at
dei ikkje refererer til ordlenkjer, berre f-strukturlenkjer. Sidan eit
av måla med Xpar-prosjektet er å finne ut kor mykje
frasesamanstillingsinformasjon me kan få ut av parallellismen i
f-strukturane (eller, sett frå den andre sida, kor uavhengig ein kan
gjere seg av den bottom-up-informasjonen ei ordlenkje gir), blir det
eit avleidd mål å formulere frasesamanstillingskrava med referanse til
f-strukturane der det går an.

** Formål med frasesamanstilling
\label{SEC:formaal}

Ei frasesamanstilling er ein slag annotasjon av eit korpus. På same
måte som oppbygginga av eit korpus avheng av formålet til korpuset,
kan ein ikkje definere den ideelle annotasjonen av eit korpus utan å
ta høgd for kva ein skal nytte annotasjonen til.

Me kan illustrere dette med eit enkelt, praktisk døme: ved automatisk
ordklassetagging må ein gjerne avvege mellom dekning (å finne flest
moglege analysar for flest mogleg ord) og presisjon (å berre ende opp
med korrekte analysar).  Viss formålet er å annotere ein
leksikografisk ressurs, vil det vere viktigare med høg dekning på
bekostning av presisjon, sidan leksikografen gjerne leiter etter
nye/kreative bruksområde av ord. Skal taggaren nyttast til
maskinomsetjing i staden, kan ein ikkje nytte meir enn éin analyse til
slutt, så her er presisjon viktigast.

Sjølvsagt kan ein her seie at den /ideelle/ annotasjonen vil vere å
berre ha korrekte analysar, men sjølv ved ideelle krav er formålet
viktig: er ein ute etter å finne N-gram som ofte blir omsett med
kvarande, men som /ikkje/ er syntaktiske konstituentar, er det klart
at retningslinjene nedanfor ikkje er så nyttige.

Sidan utviklinga av automatisk frasesamanstilling hovudsakleg har
skjedd innanfor frasebasert statistisk maskinomsetjing (PBSMT), kjem
me ikkje utanom ei samanlikning her. I PBSMT er formålet med ei
fraselenkje å betre maskinomsetjing på eitt eller anna mål,
t.d. \Bleu-skåren. \Bleu-skåren samanliknar ferdig omsett tekst (ein
gullstandard) med det automatisk omsette, ved å sjekke kor mykje
N-gram-overlapp det er mellom tekstene. Ei fraselenkje mellom
N-grammet /es gibt/ og /there is/ (dvs. eit auka sannsyn for å nytte
slike par i omsetjinga) kan gi ein høgare endeleg skåre i \Bleu. Som
vist i \citet{koehn2003spb} fekk dei ein lågare \Bleu-skåre når dei
\fxnote{todo: referere til den faktiske parsaren? det var Bikel
kanskje?}  fjerna lenkjer mellom nodar som, i følgje ein robust
statistisk PCFG-parsar, ikkje var syntaktiske frasar
(konstituentar). Dvs. at i figur \ref{fig:ikkjenode} vil lenkja vist
ved den prikkete linja bli fjerna frå mengda over moglege lenkjer om
ein berre held seg til syntaktiske konstituentar, og
$p(es~gibt,~there~is)$ vil ikkje bli tilsvarande auka i den
statistiske omsetjingsmodellen. Sidan PBSMT, som skildra i
\citet{koehn2003spb}, er agnostisk til syntaktiske høve i
omsetjingssteget[fn:1] er det for dei ingen grunn til å berre halde
seg til samanstilling mellom syntaktiske konstituentar; dei har i
utgangspunktet meir nytte av kollokasjonsinformasjon.

#+BEGIN_LaTeX
\begin{figure}[htp]
   \centering
   \begin{tikzpicture}
   \Tree [ [.\node(aDE){Es}; ]
    [.\node(pDE){XP};      
    \edge[roof]; \node(rDE){    gibt Frost an meiner Tür };  ] ] 
    \begin{scope}[shift={(2in,0in)}]
      \Tree [ [.\node(aEN){There};  ]
            [.\node(pEN){YP}; \edge[roof]; \node(rEN){ is frost at my door}; ] ]
          \end{scope}
          \draw[-] (pDE)..controls +(north east:2) and +(north:2) .. (pEN); 
          \draw[dashed,-] ($(rDE.west)-(0.5,0)$)..controls +(south:2) and +(south:2)..($(rEN.west)-(0.5,0)$); 
          \draw[dashed,-] (aEN)..controls +(south west:1) and +(south:1) .. (rEN.north west); 
          \draw[dashed,-] (aDE)..controls +(south west:1) and +(south:1) .. (rDE.north west); 
\end{tikzpicture}
   \caption{N-gram-samanstilling versus syntaktiske frasar}
    \label{fig:ikkjenode}
  \end{figure}
#+END_LaTeX
# there's frost at my door
# es gibt Frost an meiner Tür

Men sett no at me ikkje har som formål å nytte frasesamanstillinga til
reint N-grambasert omsetjing. Kva for /lingvistiske/ krav kan me
stille til å kalle to frasar samanstilte? Me må i alle fall tillate
ein del skilnad.  I alle større parallelltekster vil parallellstilte
setningar ha visse syntaktiske og semantiske[fn:6] omsetjingsskifte,
t.d. leksikalisering av syntaktiske konstruksjonar eller omvendt,
endring av ordklasse, presisering/depresisering, endringar i leksikalske
trekk (t.d. telleleg/utelleleg),
osb. \citep[s.~56--62]{munday2001its}, slik at den einaste
fullstendige, «perfekte» samanstillinga vil vere
identitetsfunksjonen. Kor mykje mangel på samsvar me godtek blir då
avgjort av formålet med samanstillinga.

Eitt av formåla med samanstillinga i denne oppgåva er å kunne oppdage
korleis ulike språk realiserer semantiske roller syntaktisk; då
spesielt i forhold til hypotesane gitt i \citet[s.~7]{xpar2008rcn},
t.d. at «case marking might be useful to further determine a given
argument's semantic role». Skal me finne det siste, må me altså kunne
lenkje frasar med ulik kasusmarkering, men ha krav om lik tildeling av
semantiske roller; samtidig skal me sjå at me ikkje kan ha krav om lik
syntaktisk funksjon. I tillegg vil me sjølvsagt ikkje lenkje på tvers
av konstituentgrenser, sidan det er fullstendige konstituentar[fn:11]
som fyller dei semantiske rollene.

Eit anna mogleg formål er å nytte desse frasesamanstillingane til
maskinomsetjing. \citet{riezler2006gmt} nyttar ein stokastisk
frasesamanstilling til å oppdage transfer-reglar for bruk i LFG-basert
generering i maskinomsetjing. Dette er reglar som omsett fragment av
ein f-struktur på kjeldespråket til f-strukturfragment på
målspråket. (Eit krav på utforminga av moglege transfer-reglar hindrar
at ein får reglar som lenkjar ikkje-konstituentar, eg kjem tilbake til
dette nedanfor.)  Samanstillinga utvikla her burde au kunne nyttast
til å finne slike transfer-reglar, men dette er ikkje noko eg har lagt
vekt på.

Nedanfor gir eg eit forslag til krav for frasesamanstilling, med desse
formåla i tankane. Om alle krava er moglege å implementere, er eit
separat problem.

** Frasesamanstilling i ein LFG-trebank

Samanstilte frasar bør ha nok semantisk likskap til å kunne opptre som
omsetjingar i liknande omgivnader
\citep[s.~74]{dyvik2009lmp}. \citet{thunes2003eal} gir nokre prinsipp
-- som er passande å ha som utgangspunkt -- for å fastslå det som kan
kallast /omsetjingsmessig korrespondanse/ (her for
ordsamanstilling). Dette er prinsipp som skal gjelde for eit litt
forskjellig formål, men som au «ligger nær opp til det vi intuitivt
mener er riktig» \citep[s.~2]{thunes2003eal}. Prinsippa blir nytta til
å lage ein gullstandard for ordsamanstilling[fn:typetoken],
hovudsakleg for dei opne klassene, og er definert ved å vise til kva
for rolle eit argumentord speler, eller kva for rolletildeling eit
predikat eller modifiserande ord gir. Så for å t.d. samanstille to
verb må dei ha like mange semantiske argument (men argumenta treng
ikkje alle realiserast syntaktisk) og dei må /tildele same roller/;
medan argumenta må /spele same rolle/, og både argument og adjunkt må
vere /koreferente/. Lenkja ord må vere del av frasar som speler same
rolle i «det som er felles i interpretasjonene av [dei to setningane]»
\citep[s.~3]{thunes2003eal}.

# - /Anafori/: ulike _system_-setningar, like _tekst_-setningar
#   1) studenten ... studenten ...
#   2) the student ... he ...

Viss me tek utgangspunkt i det siste, vil det vere naturleg å i
tillegg lenkje desse frasane som speler same rolle i «det som er
felles i interpretasjonene».

Krava for ordsamanstillinga må au vere fylt for at desse frasane kan
samanstillast. Ei ordsamanstilling er altså naudsynt for ein
frasesamanstilling, og omvendt. Dette er berre problematisk om me
føreset at det eine er derivert av det andre; men dette har me ingen
\emph{a priori} grunn til å gjere. Krava eg her utviklar bør i staden
sjåast på som /skrankar/ på moglege samanstillingar i modellen (jamfør
\ref{SEC:omgrepsavklaring} om modellteoretiske grammatikkar), heller
enn derivasjonelle forhold. Samtidig er det som nemnt eit mål å finne
ut kor uavhengig me kan gjere oss av ordlenkjingsinformasjonen (dette
er au nyttig for implementasjonen), utan at det treng å gi krava ei
/retning/.

Ei frasesamanstilling er ei skildring av forhold mellom /fragment/ av
setningar, dette er endå ein grunn til at det er naturleg å skildre
dei ønskelege forholda som skrankar på moglege samanstillingar. Me kan
setje skrankar på f-struktur-, konstituent- og ordsamanstilling
samtidig, utan å måtte ha krav om at den eine samanstillinga er
fullstendig (eller delvis) avleiia av den andre, før me veit om eit
slikt avleiingsforhold er empirisk fundert. Me kan i tillegg ha
ufullstendige samanstillingar i dei tilfella der det er ufullstendig
samsvar mellom setningane (der ei fullstendig samanstilling ville
brutt visse krav).

Sidan metoden er mynta på bruk i ein LFG-parsa trebank, og delvis vil
nytte denne annotasjonen som datagrunnlag, er det naturleg å nytte
same konsept som blir nytta i LFG[fn:9] (f-struktur, c-struktur,
endosentrisitetsprinsipp, \xbar{}-tre, osb.)  au i desse krava til den
«beste» frasesamanstillinga; i den grad LFG gir ein generaliserbar
skildring av syntaks, bør desse krava vere generaliserbare til andre
teoriar, men ein del forhold som er avleidd av LFG-prinsipp må
sjølvsagt modifiserast om krava skal generaliserast til andre teoriar.

Utan skrankar i det heile vil alt kunne lenkjast til alt (noko som er
like unyttig som å ikkje lenkje noko); i del \ref{SEC:kandidatar} ser
eg på kva for typar element i dei lingvistiske analysane (ord,
grammatiske trekk, konstituentar, ...) det er fornuftig å tillate
lenkjer mellom. I avsnitta nedanfor spesifiserer eg kva som må til for
at me skal lenkje element av desse typane.

** Kva kan lenkjast?
\label{SEC:kandidatar}

Viss to uttrykk er samanstilt på setningsnivå (slik at me dimed kan gå
ut frå at dei er omsetjingar av kvarandre), og begge har ein
LFG-analyse, så har me iallfall tre ulike nivå kor me kan finne
ekvivalensforhold under setningsnivå:
1. mellom ord i setningane,
2. mellom f-strukturar, 
3. mellom c-strukturnodar.

På begge språk har me alle nivå -- det er ingen grunn til å lenkje på
tvers av nivå sidan forhold mellom desse nivåa er implisitt i
LFG-analysen.

Alle ord i setninga er /kandidatar/ for samanstilling med ord i
omsetjinga, men det kan godt hende at eit ord /ikkje/ har ei lenkje,
og me kan heller ikkje utelukke at det finst mange-til-mange-lenkjer
som ikkje kan «delast opp». Dette gjeld au nodane i c-strukturen.

Me utelukker lenkjing av ikkje-konstituentar som /there is/ på
c-strukturnivå sidan ei lenkje mellom to c-strukturnodar impliserer at
heile frasen under er lenkja. Det finst ingen c-strukturnoda som
dominerer berre /there/, /is/ og ingen andre ord (heller ikkje /es/,
/gibt/), så dette er ikkje lenkjekandidatar.  /There is/ og /Es gibt/
i figur \ref{fig:ikkjenode} kan då ikkje samanstillast åleine, men
berre som del av ei ytre frasesamanstilling.

Når det gjeld f-strukturane er det ganske mange element me teoretisk
sett kunne ha lenkja, t.d. enkelttrekk som kasus eller dei uordna
mengdene med adjunkt, men det som er mest /nyttig/ er nok å berre
lenkje der det er ei nær kopling til orda i setninga. Sidan alle
PRED-element i ein f-struktur unikt står for predikerande ord, kan me
-- gitt to samanstilte setningar -- la \emph{kandidatane for
samanstilling på f-strukturnivå} inkludere alle desse PRED-elementa i
f-strukturane til setningane[fn:12]. PRED-element representerer
semantiske bidrag som oftast er påkrevde på begge språk i omsetjingar,
medan andre f-strukturtrekk gjerne er valfrie på det eine av språka;
det er ikkje alle språk som har t.d. obligatorisk kasusmarkering, og
ein vil kanskje nytte trebanken til å oppdage nettopp slik variasjon.
\fxnote[inline,nomargin]{Diskutabelt, TODO:} PRED-elementa er i tillegg
gjerne enklare å knyte direkte opp mot den konkrete, observerte
tekststrengen, medan t.d. aspekt kanskje er umogleg å skilje frå
tempus i affikset.

Samtidig er det au eit omsetjingsforhold mellom trekka i same
f-struktur som dei lenkja PRED-elementa, og me ville kanskje ikkje ha
omsett dei to PRED-elementa i andre f-strukturkontekstar. Difor bør me
au sjå på ei PRED-lenkje som ei lenkje mellom \emph{f-strukturane til
desse PRED-elementa}[fn:7].  Med dette i tankane, kombinert med
c-struktur-f-strukturavbildinga $\phi$ (sjå del
\ref{SEC:omgrepsavklaring}), får me følgjande samanheng, illustrert i
figur \ref{fig:viss-PRED-så-f-og-c}:

\ex. \label{f-links} Ei lenkje mellom to PRED-element $p$ og $q$, kor
      $p$ er medlem av f-strukturen $f$, og $q$ er medlem av
      f-strukturen $g$, tilseier at:
\a. \label{f-links-substr} me tolkar f-strukturane $f$ og $g$ som lenkja,
\b. \label{f-links-words} orda i setningane som projiserer
     PRED-elementa tek del i ei lenkje (kor andre
     ord kan vere involvert), og at
\c. \label{f-links-domain} iallfall dei øvste nodane i $\phi^{-1}(f)$
     og $\phi^{-1}(g)$, dei funksjonelle domena til f-strukturane $f$
     og $g$, er lenkja 

#+BEGIN_LaTeX
 \begin{figure}[htp]
    \centering
    \begin{tikzpicture}
    {\avmoptions{}
     \node(src){
        \begin{avm}
          $f$ \[pred  & `{\bf{}sove}<jeg>' \\
          tense & pret \\
          ... \]
        \end{avm}
      };
      \node[right of=src, node distance=5cm](trg){
        \begin{avm}
          $g$ \[pred   &  `{\bf{}sleep}<I>'\\
          tense  & pret  \\
          aspect & simple \\
          ... \]
        \end{avm}
      };
      }
      \draw[dashed,-] (src.west) .. controls +(-1,2) and +(-1,2) .. node[above,sloped]{$l_f$} (trg.west) ;
      \draw[-] ($(src.north)-(1,0.3)$) .. controls +(0,1.5) and +(0,1.5) .. node[above,sloped]{$l_p$} ($(trg.north)-(1,0.3)$) ;

      \begin{scope}[shift={(0,-3cm)}]
     \Tree  [.\node(VPs){VP}; [.\node(Vs){V}; \node(sov){sov};  ] ]
      \begin{scope}[shift={(5cm,0)}]
        \Tree  [.\node(VPt){VP}; [.\node(Vt){V}; \node(slept){slept};  ] ]
      \end{scope}
      \end{scope}
      \draw[-] (VPs)..controls +(north:1.5) and +(north:1.5) .. node[above,sloped]{$l_c$} (VPt) ;
      \draw[dashed,-] (sov)..controls +(north east:1.5) and +(north west:1.5) .. node[above,sloped]{$l_o$} (slept) ;
   \end{tikzpicture}
    
\fxnote{TODO: teikne inn f-domene}

    \caption{Ei PRED-lenkje $l_p$ kan tolkast som ei f-strukturlenkje
    $l_f$, og impliserer ei c-strukturlenkje $l_c$ mellom toppnodane i
    dei funksjonelle domena. Orda som projiserer PRED-elementa er med
    i ei lenkje $l_o$ (som kan inkludere fleire ord).}
   \label{fig:viss-PRED-så-f-og-c}
 \end{figure}
#+END_LaTeX

Punkt \ref{f-links-substr} og \ref{f-links-domain} over seier at viss
PRED-elementa projisert av t.d. to verb i verbfrasar er lenkja, vil
VP-ane som heilskap vere lenkja (både VP-nodane som dominerer dei
lenkja funksjonelle domena, og f-strukturane frå ytre PRED til verba),
det er dette at heile VP-ane er lenkja som gjer det til ei fraselenkje
og ikkje berre ei ordlenkje. Punkt \ref{f-links-substr} er forsvart
over, medan punkt \ref{f-links-domain} kjem som ein konsekvens av at
øvste node dominerer alle nodar i det funksjonelle domenet; det er det
funksjonelle domenet som spesifiserer informasjonen i f-strukturane,
toppnodane dominerer heile dette domenet og bør difor lenkjast viss og
berre viss f-strukturane er lenkja.  

Alle nodar i c-strukturen (alle syntaktiske /frasar/konstituentar/ i
setninga) som kan koplast til PRED-haldande f-strukturar, vil vere
kandidatar for samanstilling på c-strukturnivå (dette inkluderer
diskontinuerlege konstituentar), men ikkje alle vil bli lenkja.  I del
\ref{SEC:subnode} ser eg på kva som må til for å lenkje ikkje-øvste
nodar i det funksjonelle domenet.
I tillegg finst det nodar over ord som ikkje projiserer PRED-element,
desse kjem eg tilbake til i del \ref{SEC:fnord}.

I følgje punkt \ref{f-links-words} vil fraselenkja leie til at sjølve
verba i to lenkja VP-ar au er lenkja, som tilseier at /ei PRED-lenkje
impliserer ei ordlenkje/. I visse tilfelle er dette heilt
uproblematisk, t.d. viss /I slept down by the river/ skal lenkjast med
\emph{Eg sov nede med elva} vil me uansett lenkje /slept/ og /sov/; dette
kan gjelde transitive verb au:

\ex. \a. The locusts have no king, just noise and hard language\\
     $\leftrightarrow$
     \b. Grashoppene har ingen konge, berre støy og krasse ord


#+BEGIN_LaTeX
\emph{have/har} tek del i VP-samanstillinga \emph{have no king.../har
ingen konge...}, her au skal det vere uproblematisk å lenkje
enkeltorda \emph{have} og \emph{har}.

Men som nemnd treng ikkje ordsamanstillinga vere ein-til-ein, det
punkt \ref{f-links-words} seier er at desse orda iallfall er ein del
av ein samanstilling med kvarandre (i døme \Last altså
VP-samanstillinga). Kanskje er dette ei mange-til-mange-lenkje som
ikkje \emph{kan} reduserast til ein-til-ein-lenkjer; eller kanskje er
det som i \Last mogleg å skilje ut delsamanstillingar, som
\emph{have/har}. Eg kjem tilbake til dette
\fxnote[inline,nomargin]{TODO: når?} seinare.
#+END_LaTeX

Sidan PRED-lenkjing impliserer ordlenkjing, må me sjekke om krava på
ordnivå (del \ref{SEC:ordkrav}) er oppfylte for å lenkje to
PRED-element. \fxnote[inline,nomargin]{TODO: litt brå avslutning}

** Forholdet mellom ordlenkjer og PRED-lenkjer 			     :ROTETE:
\fxnote{der ADJUNKT ikkje er realisert, lenkjer me ikkje PRED.  skal
me då ikkje lenkje ord heller?}

\fxnote{finst det tilfelle der ordlenkjer ikkje impliserer PRED-lenkjer? 
\\
(hypotese: det er alltid slik at ordlenkjing av predikerande ord => PRED-lenkje)
\\
PRED->ord :: iallfall\\
PRED<-ord :: ?\\
PRED<->ord\\
PRED, ord}

** Krav på ordnivå
\label{SEC:ordkrav}

Ord som skal lenkjast må i \cite{thunes2003eal} vere del av frasar som
speler same rolle i det som er felles i interpretasjonane, her kan me
omskrive det til at dei må vere del av /frasar som er lenkja på
c-strukturnivå/; forholda i \ref{f-links} gir då koplinga til krav på
andre nivå (t.d. vil krav om tildeling av like mange roller vere
meir passande å spesifisere på f-strukturnivå).

Det er visse ting me ikkje kan spesifisere ut frå rein c- og
f-strukturinformasjon. Den norske setninga /eg vil ete/ kan fint
samanstillast med /I want to eat/, med ei lenkje mellom /ete/ og
/eat/. Men kva står i vegen for å lenkje /ete/ til hovudverbet i /I
want to drink/? Forskjellen på f-strukturnivå er berre at PRED-verdien
er ulik (*eat* mot *drink*). Me må altså ha eit krav om at tydinga til
lenkja ord (og deira predikat) er «lik nok» til at me kan sjå på dei
som omsetjingar[fn:21]. \citet[s.~74]{dyvik2009lmp} krev dei at orda
generelt, utan kontekst, må vere semantisk plausible omsetjingar,
eller at målordet er eit medlem av mengda av /linguistically
predictable translations/ av kjeldeordet. Målordet har då
\emph{LPT-korrespondanse} med kjeldeordet. Informasjon om slik
LPT-korrespondanse kan komme frå ei djup semantisk dekomponering av
kvart ord, då blir det eit krav på f-strukturnivå (eller på ein
semantisk struktur), eller han kan komme bottom-up, typisk frå
automatisk ordsamanstilling. Bottom-up-informasjonen viser då om orda
generelt (i ulike kontekstar) blir nytta som omsetjingar av kvarandre.
Nedanfor reknar eg LPT-kravet som eit krav på ordnivå.

\fxnote{TODO: Er det mogleg å presisere LPT-kravet meir? Skal det
berre vere eit rangeringskrav??}
 
Ein type presisering/depresisering (del \ref{SEC:formaal}) me ofte ser
i omsetjingar er at eit pronomen på kjeldespråket blir nytta der
målspråket har eit koreferent substantiv, eller
omvendt. \citet{dyvik2009lmp} opnar for at desse au har
LPT-korrespondanse (som nemnt i \cite{thunes2003eal} må lenkja ord
uansett vere koreferente).

Men kva då med lenkjing av pronomen til verb bøygd for person og tal i
pro-drop-språk?

\ex. \a. iqePa                                  \hfill{} (georgisk) \\
     $\leftrightarrow$
     \b. han bjeffa

Viss setningane i døme \Last er lenkja, der iqePa har eit pro-argument
koreferent med /han/ som subjekt, bør dei to subjekta iallfall kunne
lenkjast på f-strukturnivå; dei har same referent og speler same rolle
i argumentstrukturen til verba (som me går ut frå er lenkja). På
ordnivå, derimot, kan me ikkje lenkje /han/ til /iqePa/ åleine -- her
må me ha ei mange-til-ein-lenkje mellom $\{ \rm han, bjeffa \}$ og $\{
\rm iqePa \}$. 
Generelt må me ha slike lenkjer der eitt ord projiserer fleire
PRED-element[fn:13].

*** Ordklasse
Ulike språk leksikaliserer same konsept på ulike
måtar. \citet[s.~3]{cheung2002scg} nemnar vanskane med å ha eit krav
om lik ordklasse i utviklinga av ein kinesisk-engelsk termbank, kor
t.d. det engelske ordet /fulfilment/ meir naturleg blir omsett til eit
verb på kinesisk. På same måte vil eit georgisk verbalsubstantiv
(/masdar/) gjerne bli omsett til eit verb i infinitiv på
norsk. Slike skifte mellom ordklasser er svært vanlege i
omsetjing[fn:3].

Me kan opne for ordklasseoverskridande lenkjer der det er samsvar på
andre nivå, me bør iallfall krevje ein likskap i argumentstruktur; så
om LPT-kravet og krava på c- og f-strukturnivå er fylt, bør det ikkje
vere noko i vegen for å lenkje ord (eventuelt mengder av ord) av ulik
ordklasse.


** Krav på f-strukturnivå
\fxnote{problematiser: må me ha /PRED-lenkje/ frå arg til arg/adj? (ikkje
    krevd no...men skal me rangere ved det?)}
\fxnote{kryssande f-lenkjer?}
\fxnote{mange-mange-f-lenkjer?}
 
På f-strukturnivå har me direkte tilgang til informasjon om
argumentstrukturen til eit predikat, og mengda av adjunkt som
modifiserer predikatet. Når \citet[s.~3]{thunes2003eal} skriv at to
lenkja ord $a$ og $b$ må opptre i frasar som har «tilstrekkelig like
argumentstrukturer til at uttrykkene i \emph{a}s omgivelser står i de
samme semantiske relasjonene til hverandre og til \emph{a} som de
korresponderende uttrykkene i \emph{b}s omgivelser gjør til hverandre
og til \emph{b}» er det difor passande å prøve å gjere dette til eit
krav på f-strukturnivå.

Den enklaste lenkjingssituasjonen, f-strukturmessig, er der
rotpredikata kan lenkjast, og første argument av predikatet på
kjeldespråket kan lenkjast til første argument på målspråket, andre
argument til andre argument, osb., og lenkjinga kan fortsetje slik
rekursivt inn i f-strukturane. I ein slik situasjon er det fullstendig
samsvar mellom kor mange argument det finst på kvar side, og
fullstendig samsvar i det tematiske rollehierarkiet (dvs. kva for
posisjon kvar rolle har i argumentstrukturen), i heile strukturen.

Som me skal sjå er det ikkje vanskeleg å komme over situasjonar der
dette ikkje held, og me blir nøydt til å tillate lenkjer mellom
argument og adjunkt, og lenkjer som går på tvers av følgja i
argumentstrukturane. I tillegg kan me ikkje klare oss utan
LPT-informasjon for å avgjere /når/ me har å gjere med slike meir
komplekse situasjonar. 
*** Krav om lik argumentstruktur
\label{SEC:lik-argstr}

\citet{thunes2003eal} gir som nemnd eit krav om at /predikat må ha
tilsvarande semantiske argument/ for å lenkjast.

Om det alltid er slik at to predikat har like mange argument, som kjem i
same rekkjefølgje i argumentstrukturen, vil det gjere den praktiske
oppgåva med å lenkje predikata, og argument med argument, mykje
enklare. Men kan me stille så sterke krav?

Sett at ein setning på språk 1 har ei /at/-setning som adjunkt, medan
denne setninga på språk 2 er eit argument, og at desse setningane
ville vore lenkja om dei opptredde åleine. Om dei uttrykkjer same
proposisjon og \emph{speler same rolle i verbsituasjonen},
synest det naturleg å lenkje desse.  

Slike omsetjingsrelasjonar gir data for verbsituasjonen, på eit meir
generelt grunnlag enn det me kan få frå einspråklege analysar
åleine. Om me har gode semantiske grunnar for å kalle ein deltakar i
ein verbsituasjon eit argument på eitt språk, vil dei same grunnane
gjelde for omsetjingsmessig korresponderande verb på andre språk. Ein
kan då nytte unionen over alle argument til korresponderande verb til
å karakterisere kva ein meiner med /deltakarane i
verbsituasjonen/. Syntaktiske forhold i språket kan sjølvsagt gi
grunnar til å /ikkje/ kalle dette eit argument.
 
For å gjere dette konkret kan me sjå på setning 7 i test-suiten til
XPar-prosjektet:

\exg.  abramsi brouns       daenajleva sigaretze, rom cvimda \\
      Abrams.NOM Brown.DAT vedde.3SG sigarett.om, at  regne.3SG.IMP \\
     `Abrams veddet en sigarett med Brown på at det regnet' 

I følgje LFG-parsen til desse setningane har hovudpredikata svært ulik
argumentstruktur[fn:14]. Det norske /vedde/ har _fire_ argument, medan
\emph{da-najleveba} har _to_ (/Abrams/ og /Browne/), kor at-setninga på
norsk og /rom cvimda/ uttrykkjer same proposisjon og speler same rolle
i verbsituasjonen. Den engelske LFG-parsen av den tilsvarande setninga
(mine omsetjingar) gir _tre_ argument, /with/ blir her adjunkt, medan
den tyske grammatikken, som au har _tre_ argument, gjer /at/-setninga
til adjunkt. I \Next nedanfor har eg representert dei omsetjingsmessig
korresponderande frasane i f-strukturane med dei norske omsetjingane
for å illustrere dette:

#+BEGIN_LaTeX
{\avmoptions{}
\ex. \label{vedde}
\a. Adams veddet en sigarett med Browne \hfill{} (norsk bokmål)\\ på at det regnet.\\
    $\\\begin{avm}\[pred & `{\bf{}vedde}<Abrams, sigarett, Browne, regne>' \\
                 adjunct & \{\}\]\end{avm}\\$
\b. abramsi brouns daenajleva sigaretze, rom cvimda. \hfill{} (georgisk)\\
    $\\\begin{avm}\[pred &  `{\bf{}da-najleveba}<Abrams, Browne, regne>'\\
    adjunct &  \{ \rm sigarett \}\]\end{avm}\\$ 
\c. Abrams hat mit Browne um eine Zigarette gewettet, \hfill{}(tysk)\\
    daß es regnet.\\
    $\\\begin{avm}\[pred & `{\bf{}wetten}<Abrams, sigarett>' \\
                  adjunct & \{ \rm Browne, sigarett \}\]\end{avm}\\$
\d. Abrams bet a cigarette with Brown that it was raining. \hfill{}(engelsk)\\
    $\\\begin{avm}\[pred & `{\bf{}bet}<Abrams, sigarett, regne>'\\
                  adjunct & \{ \rm Browne \}\]\end{avm}$

}
#+END_LaTeX

Om ein skal ha grammatikkane som datagrunnlag er det altså eit reellt
problem kva ein skal gjere med mangel på samsvar i
argumentstruktur. Om det alltid var fullstendig samsvar i
argumentstruktur, ville det vore trivielt å lenkje argument: viss to
korresponderande verb hadde tre argument, ville me lenkja det første
med det første, det andre med det andre og det tredje med det
tredje. Men om me har analysar som dei over, ser det ut til at me er
avhengig av LPT-kravet frå del \ref{SEC:ordkrav} for å avgjere kva for
adjunkt og argument som samsvarer.

Det same gjeld forøvrig lenkjing av adjunkt til adjunkt. Adjunkt
plukker ut si eiga rolle der argument får rolla tildelt frå verbet, og
f-strukturane har ingen hierarkisk inndeling av desse slik me har for
verb og argument, dei er i staden representert som uordna mengder.

*** SKRIV Sitere eigen korpusundersøking av variasjon i arg-str?
Ei undersøking av den frasesamanstilte trebanken SMULTRON
\citep{samuelsson2006pap} mot LFG-grammatikkane for engelsk og tysk
fann at 2 av 15 korresponderande verbtoken[fn:15] for høgfrekvente
innhaldsverb fekk analysar kor argument korresponderte med adjunkt
\citep{unhammer2009aaa}.

\fxnote{LCS, dorr}
*** SKRIV kvifor lik arg-str er bra, så kvifor det er eit problem    :ROTETE:
*** SKRIV Ulik følgje i argumentstruktur
I tillegg til at argument kan lenkjast til adjunkt, kan koreferente
argument ha ulik følgje i argumentstrukturen. Det er klart at me vil
lenkje objektet til /gefallen/ (eller bokmål: /behage/) med subjektet
til /like/, og omvendt.  Men rekkjefølgje i argumentstrukturane i
ParGram-prosjektet er ofte basert på syntaktisk funksjon heller enn
rolle, slik at eit verb som har opplevar som objekt og tema som
subjekt vil ha opplevar nedanfor tema i argumentstrukturen, medan ei
omsetjing av dette verbet kan ha tema nedanfor:

#+BEGIN_LaTeX
{\avmoptions{}
\ex. \a. sie$_j$ gefallen ihnen$_i$ \\
     $\begin{avm}\[pred & `{\bf{}gefallen}<de$_j$, de$_i$>' \]\end{avm}$
    $\\\\\leftrightarrow$\\
     \b. de$_i$ liker dem$_j$ \\
     $\begin{avm}\[pred & `{\bf{}like}<de$_i$, de$_j$>' \]\end{avm}$

}
#+END_LaTeX

Argumentstrukturane i \Last har omvendt intern følgje, og som vist ved
dette dømet er det heller ikkje noko f-strukturinformasjon me kunne
nytta til å sikre lenkjinga /sie/dem/ og /ihnen/de/. Igjen ser det ut
til at bottom-up-informasjon trengst.



**** c- og f-strukturar for dømet over				     :ROTETE:
#+BEGIN_LaTeX
\begin{tikzpicture}
\Tree
[.CP
  [.DP \edge[roof]; {sie} ]   [.C'
    [.V
 \edge[roof]; {gefallen} ]     [.DP \edge[roof]; {ihnen} ]  
]]
\begin{scope}[shift={(2in,0in)}]
\Tree
[.IP
  [.PRONP \edge[roof]; {de} ] 
  [.I'
    [.V \edge[roof]; {liker} ] 
    [.S \edge[roof]; {dem} ] 
]]
  \end{scope}
\end{tikzpicture}

\avmoptions{}
\begin{avm}
\sort{$^{0}$}{\[ {\sc pred} `{\bf gefallen}<[1:{\it pro}],[2:{\it pro}]>'\\
{\sc topic} \sort{$^{1}$}{\[ {\sc pred} `{\it pro}'\\
{\sc ntype} \sort{$^{7}$}{\[ {\sc nsyn} pronoun\]}
\\
{\sc pron-type} pers, {\sc pron-form} sie, {\sc pers} 3,\\
{\sc num} pl, {\sc case} nom\]}
\\
{\sc tns-asp} \sort{$^{4}$}{\[ {\sc tense} pres, {\sc mood} indicative\]}
\\
{\sc obj-th} \sort{$^{2}$}{\[ {\sc pred} `{\it pro}'\\
{\sc ntype} \sort{$^{10}$}{\[ {\sc nsyn} pronoun\]}
\\
{\sc pron-type} pers, {\sc pron-form} sie, {\sc pers} 3,\\
{\sc num} pl, {\sc case} dat\]}
\\
{\sc subj} \[1\]\\
{\sc vtype} main, {\sc stmt-type} decl,\\
{\sc passive} -, {\sc clause-type} decl\]}
\end{avm}




\begin{avm}
\sort{$^{0}$}{\[ {\sc pred} `{\bf like}<[10:de],[11:de]>NULL'\\
{\sc tns-asp} \sort{$^{13}$}{\[ {\sc tense} pres, {\sc mood} indicative\]}
\\
{\sc topic} \sort{$^{10}$}{\[ {\sc pred} `{\bf de}'\\
{\sc ntype} \sort{$^{18}$}{\[ {\sc nsyn} pronoun\]}
\\
{\sc def} +, {\sc case} nom, {\sc ref} +,\\
{\sc pron-type} pers, {\sc pron-form} de, {\sc pers} 3,\\
{\sc num} pl\]}
\\
{\sc obj} \sort{$^{11}$}{\[ {\sc pred} `{\bf de}'\\
{\sc ntype} \sort{$^{45}$}{\[ {\sc nsyn} pronoun\]}
\\
{\sc ref} +, {\sc pron-type} pers, {\sc pron-form} de,\\
{\sc pers} 3, {\sc num} pl, {\sc def} +,\\
{\sc case} obl\]}
\\
{\sc subj} \[10\]\\
{\sc vtype} main, {\sc vform} fin, {\sc stmt-type} decl\]}
\end{avm}

#+END_LaTeX

*** SKRIV døme med wager/3 og vedde/4 og gewettet/3 		     :ROTETE:

*** SKRIV (reinskriv) 						     :ROTETE:
Same globale tyding krev i det minste at, i situasjonen verbet
denoterer, speler deltakarane same rolle. Men dette er endå meir
abstrakt/semantisk enn (semantisk) argumentstruktur...

Problem: ikkje-komposisjonell omsetjing. Same globale tyding. Det
treng ikkje vere berre pragmatisk forskjell--type /kan du lukke døra/
vs /lukk døra/, kor situasjon gjer setningane like--sidan me kan ha
konvensjonaliserte konstruksjoner på L1 kor heile tilsvarer enkeltord
på L2, a la japansk /viss eg ikkje går på skulen så kan det ikkje
vere/ ~= /eg må gå på skulen/. 

Ein føresetnad eg har, er at setningar som er samanstilte faktisk har
ein omsetjingsmessig korrespondanse (dette er min data). Så om eit par
av ytre predikat ikkje korresponderer er det au ein type data; nemleg
at me har ein omsetjingsmessig korrespondanse der det var ein mismatch
i ytre argumentstruktur. (Algoritmen bør då lagre slike mismatches
eksplisitt, ikkje berre la vere å lenkje, for det kan vere andre
grunnar til at det ikkje kom ei lenkjing. A la ekspertsystem: forklare
resonnementet.)

Alternativt ein konstruksjonslenkjing... 

Kan au ha eit krav om at argstr til $PRED_{L1}$ er ein slag delmengd av
argstr til $PRED_{L2}$. 
*** SKRIV True Arguments vs True Adjuncts, Pustejovsky 		     :ROTETE:
   - Treng døme først...
   - Er «with Browne» eit Default Argument for «wager»?
     - D-ARG: he built a house _out of bricks_
   - Adjunkt plukker ut sine eigne roller, per definisjon, ved
     vedde/4 og wager/3 har me ein slik situasjon:
     : vedde <—————wager >———<———wetten
     :        \____with_/     \__dass
     Bottom-up-informasjon vil au vere naudsynt for dei 3 rollene
     som /er/ argument, sidan me kan ha vedde<1,2,3,4> og
     wager<a,b,c>with<d>, kor det er umogleg å seie om d skal på plass
     1,2,3 eller 4 (dvs. me kan ha vedde<a,b,c,d>, vedde<a,b,d,c>,
     vedde<a,d,b,c> og vedde<d,a,b,c> -- men sannsynlegvis er altså
     a,b,c i same rekkjefølgje uansett...)

*** TOGROK mange-til-mange-lenkjing i f-strukturane?		     :ROTETE:
    Kva inneber ei mange-til-mange-lenkjing? 

    Eg er litt usikker på om me skal ha slike
    mange-til-mange-korrespondansar i f-strukturane; eg har rekna med
    at ei f-strukturlenkje /impliserer/ ei slag lenkjing mellom det som
    er innanfor f-strukturane; men i \citet{riezler2006gmt} er det i
    staden berre eit krav om at desse f-strukturane er lenkja i same
    transfer-regel.

# Ikkje-komposisjonell mange-til-mange-lenkjing 

\citet[s.~40--41]{riezler2006gmt} tillet mange-til-mange-lenkjing
mellom f-strukturar, så lenge alle f-strukturane som blir lenkja til
slutt opptrer i same transfer-regel. Frå følgjande setningspar:

\ex. Dafür bin ich zutiefst dankbar \\
     I have a deep appreciation for that

lenkjar dei \{/zutiefst/\} med \{ /a, deep, appreciation/ \}, men
sidan \{/appreciation/\} er samanstilt med \{/dankbar/\}, må
transfer-regelen inkludere \{ /zutiefst, dankbar/ \} på den eine sida
og \{ /a, deep, appreciation/ \} på den andre.




*** SKRIV Kan adjunkt lenkjast til nodar _under_ mor-lenkja?
\label{SEC:merge-daughters}

Krav (vi) i \citet[s.~75]{dyvik2009lmp} krev at viss F_s og F_t er
lenkja, så kan ingen adjunkt D_s til F_s vere lenkja til nodar utanfor
F_t. Men kan ein D_s lenkjast til ei dotternode av argument eller
adjunkt til F_t?

R_t er dotter til F_t, og må då vere lenkja til ei dotter av F_s,
A_s. Då må au alle argument til R_t vere lenkja til døtre av A_s, så
D_s kan ikkje lenkjast til argument av dotternodar til F_t. Kva med
adjunkt? Om me finn eit ulenkja adjunkt til R_t kan me heller ikkje
lenkje dette til D_s ved krav (vi) igjen, sidan D_s står utanfor
A_s.

Men om D_t er ei ulenkja \emph{adjunkt}dotter av F_t, så vil døtre av
D_t kunne lenkjast til D_s, så lenge D_t forblir ulenkja. Me kan altså
sjå ned i adjunktdøtre av F_t for å lenkje D_s. 

På same måte bør ein kunne rekursivt sjå ned i ulenkja adjunktdøtre av
R_t, men ein bør kanskje ikkje kunne lenkje så djupt uansett? Ikkje
automatisk, uansett.



Programmet mitt vil, gitt to initielle f-strukturar med
LPT-korrespondanse, finne alle moglege kombinasjonar av lenkjer som
inneheld alle argument og kanskje adjunkt, dvs. om me har

: F_s [ PRED p<1,2> ADJUNCT { 3 } ]

: F_t [ PRED p<4> ADJUNCT { 5,6 } ]

vil dette vere logisk moglege samanstillingar av «f-strukturdøtre»:

:    (((1 . 4) (2 . 5)) ((1 . 4) (2 . 6)) ((1 . 5) (2 . 4))
:     ((1 . 5) (2 . 6) (3 . 4)) ((1 . 6) (2 . 4)) ((1 . 6) (2 . 5) (3 . 4)))

Me luker ut kombinasjonar som bryt med LPT-korrespondanse. Med full
informasjon bør me sjølvsagt berre ende opp med éin kombinasjon,
t.d. =((1 . 4) (2 . 5))=.

Så langt bør altså krav (i-iv) frå \citet{dyvik2009lmp} vere dekkja.

Me _kan_ krevje at f strukturane-til f strukturdøtre-kan lenkjast
rekursivt for at F_s og F_t skal lenkjast, t.d. både =(1 . 4)= og =(2
. 5)=. Men her kjem det (iallfall) to problem.


**** 1. Kausativar og inkorporering
Om me har 

: F_s [ PRED p<SUBJ, 1, 2> XCOMP 2[ PRED q<1> ] ]

: F_t [ PRED pq<SUBJ,OBJ> ]

kor pq er t.d. ein kausativ som tilsvarer =p<..., q>=, så vil me ikkje
kunne lenkje F_s og F_t sidan det bryt med krav (iii), F_s har eit
argument for mykje. Men her vil det kanskje vere naturleg å ha ei
ein-mange-lenkje:

: ((F_s 2) . F_t)

No kan me sjå på unionen av argument av F_s (minus XCOMP) og argument
av XCOMP, alle argument i denne unionen må då ha LPT-korrespondanse
med argument/adjunkt av F_t, og alle argument av F_t må ha
LPT-korrespondanse med argument/adjunkt av unionen.

Det same bør kanskje skje ved vanleg inkorporering av substantiv, då
må det altså vere mogleg å føye saman t.d. verb og objekt; ein
kombinasjon av dette og kausativ bør vel vere mogleg, t.d.

: F_s [ PRED la<SUBJ, 1>  XCOMP 2[ få<1, 3:pengar> ] ]

: F_ t [ PRED belønn<SUBJ, 1> ]

Igjen ser me på argument frå unionen av =(F_s 2 3)= minus 2 og 3, og
om det er mogleg å lenkje dei til argument/adjunkt av F_t, og omvendt.

Men det bør kanskje vere grenser for kor langt samanføying kan gå… eg
kan ikkje tenkje meg at me vil lenkje =((F_s 2) . F_t)= eller =((F_s
1 2) . F_t)= her:

: F_s [ PRED p<…, 1> XCOMP 1[ PRED q<…, 2> XCOMP 2[ PRED r<…> ] ] ]

: F_t [ PRED pr<…> ]

...men det kan jo hende det finst situasjonar der dette au vil vere
rett. Problemet er altså kor me skal setje grensene i
implementasjonen. Om me skal prøve å samanføye på alle moglege måtar
(altså, der me ikkje har informasjon om LPT), i tillegg til «vanlege»
lenkjer, blir det fort komputasjonelt vanskeleg. Me kan sjølvsagt snu
på LPT-kravet her, og seie at dette er berre lov der me har positiv
informasjon om LPT-korrespondanse, i staden for at det ikkje er lov om
me har motstridande LPT-informasjon, det vil nok hjelpe, men det er
vanskeleg å finne prinsipelle avgrensingar her. 
***** TOGROK adjunkt bør ikkje samanføyast? eller?		     :ROTETE:
Det einaste eg kan
tenkje meg er at adjunkt ikkje bør vere kandidatar for samanføying (i
såfall burde dei vel heller vore analysert som argument?).

**** 2. Adposisjonsobjekt

I følgjande setningspar har me eit objekt «sigarett» som svarer til
PP-en «sigaretze» («sigareti» + «ze»), eit adjunkt:

: Abrams veddet en sigarett med Browne på at det regnet.
: abramsi brouns daenajleva sigaretze, rom cvimda.

: F_s [ PRED sigarett ]

: F_t [ PRED ze<1> 1[ PRED sigareti ] ]

F_s og F_t er døtre av dei ytre predikata i kvar setning, krav (iii)
seier at det må vere LPT-korrespondanse mellom desse for at me skal
kunne lenkje «veddet» og «daenajleva».  Her synest det feil å føye
saman «sigareti» og «ze», =(F_s . (F_t 1))=, sidan «sigarett» ikkje
inneheld informasjonen gitt av «ze».

Det finst då to løysingar. Me kan slakke på LMT-kravet ved å la
=L'(F_t) = {sigaretze, ze}= (evt. ={sigaret, ze}=), då kan me lenkje
=(F_s . F_t)=, medan 1 er ulenkja.

Eller me kan lenkje =(F_s . 1)=, kor me har skikkeleg
LMT-korrespondanse, men då må me slakke på (iii) og (iv), og altså ha
lov til å «hoppe over» ein f-struktur for å lenkje «veddet» og
«daenajleva». F_t er då ulenkja. Det er løysinga valt i
\citet[s.~75,~fotnote~3]{dyvik2009lmp}, og den løysinga eg følgjer
vidare i oppgåva.

** Underordna c-strukturnodar
\label{SEC:subnode}

Toppnodane i to funksjonelle domene som er lenkja på f-strukturnivå
vil ha ein informasjonsmessig korrespondanse, og kan, som nemnt i del
\ref{SEC:kandidatar}, utan vidare lenkjast. Men det er mogleg å lenkje
desse toppnodane, t.d. XP på kjeldespråket og ZP på målspråket, utan
at nodane under (X', Z') er lenkja til noko. I denne delen går eg
gjennom kva som må til for å lenkje slike underordna (ikkje-øvste)
c-strukturnodar.

Me kan byrje med eit par enkle krav, me seinare utvidar:

\ex. Enkle krav for lenkjing av underordna c-strukturnodar:
\a. \label{subnodekrav-innan-domene} c-strukturnodar som ligg under øvste node i to funksjonelle
    domena kan berre samanstillast med nodar som ligg innanfor desse
    domena,
\b. \label{subnodekrav-f-lenkja} c-strukturnodar kan berre samanstillast om deira funksjonelle
    domene er lenkja på f-strukturnivå

\Last[a] seier at om XP og ZP er lenkja, der XP og ZP er toppnodar,
kan ikkje dotter til XP, X', lenkjast med t.d. mor eller søster til
ZP. Og om ZP dominerer ein node WP, der $\phi(WP) \neq \phi(ZP)$, kan
me heller ikkje ha ei c-strukturlenkje frå X' til WP. Grunnen er at
f-strukturane er sett saman av informasjonsinnhaldet projisert av
nodane, så det vil vere unaturleg å ha ei c-strukturlenkje som står i
konflikt med f-strukturlenkjer.

Men sjølv der to underordna c-strukturnodar er i lenkja funksjonelle
domene (altså, der dei respektive toppnodane er lenkja) er det ikkje
alltid slik at me vil lenkje dei underordna nodane. I figur
\ref{fig:subnode} er XP og ZP to lenkja toppnodar i som inkluderer
høvesvis X' og Z' i dei funksjonelle domena. Her kan me ha gode
grunnar for å ikkje lenkje X' og Z'. 

#+BEGIN_LaTeX
\begin{figure}[htp]
\centering
  \begin{tikzpicture}
  \Tree  [.\node(XP){XP};  \node(YP){YP};  
                                    \node(X'){X'};   ]
      \begin{scope}[shift={(2in,0in)}]
  \Tree  [.\node(ZP){ZP};  \node(WP){WP};  
                                    \node(Z'){Z'};   ]
\end{scope}
\draw[-] (XP)..controls +(north east:1) and +(north:1) .. (ZP) ;
\draw[dashed,-] (X')..controls +(south:1) and +(south:1) .. node[above,sloped]{?} (Z') ;
%\draw[dashed,-] (YP)..controls +(south:1) and +(south:1) .. node[below,sloped]{manglar} (WP) ;

\end{tikzpicture}
   \caption{Lenkjing av underordna c-strukturnodar}
   \label{fig:subnode}
  \end{figure}
#+END_LaTeX

Éin grunn til å ikkje lenkje desse underordna nodane, er viss YP og WP
i figur \ref{fig:subnode} ikkje er lenkja, og det finst informasjon
som korresponderer mellom X' og WP eller mellom Z' og YP; dette gir
eit mangel på samsvar mellom X' og Z'.  Ein annan situasjon der me
ikkje vil lenkje X' og Z' er når WP ikkje finst og YP har informasjon
som på målspråket blir spesifisert av nodar under Z'.

Når treet deler seg i to som i figur \ref{fig:subnode}, får me ei
mogleg oppdeling av kjeldene til f-strukturinformasjonen. Me vil ikkje
lenkje nodar som ikkje gir same tilskot til f-strukturen, på same måte
som me ikkje vil lenkje på tvers av f-strukturlenkjer. I begge
situasjonane nemnt i avsnittet ovanfor er det slik at X' og Z' gir
ulike tilskot til f-strukturen, dei kan difor ikkje lenkjast. Likevel
må me tillate litt slingringsmonn her, X' og Z' skal ikkje trenge
projisere heilt like f-strukturar. Det som er relevant er det som blir
lenkja i f-strukturen, eller /kva for lenkjer som finst mellom
f-strukturane til nodane under/.

For å gjere dette meir konkret kan me sjå på dømet i figur
\ref{fig:ikkjesub}. IP-nodane er her lenkja, men me kan ikkje lenkje
I'-nodane i same funksjonelle domene. PRONP-noden, spesifikator på den
norske sida, er ikkje lenkja med nokon spesifikator på den georgiske
sida. Den informasjonen (her reint syntaktisk) som ordet /det/
tilfører IP, ligg under I' på georgisk. Me kunne lenkja I' om me hadde
ein georgisk spesifikator som var lenkja til den norske PRONP. Me kan
heller ikkje lenkje Vfin til V, her manglar endå meir informasjon
(både frå /det/ og frå /seg/). 

#+BEGIN_LaTeX
\begin{figure}[htp]
\centering
\begin{tikzpicture}
\Tree [.\node(IPk){IP}; 
  [.\node(Ibark){I'};  [. \node(Vk){V};  \node(gaiGo){gaiGo};  ]
  ] ]
     \begin{scope}[shift={(2in,0in)}]
\Tree [.\node(IPb){IP}; 
  [.PRONP \edge[roof]; {det} ] 
  [.\node(Ibarb){I'};  [.\node(Vfinb){Vfin};   \node(åpnet){åpnet};  ]
       [.S \edge[roof]; {seg} ] ] ]
\end{scope}
 \draw[-] (IPk)..controls +(north:1) and +(north:1) .. (IPb) ;
  \draw[dashed,-] (Ibark)..controls +(north east:1.3) and +(north west:1.3) .. node[midway,sloped]{$\times$}(Ibarb) ;
  \draw[dashed,-] (Vk)..controls +(north east:1.3) and +(north west:1.3) .. node[midway,sloped]{$\times$}(Vfinb) ;
% \draw[-] (gaiGo)..controls +(south:1) and +(south:1) .. (åpnet) ;

\end{tikzpicture}

\fxnote{TODO: teikne inn f-domene her òg}

\caption{Umogleg lenkjing av underordna c-strukturnodar mellom georgisk og bokmål}
 \label{fig:ikkjesub}
\end{figure}
#+END_LaTeX

Hadde det georgiske treet hatt spesifikator og komplement som kunne
lenkjast til spesifikator og komplement på norsk, kunne me ha lenkja
I' og Vfin. For å tillate desse lenkjene, men ikkje dei i figur
\ref{fig:ikkjesub}, ville det vore nok å krevje at søsternodane var
lenkja. Hadde me hatt situasjon i figur \ref{fig:enkelsub} nedanfor
ville dette stemt, Vfin-nodane kan lenkjast fordi S-nodane er lenkja,
I'-nodane fordi PRONP-nodane er lenkja. 

#+BEGIN_LaTeX
    \begin{figure}[htp]
    \centering
    \begin{tikzpicture}
      \Tree
      [.\node(IPk){IPfoc};
         [.\node(NPk){PRONP}; \edge[roof]; {...} ] 
         [.\node(Ibark){I'};  [.\node(Vfink){Vfin}; {...}  ]
                                     [.\node(Sk){S}; \edge[roof]; {...} ]
         ]
      ]
  \begin{scope}[shift={(2in,0in)}]
    \Tree [.\node(IPb){IP}; 
      [.\node(PRONPb){PRONP}; \edge[roof]; {det} ] 
      [.\node(Ibarb){I'};  [. \node(Vfinb){Vfin}; \node(åpnet){åpnet};  ]
           [.\node(Sb){S}; \edge[roof]; {seg} ] ] ]
  \end{scope}
     \draw[-] (IPk)..controls +(north:1) and +(north:1) .. (IPb) ;
      \draw[-,very thick] (Vfink)..controls +(north east:1.5) and +(north west:1.5) .. (Vfinb) ;
      \draw[-,very thick] (Ibark)..controls +(north east:1.5) and +(north west:1.5) .. (Ibarb) ;
    % \draw[-] (gaiGo)..controls +(south:1) and +(south:1) .. (åpnet) ;
     \draw[-] (NPk)..controls +(north east:1) and +(north west:1) .. (PRONPb) ;
     \draw[-] (Sk)..controls +(north east:1) and +(north west:1) .. (Sb) ;    
    \end{tikzpicture}
    
    \fxnote{TODO: teikne inn f-domene her òg}
    
    \caption{Ei enkel lenkjing av c-strukturnodar}
     \label{fig:enkelsub}
    \end{figure}
#+END_LaTeX


Men det blir for strengt å krevje at søsternodar er lenkja; S-noden i
den norske analysen er ein del av det funksjonelle domenet til IP,
medan komplementet i andre språk kanskje går rett på eit nytt
funksjonelt domene. Figur \ref{fig:enkelsub2} demonstrerer denne
situasjonen. Her kan ikkje S lenkjast til PRONrfl sidan dei ikkje er i
same funksjonelle domene, men me vil jo likevel lenkje Vfin-nodane. 

#+BEGIN_LaTeX
    \begin{figure}[htp]
    \centering
    \begin{tikzpicture}
      \Tree
      [.\node(IPk){IPfoc};
         [.\node(NPk){PRONP}; \edge[roof]; {...} ] 
         [.\node(Ibark){I'};  [.\node(Vfink){Vfin}; {...}  ]
                                     [.\node(PRONrflk){PRONrfl}; \edge[roof]; {...} ]
         ]
      ]
  \begin{scope}[shift={(2in,0in)}]
    \Tree [.\node(IPb){IP}; 
      [.\node(PRONPb){PRONP}; \edge[roof]; {det} ] 
      [.\node(Ibarb){I'};  [. \node(Vfinb){Vfin}; \node(åpnet){åpnet};  ]
           [.\node(Sb){S}; [.\node(PRONrflb){PRONrfl}; {seg} ] ] ] ]
  \end{scope}
     \draw[-] (IPk)..controls +(north:1) and +(north:1) .. (IPb) ;
      \draw[-,very thick] (Vfink)..controls +(north east:1.5) and +(north west:1.5) .. (Vfinb) ;
      \draw[-,very thick] (Ibark)..controls +(north east:1.5) and +(north west:1.5) .. (Ibarb) ;
    % \draw[-] (gaiGo)..controls +(south:1) and +(south:1) .. (åpnet) ;
     \draw[-] (NPk)..controls +(north east:1) and +(north west:1) .. (PRONPb) ;
     \draw[-] (PRONrflk)..controls +(north east:1) and +(north west:1) .. (PRONrflb) ;    
    \end{tikzpicture}
    
    \fxnote{TODO: teikne inn f-domene her òg}
    
    \caption{Her vil me lenkje Vfin-nodane utan å lenkje søstrene deira.}
     \label{fig:enkelsub2}
    \end{figure}
#+END_LaTeX

Me treng altså eit litt meir nyansert
krav. \citet[s.~77]{dyvik2009lmp} definerer i denne samanhengen
omgrepet /lenkja leksikalske nodar/, $LL$, kor $LL(n)$ er mengda av
nodar dominert av $n$ som har ei ordlenkje. For å lenkje
c-strukturnodane $n_s$ og $n_t$, som er i lenkja funksjonelle domene,
må alle nodane i mengda $LL(n_s)$ vere lenkja til nodar i
$LL(n_t)$. Ulenkja nodar under $n_s$ og $n_t$ står ikkje i vegen for
lenkjing av $n_s$ og $n_t$, men dei to mengdene kan ikkje vere tomme.
For at me skal unngå å lenkje I' og Vfin i figur \ref{fig:ikkjesub} må
altså /det/ og /seg/ òg vere ordlenkja til /gaiGo/. Dette blir ei
ein-til-mange-lenkje på ordnivå, som må representerast som fleire
lenkjer som alle byrjar i /gaiGo/. Viss georgisk er kjeldespråket
($n_s$, norsk: $n_t$) blir
$LL(IP_s)=LL(I'_s)=LL(V_s)=\{(\text{det},\text{gaiGo}),(\text{åpnet},\text{gaiGo}),(\text{seg},\text{gaiGo})\}=LL(IP_t)$.
Mengdene
$LL(I'_t)=\{(\text{åpnet},\text{gaiGo}),(\text{det},\text{gaiGo})\}$
og $LL(Vfin_t)=\{(\text{åpnet},\text{gaiGo})\}$ på den norske sida har
ikkje korresponderande mengder på georgisk og blir ikkje lenkja[fn:4].

Men viss me vil unngå å referere til ordlenkjer, går det au an å
definere kravet i form av f-strukturlenkjer på preterminale
nodar[fn:22]:

\ex. \label{subnodekrav-infotap} For å lenkje dei underordna
     c-strukturnodane $n_s$ og $n_t$ (kor toppnodane i dei
     funksjonelle domena er lenkja ved
     krav \ref{f-links-domain}):\\
     La $L_c(n_s)$ vere alle
     f-strukturlenkjer frå $\phi(n'_s)$ for alle preterminale $n'_s$
     som er dominert av $n_s$. Ulenkja nodar $n'_s$ er ikkje med i $L_c$.
     Nodane $n_s$ og $n_t$ kan då lenkjast viss
\a.  mor av $n_s$, $m_s$, har same funksjonelle domene som $n_s$,
     og mor av $n_t$, $m_t$, har same funksjonelle domene som $n_t$, 
\b.  $m_s$ og $m_t$ er lenkja, 
\c.  og $L_c(m_s)-L_c(n_s)=L_c(m_t)-L_c(n_t)$.


\Last[a og -b] seier til saman det same som
\ref{subnodekrav-innan-domene} og \ref{subnodekrav-f-lenkja}. Det
\Last[c] seier er at me må ha same /informasjonstap/ når me går
nedover i c-strukturtreet.

Figur \ref{fig:enkelsub2} illusterer dette kravet. IPfoc og IP er
toppnodar, lenkja ved krav \ref{f-links-domain}. I'-nodane er i lenkja
funksjonelle domene og har lenkja mødre. I tillegg har dei same
informasjonstap:\\
#+BEGIN_LaTeX
\\$L_c(IPfoc_s)=\{(\textbf{PanJara},\textbf{den}),(\textbf{ga-Geba},\textbf{åpne})\}$,
$L_c(I'_s)=\{(\textbf{ga-Geba},\textbf{åpne})\}$
\\$L_c(IP_t)=\{(\textbf{PanJara},\textbf{den}),(\textbf{ga-Geba},\textbf{åpne}),(\textbf{pro},\textbf{pro})\}$,
$L_c(I'_t)=\{(\textbf{ga-Geba},\textbf{åpne}),(\textbf{pro},\textbf{pro})\}$
\\$L_c(IPfoc_s)-L_c(I'_s)=\{(\textbf{PanJara},\textbf{den})\}=L_c(IP_t)-L_c(I'_t)$\\
#+END_LaTeX

#+BEGIN_LaTeX
\begin{figure}[htp]
\centering
\begin{tikzpicture}
\Tree [.\node(IPk){IPfoc}; 
  [.\node(NPk){NP}; \edge[roof]; {PanJara} ] 
  [.\node(Ibark){I'};  [.\node(Vfink){Vfin};    \node(gaiGo){gaiGo};  ]
  ] ]
     \begin{scope}[shift={(2in,0in)}]
\Tree [.\node(IPb){IP}; 
  [.\node(PRONPb){PRONP}; \edge[roof]; {det} ] 
  [.\node(Ibarb){I'};  [. \node(Vfinb){Vfin}; \node(åpnet){åpnet};  ]
       [.S \edge[roof]; {seg} ] ] ]
\end{scope}
 \draw[-] (IPk)..controls +(north:1) and +(north:1) .. (IPb) ;
  \draw[dashed,-] (Vfink)..controls +(north east:1) and +(north west:1) .. node[midway,sloped]{$\times$}(Vfinb) ;
  \draw[-,very thick] (Ibark)..controls +(north east:1.5) and +(north west:1.5) .. (Ibarb) ;
% \draw[-] (gaiGo)..controls +(south:1) and +(south:1) .. (åpnet) ;
 \draw[-] (NPk)..controls +(north east:1) and +(north west:1) .. (PRONPb) ;

\end{tikzpicture}

\fxnote{TODO: teikne inn f-domene her òg}

\caption{Delvis mogleg lenkjing av underordna c-strukturnodar mellom georgisk og bokmål}
 \label{fig:ikkjesub2}
\end{figure}
#+END_LaTeX
 
Vfin-nodane er au i same funksjonelle domene, og har lenkja mødre, men
her har dei ulikt informasjonstap:\\
#+BEGIN_LaTeX
\\$L_c(I'_s)=\{(\textbf{ga-Geba},\textbf{åpne})\}$,
$L_c(Vfin_s)=\{(\textbf{ga-Geba},\textbf{åpne})\}$
\\$L_c(I'_t)=\{(\textbf{ga-Geba},\textbf{åpne}),(\textbf{pro},\textbf{pro})\}$,
$L_c(Vfin_t)=\{(\textbf{ga-Geba},\textbf{åpne})\}$
\\$L_c(I'_s)-L_c(Vfin_s)=\{\}$
\\$L_c(I'_t)-L_c(Vfin_t)=\{(\textbf{pro},\textbf{pro})\}$\\
#+END_LaTeX

Me ikkje har altså ein c-strukturnode som direkte projiserer
f-strukturen til /pro/ på georgisk, lenkja til /seg/ på norsk;
f-strukturen til /pro/ er spesifisert via verbet. Men sjølv om me
ikkje kan sjå ein slik node, kan me sjå at det er /noko/ som er
spesifisert via dette fragmentet av den georgiske c-strukturen, og at
det er lenkja til /seg/, difor mister me informasjon når me går frå I'
til Vfin.

*** Alternativ formulering, utan å sjekke informasjonstap
F-strukturen til /gaiGo/ i dømet over har pro-elementet (lenkja til
/seg/) som argument, difor burde det au vere mogleg å finne
f-strukturlenkja til dette argumentet når ein finn $L_c(I'_s)$. Om ein
legg til denne lenkja i $L_c$, er det nok at $L_c(n_s)=L_c(n_t)$ for
at $n_s$ og $n_t$ skal lenkjast (dvs. ein treng ikkje sjekke
forskjellen til mornodane). Men skal ein formulere eit slikt krav må
ein passe på å spesifisere kor djupt ned i f-strukturen ein skal
kikke, og avgjere om adjunkt-lenkjer skal med, osb. I implementasjonen
min har eg valt å følgje krav \ref{subnodekrav-infotap} for å unngå å
måtte kode denne typen informasjon inn i systemet.

** Funksjonelle c-strukturnodar
\label{SEC:fnord}

Ikkje alle ord tilsvarer PRED-element i f-strukturen, dette gjeld
typisk funksjonsord (t.d. /som/, /at/). Ved endosentrisitetsprinsippa
til \citet{bresnan2001lfs} er komplementet til funksjonelle kategoriar
(C, I, P) ein funksjonell ko-kjerne, det er altså komplementet som gir
PRED-elementet i dette funksjonelle domenet.

Problemet med å nytte metoden frå del \ref{SEC:subnode} i dette
tilfellet er at nodar over funksjonsord er i det same funksjonelle
domenet som komplementet, og nodane over funksjonsorda tilføyer ikkje
ei ny PRED-lenkje som kan dele opp treet slik me gjorde tidlegare. Så
me må utvide prinsippa for å dele opp c-strukturtreet i buntar med
likt informasjonstap.

Ord som ikkje projiserer PRED-lenkjer kan likevel ha
LPT-korrespondanse og bestå krava på ordnivå, men når me skal lenkje
desse på c-strukturnivå må me sjekke ordkrava direkte (me kan ikkje gå
via nokon f-strukturlenkjing). LPT-kravet gir oss eit utgangspunkt for
lenkjing.

Viss begge språk har funksjonsord, men funksjonsord som ikkje kan
sjåast på som moglege omsetjingar (t.d. /fordi/ og /whether/), bør me
ikkje ein gong lenkje komplementa[fn:10]. Samtidig vil me ikkje at eit
manglande funksjonsord på det eine språket skal hindre lenkjing av
komplementa, sidan det kan hende at funksjonsordet ikkje er krevd på
det språket (eventuelt kjem dette fram som korrespondansar i
f-strukturtrekk, eg har ikkje teke høgd for korrespondansar mellom
element som ikkje er PRED i denne oppgåva).

Me krev at komplementa er lenkja for å sikre at me ikkje lenkjer nodar
som står i ulike konstekstar (me vil ikkje lenkje /at/ i «han såg at
det gjekk bra» med /that/ i «he saw that she drew a picture»), jamfør
kravet om lenkja argument for lenkja predikat i del
\ref{SEC:lik-argstr}.

Då får me følgjande:

\ex. \label{fnordkrav} Krav for lenkjing av funksjonelle kategoriar i c-strukturen:
\a. Gitt ei mogleg lenkjing av FP og GP, kor F og G er funksjonelle
    kategoriar der komplementa elles kan lenkjast, introduserer me eit
    «falskt informasjonstap» mellom FP og F' og mellom GP og G'; orda
    under F' og G' må ha LPT-korrespondanse for at FP og GP skal kunne
    lenkjast, då kan me au lenkje F' og G'.  
\b. Gitt ei mogleg lenkjing av FP og XP, der F er ein funksjonell
    kategori, medan X er ein ikkje-funksjonell kategori, ignorerer me
    den funksjonelle kategorien i c-strukturlenkjinga. Sidan det ikkje
    er noko forskjell i informasjonstap mellom FP og F', er F' medlem
    av nodemengden som blir lenkja til XP.

# \ex. \label{fnordkrav} Skal nodar over ord som ikkje projiserer
#      PRED-element lenkjast, må følgjande krav vere oppfylt:
# \a. dei funksjonelle domena (gitt ved komplementa) må vere
#   lenkja, og
# \b. nodane er begge c-strukturhovud.

Om \Last[a] er oppfylt, kan me få samanstillinga vist i figur
\ref{fig:fnord}. Her vil dei funksjonelle domena til CPsub og CPnom
kvar kunne delast opp i to deler, kor den funksjonelle delen har
LPT-korrespondanse medan komplementa er lenkja på f-strukturnivå. Det
er ingen informasjonstap frå CPsub til Csub som ikkje er reflektert i
CPnom til Cnom, og det er ingen informasjonstap frå CPsub til IP som
ikkje er reflektert i CPnom til Ssub.

(Alle nodane under S vist i dei to trea er i same funksjonelle domene,
så om dei funksjonelle domena er lenkja, vil
krav~\ref{subnodekrav-innan-domene} og krav~\ref{subnodekrav-f-lenkja}
vere oppfylt kva gjeld CP-komplementa -- lenkjinga går ikkje ut over
dei funksjonelle domena, medan krav~\ref{subnodekrav-infotap} er
dekkja for IP og Ssub med unntaket over.)

#+BEGIN_LaTeX
  \begin{figure}[htp]
   \centering
  
  \begin{tikzpicture}
  \Tree
  [.IPfoc
    [.PROPP [.PROP abramsma ] ] 
    [.I' [.I \edge[roof]; {iCoda} ]
             [.S [.\node(CPsub){CPsub};
                  [.\node(Csub){Csub};  rom ]
                  [.\node(IP){IP}; \edge[roof]; {cvimda} ]]]]]
      \begin{scope}[shift={(2in,0in)}]
  \Tree
  [.IP
    [.PROPP [.PROP Abrams ] ]
     [.I' [.Vfin visste ]
              [.S [.VPmain [.\node(CPnom){CPnom};
                           [.\node(Cnom){Cnom};  at ] 
                            [.\node(Ssub){Ssub}; \edge[roof]; {det regnet} ]]]]] ]
  \end{scope}                      
  \draw[-] (CPsub)..controls +(1,6) and +(north east:6) .. (CPnom) ;
  \draw[-] (IP)..controls +(north east:1.5) and +(west:0.5) .. (Ssub) ;
  \draw[-,very thick] (Csub)..controls +(south west:3) and +(south west:1) .. (Cnom) ;
  \end{tikzpicture}
  \caption{Mogleg samanstilling av funksjonelle c-strukturnodar mellom georgisk og norsk (bokmål)}
   \label{fig:fnord}
  \end{figure}
#+END_LaTeX

Der det eine språket har eit funksjonsord og det andre språket ikkje
krever det, bryr me oss ikkje om funksjonsordet. For å sjekke noko
slikt må me som nemnt sjå på andre trekk enn PRED i f-strukturane,
noko som blir utanfor denne oppgåva; men om me hadde sjekka slike
f-strukturkorrespondansar kunne me unngått kravet om
LPT-korrespondanse og i staden nytta informasjon frå f-strukturane til
lenkjing av funksjonelle kategoriar. Utan å ha slike mekanismar på
plass blir f-strukturlenkjinga avhengig av c-strukturforhold, og i
implementasjonen min har eg difor lagt mindre vekt lenkjing av
funksjonelle kategoriar.

*** TOGROK cvimda<PRO> men regne<>expletive -- lenkje? 		     :ROTETE:
*** TOGROK kva med ekspletivar? ingen PRED men heller ikkje C/F/I    :ROTETE:
Kandidatane på f-strukturnivå må jo inkludere desse au...

** SKRIV Mangel på samsvar i syntaks og semantikk		     :ROTETE:
\cite[s.~5]{kruijffkorbayova2006agc} gir følgjande døme: 
#+BEGIN_LaTeX
\ex.  nikdy nebyl \\
      never was.not\\
      `has never been'
#+END_LaTeX

/nebyl/ blir «svakt» samanstilt med /never/, men «sterkt» samanstilt med
\emph{has ... been} i deira system. I tillegg er det ein sterk samanstilling
mellom /never/ og /nikby/.

# Og i kvantitetsfrasar er talet det semantiske hovudet på tsjekkisk,
# medan einingen er det på engelsk (her følgjer dei semantikken i
# samanstilling).

** TOGROK Diskontinuerlege einingar				     :ROTETE:
   - diskontinuerlege einingar \cite[s.~4]{cheung2002scg} [[http://scholar.google.no/scholar.bib%3Fhl%3Dno&lr%3D&ie%3DUTF-8&q%3Dinfo:Qh_MRSftNZgJ:scholar.google.com/&output%3Dcitation&oe%3DMACINTOSH&oi%3Dcitation][@books.google]] -- skal dei eigentleg samanstillast? Kva for problem gir dei i forhold til c-strukturnivåsamanstilling?

bør ikkje finnast på f-nivå, PRED er unikt instansiert; MEN: prøv «jeg
tror på ham» i XLE, ser ut som dei har komplekse predikat :-/
*** TODO døme på diskontinuerlege konstituentar som er lenkja	     :ROTETE:
** TOGROK Er «compounds» frasar?	     :ROTETE:
 \citep[p.~1]{giegerich2006aea}

** TOGROK kva var poenget med dette?				     :ROTETE:
«etter og uten er dei einaste prep som tek setn utan å vere arg»
** ULEST Cyrus, FuSe-prosjektet					     :ROTETE:
\citet{cyrus2004apa}
«Abstract: We report on a recently initiated project which aims at
building a multi-layered parallel treebank of English and
German. Particular attention is devoted to a dedicated
predicate-argument layer which is used for aligning translationally
equivalent sentences of the two languages. We describe both our
conceptual decisions and aspects of their technical realisation. We
discuss some selected problems and conclude with a few remarks on how
this project relates to similar projects in the field.»
** TODO Konstruksjonar og komposisjonell inekvivalens		     :ROTETE:
# eg siterer her alsina frå min eigen artikkel..heller sitere min??
\xbar-teori føreset at det finst éi dotter i kvart ledd som kan
reknast som predikatet for dette leddet. Ei utfordring for
\xbar-baserte teoriar er då handsaming av /komplekse predikat/. Desse
har fleire grammatiske element innanfor same ledd som alle bidrar med
«a non-trivial part of the information of the complex predicate»
\citep{alsina1997cp}. I LFG er det ein føresetnad at me berre har éin
\textsc{pred} ytterst i kvar f-struktur; ulike mekanismar har blitt
føreslått for å handsame dette fenomenet.
# \citep[eg~gir~ein~gjennomgang~i][]{unhammer2008cps}

I omsette tekster kan me få eit analogt problem:

\ex. It can't be done \\
     Det lar seg ikke gjøre

Her vil ytre predikat i f-strukturen på norsk vere
'la<det_1,XCOMP>PRO', kor XCOMP[PRED 'gjøre<NULL,det_1>NULL'].

På engelsk får me 'can<XCOMP,it_2>', kor
XCOMP[PRED 'do<NULL,it_2>']. 

# 'la' er eit 3-plasspredikat, medan 'can' er 2-plass; som strid mot
# kravet nemnd over om like mange argument;
# SEMANTISKE argument! og siter/xref meg på kravet om like mange argument

Skal me lenkje orda /can/ og /la/? På /heile konstruksjonen/ finn me
iallfall eit omsetjingsforhold:
# TODO: presiser/ekpliser analogien mellom CP og
# konstruksjonssamanstilling!

| It can't be done                 | Det lar seg ikke gjøre            |    |
| can't be done                    | lar seg ikke gjøre                |    |
| be done                          | gjøre                             | s? |
| _ can't be VPASS                 | _ lar seg ikke VPASS              | ?? |
| \_$_{1}$ can \_$_{2}$ be VPASS_3 | \_$_{1}$ lar seg \_$_{2}$ VPASS_3 | ?? |

# TODO: skrankebaserte skildringar bør iallfall kunne gi samanstilling
# av deltre; type [ can't [be [ ] ] ] opp mot [ lar [ seg ikke ] ] ,
# kopling opp mot modellteori, Pullum&Scholz.

(kan me få den siste generaliseringa frå trebanken?)


** SKRIV definer sitering frå MRS-suiten			     :ROTETE:
** SKRIV setning 7 i MRS-suiten					     :ROTETE:
# setning 31: her har relativpronomenet (romeli) ingen (anaforisk)
# kopling til hunden... manglar dette?

# eh, betre tittel

# II.bøyingsklasse i aorist-serien har nominativ-subjekt og
# dativ-DO/IO som vanleg, medan
# I.bøyingsklasse-aroist-serie-subjektet står i ergativ, og får
# nominativ-DO og dativ-IO. danajleva må altså vere i
# II.bøyingsklasse, og brouns er indirekte objekt? Applikativ?
  

Ein samanstilling bør i det minste gi følgjande:

# TODO: høgrestill venstre kolonne
| abramsi brouns daenajleva sigaretze, rom cvimda | Abrams veddet en sigarett med Brown på at det regnet |
| abramsi brouns daenajleva sigaretze             | Abrams veddet en sigarett med Brown                  |
| brouns daenajleva sigaretze                     | veddet en sigarett med Brown                         |
| daenajleva sigaretze                            | veddet (en) sigarett (på)                            |
| daenajleva                                      | veddet                                               |
| sigaretze                                       | (en) sigarett (på)                                   |
| rom cvimda                                      | at det regnet                                        |
| cvimda                                          | (det) regnet                                         |
| abramsi                                         | Abrams                                               |
| brouns                                          | Brown                                                |
|                                                 |                                                      |
 
** TOGROK og så finst jo større forskjellar, stilistiske osb...	     :ROTETE:

** TOGROK prosessering, kognitive modellar?			     :ROTETE:
finne empiri frå korleis menneske samanstillar? (dvs., korleis skjer
omsetjing)

- \citet{maier2009sis}, http://linguistlist.org/issues/20/20-1786.html
«cross-linguistic structural phenomena in the language production of
bilinguals in the specific context of translation.»

- http://www.linguistlist.org/pubs/diss/browse-diss-action.cfm?DissID=143

- [[http://books.google.com/books%3Fhl%3Dno&lr%3D&ie%3DUTF-8&id%3DhHFoJguRE4oC&oi%3Dfnd&pg%3DPA141&dq%3Dprocessing%2Btranslation%2Bpsycholinguistic%2Bsyntax&ots%3DNUlz1ebVnE&sig%3DrkMwuX59RoIikvTYGq23HNkYtzc][books.google bialystok????lpb]]: «Translation has been called
  "interlanguage paraphrase"», «a metalinguistic skill». «Paraphrasing
  consists in finding the meaning of two compared sequences and
  showing its equivalence, and this identification constitutes a
  judgment on the sequences»[s.~151]

- [[http://books.google.com/books%3Fhl%3Dno&lr%3D&ie%3DUTF-8&id%3DCZXcTzFLDuwC&oi%3Dfnd&pg%3DPA17&dq%3Dprocessing%2Btranslation%2Bpsycholinguistic%2Bsyntax&ots%3DFUm_X5VCeu&sig%3DNoHLNrNxq7bGNAcsRda8RWNDyOY][books.google house????iic]]: «The process of translation, particularly
  if successful, necessitates a complex text and discourse
  processing. The process of interpretation performed by the
  translator on the source text might lead to a TL text which is more
  redundant than the SL text. This argument may be stated as "the
  explicitation hypothesis", [...] especially marked in the work of
  "non professional" translators» [s.~19--20]

- Hutchinson: «What is a grammatical sentence?» (vanskeleg å unngå
  /talaren/ i akseptabilitetvurderingar); kva _er_ ei frasesamanstilling,
  sånn ute i naturen? 
** TOGROK Retningslinjer for samanstilling			     :ROTETE:
Ved korpusbygging er det vanleg at retningslinjer for samanstilling
blir utvikla /etter kvart som ein finn problem/... (det er vanskeleg å
seie noko /a priori/ om kva for vanskar ein kan finne).


** SKRIV Rangering
(meir om dette i del \ref{SEC:f-rangering})

* Implementasjonen av =lfgalign=
\label{SEC:implementasjon}

For å finne ut av kor godt krava i forrige kapittel fungerer til å
avgrense kva for lenkjer som er moglege, har eg implementert dei etter
beste evne i eit Lisp[fn:16]-program.

\fxnote{intro TODO, kanskje noko om kva eg faktisk har fått ut av
implementasjonen} Ei implementering gjer det svært synleg om det finst
manglar i eit formelt krav, eller om noko ikkje er godt nok
spesifisert.

Programmet \texttt{lfgalign}[fn:2] tek inn LFG-analysane av to
setningar som me av uavhengige grunnar trur er omsetjingar av
kvarandre. LFG-analysane må vere disambiguerte og i Prolog-formatet
frå XLE[fn:5]. Programmet les inn dei to filene og opprettar ein
intern representasjon av LFG-analysen.  \fxnote{treng eg ein eigen del
om LPT i dette kapittelet? Implementasjonen er jo veldig enkel
iallfall.}

Me kan i tillegg gi programmet informasjon om kva for ord-omsetjingar
me ser på som lingvistisk prediktable. Intensjonen er at dette kan
vere informert av omsetjingstabellen frå eit automatisk
ordsamanstillingsprogram, eller av handskrivne omsetjingsordbøker.

Programmet byrjar lenkjinga med f-strukturane. Ei
f-struktur\emph{samanstilling} er ei mengd med /lenkjer/ mellom
individuelle f-strukturar. Resultatet av lenkjinga på dette nivået kan
vere tvitydig: sidan det ofte finst fleire måtar å lenkje argument og
adjunkt på, får me i første omgang mange samanstillingar mellom
kjelde- og mål-f-strukturar.

Difor rangerer me f-struktursamanstillingane, og den beste sender me
vidare til c-struktursamanstillinga. Denne delen av programmet gir ut
éi, utvitydig mengd med mange-til-mange-lenkjer mellom c-strukturane
(her treng me ingen rangering). Nodane i kvar av desse
mange-til-mange-lenkjene definerer no den endelege
frasesamanstillinga.

Nedanfor går eg gjennom detaljane rundt dei relevante delene av
programmet.

** Lenkjer mellom f-strukturar
\label{SEC:impl-f-lenkjing}

Hovudalgoritmen for lenkjing mellom f-strukturar er vist i kodefigur
\ref{algo:f-align}. Funksjonen =f-align= returnerer ei mengd med
moglege samanstillingar. Kvar samanstilling er ei mengd med par av
f-strukturar[fn:18]. Eit par $(F_s,F_t)$ representerer ei lenkje frå
ein f-struktur på kjeldespråket, til ein f-struktur på målspråket. Me
går ut frå at dette paret har LPT-korrespondanse[fn:17], dette blir
sjekka før alle kall på =f-align=. Der me ikkje har informasjon om
LPT-korrespondanse mellom to ord (orda er ukjende), er lenkjing
lov. Pro-element og substantiv kan alltid lenkjast med kvarandre.
\fxnote{TOGROK: kan me i tillegg sjekke om funksjonelle nodar i same
f-domene som PRED-ordformen har LPT-korrespondanse?}

Hjelpefunksjonen =argalign= (som igjen kallar =argalign-p=, vist i
kodefigur \ref{algo:argalign-p}) gir alle moglege
«argumentpermutasjonar», dvs. moglege kombinasjonar av lenkjer mellom
argumenta til $F_s$ og $F_t$ som tilfredsstiller kravet om
LPT-korrespondanse, men utan å sjekke at desse argumenta igjen kan
samanstillast. Funksjonen prøver å lenkje kvart argument til eit
argument eller eit adjunkt, men gir ingen lenkjer mellom to adjunkt
(sjå del \ref{SEC:impl-adjalign} nedanfor om dette). Funksjonen gir
heller ikkje kombinasjonar der minst eitt argument ikkje er lenkja --
alle kombinasjonane må inkludere alle argument frå $F_s$ og $F_t$,
jf. krav (iii) og (iv) i \citet[s.~75]{dyvik2009lmp}. Elles er krav
(i) er tautologisk oppfylt, medan me som nemnt føreset at krav (ii) er
oppfylt før alle kall på =f-align=.

Eit døme: viss $F_s$ har argumenta \SUBJs og \OBJs og ingen adjunkt,
og $F_t$ har argumentet \SUBJs og eitt adjunkt \ADJ, der alle
ord-omsetjingar er moglege, vil =argalign= gi dei to samanstillingane
$\{(\SUBJ,\SUBJ), (\OBJ,\ADJ)\}$ og $\{(\SUBJ,\ADJ),
(\OBJ,\SUBJ)\}$. Viss adjunktet til $F_t$ ikkje fantest, eller ikkje
hadde LPT-korrespondanse med nokon av argumenta til $F_s$, ville me
ikkje fått nokon samanstillingar; medan viss paret $(\SUBJ,\SUBJ)$
ikkje hadde LPT-korrespondanse og alt anna var likt, ville me berre
fått den siste samanstillinga.

Funksjonen =f-align= går så gjennom kvar lenkje i kvar
argumentpermutasjon, og prøver å kalle =f-align= på alle
lenkjene. Sidan lenkjene som =argalign= gir har LPT-korrespondanse,
vil alle f-strukturane i dei rekursive kalla i =f-align= ha
LPT-korrespondanse. Eit rekursivt kall kan gi nye samanstillingar i
dei indre f-strukturane, viss dei relevante krava er oppfylte.

Det er mogleg at ei lenkje frå éi samanstilling kan finnast i andre
samanstillingar, me unngår dobbeltarbeid ved å lagre alle delvise
samanstillingar i tabellen $aligntable$. Dette føreset at
\texttt{f-align}$(s,t)$ er uavhengig av konteksten rundt; t.d. må
mengda av samanstillingar som kjem ved å lenkje subjektet til $F_s$
mot subjektet til $F_t$ vere uavhengig av om objektet til $F_s$ er
lenkja mot eit objekt eller eit adjunkt osb. av $F_t$. \fxnote{TODO:
nemne føresetnaden om uavhengnad i kapittel 3}

#+BEGIN_LaTeX
      \SetKwComment{Comment}{ // }{}
     \SetKwInOut{Input}{usage}
  
     \begin{algorithm}[]
      \caption{f-align($F_s$, $F_t$)}
      \label{algo:f-align}
      
      $alignments \gets \emptyset$  \;
      \ForAll{argperm in argalign($F_s$, $F_t$)} {
        $p \gets \emptyset$ \;
         \ForAll{$A_s$, $A_t$ in argperm} {
           \uIf{not(aligntable[$A_s$,$A_t$])} {
           aligntable[$A_s$,$A_t$] $\gets$ f-align($A_s$, $A_t$)\;
           }
          \uIf{aligntable[$A_s$,$A_t$]}{add aligntable[$A_s$,$A_t$] to $p$\;}
          \uElse{add $(A_s, A_t)$ to $p$}
        }
        add $p$ to $alignments$ \;
        \ForAll{adjperm in adjalign(argperm, $F_s$, $F_t$)} {
          $a \gets$ copy-of($p$) \Comment*[r]{optional adjunct links}
          \ForAll{$A_s$, $A_t$ in adjperm}{
            \uIf{not(aligntable[$A_s$,$A_t$])} {
              aligntable[$A_s$,$A_t$] $\gets$ f-align($A_s$, $A_t$)\;
            }
            \uIf{aligntable[$A_s$,$A_t$]}{add aligntable[$A_s$,$A_t$] to $a$\;}
            \uElse{add $(A_s, A_t)$ to $a$}
          }
          add $a$ to $alignments$ \;
        } % adjperm in adjalign
       } % argperm in argalign
       \Comment{loop through adjalign if no arguments exist}
       \lIf {$alignments=\emptyset$}{ \Return $\emptyset$ \Comment*[l]{Fail} }
       \lElse{ \Return $((F_s, F_t), alignments)$ \; }
       \end{algorithm}    
    
    
      \begin{algorithm}[]
      \caption{argalign-p($args_s$, $adjs_s$, $args_t$, $adjs_t$)}
      \label{algo:argalign-p}
    
      \Input{Kalt av argalign slik: \\ argalign-p(arguments($F_s$),
      adjuncts($F_s$), arguments($F_t$), adjuncts($F_t$))}
      \BlankLine
      
     $a \gets \emptyset$\;
     \uIf{$args_s$} {
           $s \in args_s$\;
           \ForAll{$t \in args_t$ \textbf{where} LPT($s$,$t$)} {
               \lForAll{$p \in$ argalign-p($args_s-\{s\}$, $adjs_s$, $args_t-\{t\}$,$adjs_t$)}{
  add $\{(s,t)\} \bigcup p$ to $a$\;
             }
            }
           \ForAll{$t \in adjs_t$ \textbf{where} LPT($s$,$t$)} {
               \lForAll{$p \in$ argalign-p($args_s-\{s\}$, $adjs_s$, $args_t$,$adjs_t-\{t\}$)}{
  add $\{(s,t)\} \bigcup p$ to $a$\;
                }
           }
             \Return $a$\;
         }
          \uElseIf{$args_t$} {
            \uIf{$adjs_s$}{
                $s \in adjs_s$\;
           \ForAll{$t \in args_t$ \textbf{where} LPT($s$,$t$)} {
               \lForAll{$p \in$ argalign-p($args_s$, $adjs_s-\{s\}$, $args_t-\{t\}$,$adjs_t$)}{
  add $\{(s,t)\} \bigcup p$ to $a$\;
             }
            }
             \Return $a$\;
        }\uElse{
              \Return $\emptyset$  \Comment*[l]{Fail}
            }
          }
        \uElse {
          \Return \{$\emptyset$\} \Comment*[l]{End}
        }     
      \end{algorithm}
#+END_LaTeX

Sjølv om det er krav om LPT-korrespondanse mellom kvart argument og
eit argument/adjunkt for å lenkje $F_s$ og $F_t$, er det ikkje noko
krav om at alle para i ein argumentpermutasjon tilfredsstiller alle
lenkjingskrava. Viss \texttt{f-align}$(\OBJ,\ADJ)$ frå dømet over gir
null, og ikkje kan lenkjast (t.d. fordi \ADJs hadde eitt argument, og
\OBJs ingen argument/adjunkt), medan \texttt{f-align}$(\SUBJ,\SUBJ)$
kan lenkjast, vil =f-align= likevel returnere samanstillinga som
inneheld $(\OBJ,\ADJ)$ og $(\SUBJ,\SUBJ)$. Me kan sjå i $aligntable$
for å finne ut av om kvar av f-strukturane kunne lenkjast; i dette
tilfellet vil $aligntable[\OBJ,\ADJ]$ vere tom.

\fxnote{TODO: forskjellen mellom LPT-krav og rekursjonskrav på argument må
inn i kapittel 3}

Om me i tillegg krev at substrukturar kan samanstillast kan me
utelukke lenkjing av f-strukturane $F_s$ og $F_t$ i \Next under:

#+BEGIN_LaTeX
{\avmoptions{}

\ex. \a.  \begin{avm}  \sort{$F_s$}{\[ {\sc pred} `{\bf planlegge}<{\it eg},[1:{\it gi}]>'\\
  {\sc xcomp} \sort{$^{1}$}{\[ {\sc pred} `{\it gi (opp)}'\]} \]}  \end{avm}
  \b.\begin{avm} \sort{$F_t$}{\[ {\sc pred} `{\bf plan}<{\it I},[2:{\it give}]>'\\
  {\sc xcomp} \sort{$^{2}$}{\[ {\sc pred} {\bf give}<{\it I},{\it him},{\it it}>' \]} \]} \end{avm}

}
#+END_LaTeX

Men det kan vere at me ikkje /vil/ krevje dette i alle moglege
tilfelle. Ei tryggare løysing er å rangere ulike løysingar i
etterkant, ved å spørje etter dei argumentsamanstillingane som har
flest medlem i $aligntable$, dette kjem eg tilbake til i
\ref{SEC:f-rangering} nedanfor.
*** Overflødige adverbial
   \label{SEC:impl-adjalign}

Argumentpermutasjonane frå =argalign= prøver som nemnt ikkje reine
adjunkt-adjunkt-lenkjer, sidan me ikkje vil forkaste lenkjing av $F_s$
og $F_t$ berre på grunn av at ikkje alle adjunkt kunne lenkjast. Men
når me har prøvd ein argumentpermutasjon, kan me lage ein kopi av
denne som i tillegg inneheld lenkjer mellom «overflødige» adverbial,
altså dei adjunkt-adjunkt-lenkjene som =argalign= ikkje
prøver. Hjelpefunksjonen =adjalign= (ikkje vist her
\fxnote[inline,nomargin]{TODO: implementere :->}) konstruerer moglege
permutasjonar av lenkjer mellom adjunkt som ikkje er inkludert i
$argperm$, og =f-align= prøver desse rekursivt på same måte som med
argumentlenkjene. \fxnote{og så er det spørsmålet om me kan lenkje
adjunkt på ulike nivå i f-strukturane} Lenkjene blir lagt til ein
/kopi/ av argumentpermutasjonane, sidan det ikkje er sikkert at me
ønskjer å lenkje alle adjunktdøtre. Viss me har to overflødige adjunkt
på kvar side, og kravet om LPT-korrespondanse er dekkja for alle fire
moglege par, får me seks moglege permutasjonar, sidan me inkluderer
dei fire permutasjonane der eitt adjunktpar er ulenkja.

Viss $F_s$ og $F_t$ ikkje hadde argument i det heile teke, går me au
gjennom moglege permutasjonar av adjunktdøtre, på same måte (ikkje
vist i kodefigur \ref{algo:f-align}).

*** SKRIV Funksjonsord utan LPT-korrespondanse bør eigentleg hindre f-strukturlenkjing
*** SKRIV Når f-lenkjene ikkje er 1-1
\fxnote{Dette må 1. spesifiserast (kap.3), og 2. implementerast...}
**** kausativ
**** preposisjonsobjekt
"sigaretten" og "sigaretze" er ikkje på same nivå i dei respektive
f-strukturane nedanfor:
: 0[ PRED vedde<28,29,27,30>
:    29[ PRED sigarett<> ] ]

: 0[ PRED da-najleveba<37,10,46>
:    ADJUNCT { 2 }
:    2[ ze<5>
:       OBJ 5[ sigareti ] ] ]

Men dette er fordi sigaretze er _adjunkt_, og i følgje fotnote 3 i
\citet{dyvik2009lmp} er P(ADJ) lik den semantiske formen til
_preposisjonsobjektet_ til ADJ. (Er dette heilt enkelt? Kan me ha
adjunkt med fleire «preposisjonsargument»?)

I motsetning til å endre på P(ADJ) slik at pred-verdien til eit
adjunkt hoppar over preposisjonar og inn i preposisjonsobjekt, har eg
i implementasjonen min gjort det slik at funksjonen som henter ut /f-strukturen/ til adjunkt-døtre av ein f-struktur hoppar over
preposisjonsobjekt (m.a. fordi ved eit kall P(X) kan ikkje P vite om X
er eit adjunkt eller argument).

Sjå au del \ref{SEC:merge-daughters}.

**** notat 							     :ROTETE:
filene 
: ((tab_s (open-and-import "dev/TEST_argadj_s.pl"))
:  (tab_t (open-and-import "dev/TEST_argadj_t.pl")))
viser at me kan trenge samanføying av pred på ulike nivå.
*** Kan me gjere f-struktursamanstillinga bottom-up?
#+BEGIN_LaTeX
  %     \begin{quotation}
  %    Any sufficiently complex problem needs to be coded three times.\\
  % \begin{minipage}{0.8\textwidth}
  % \begin{flushright}
  %        (ukjend, via Steve Gibson)
  % \end{flushright}
  % \end{minipage}
  %    \end{quotation}
#+END_LaTeX
Ein alternativ metode for lenkjing av f-strukturane er å byrje med
alle logisk moglege permutasjonar av LPT-korrespondansar, og så sile
ut dei som ikkje svarer til krava. Prosessen ville nok blitt mykje
meir oversiktleg på denne måten, sidan det då berre er snakk om å
sjekke krav for kvar enkelt lenkje.  Men ein slik metode er vanskeleg
i praksis; når avskjeringa skjer så seint, blir det alt for mange
moglege kombinasjonar for lengre setningar med mange ukjende ord til
at ein vanleg datamaskin kan halde styr på dei.

Me må i alle tilfelle vere klar for ei setning der alle ord er ukjende
(me har ingen informasjon om LPT-korrespondanse), slik at kvart
kjeldeord kan lenkjast til kvart målord. Viss begge setningane er 4 ord,
får me 16 moglege samanstillingar der alle ord er med i nøyaktig éi
lenkje ($2^l$, kor $l$ er setningslengd). Men ofte har me
null-lenkjer, me må altså i tillegg tillate samanstillingar der minst
eitt ord er ulenkja, utan at me treng å vite kva for ord det er; med
desse kortare listene inkludert får me endå fleire moglege
samanstillingar per setning (4 ord gir 26, 8 ord gir 2186 moglege
samanstillingar). Sjølv om me heile tida vel dei samanstillingane som
lenkjar flest ord, ville maskinen raskt fått problem. I tillegg har me
problemet med 1-mange-lenkjer, som skaper endå fleire moglege
samanstillingar.

Ein sideverknad av å byrje med ytre lenkjer og gå innover (prosessen
skildra i del \ref{SEC:impl-f-lenkjing}) er at me automatisk unngår å
prøve «kryssande» lenkjer, t.d. å lenkje $F_s$ med \XCOMPs av $F_t$, og
\XCOMPs av $F_s$ med $F_t$ (denne kombinasjonen av lenkjer vil jo vere
ein del av alle logisk moglege permutasjonar). Me får au prioritert å
lenkje ytre element, som jo er sikrare lenkjer: gitt to f-strukturar
for setningar der alt me veit om lenkjinga er at /setningane/ er
omsetjingar av kvarandre, vil dei to ytre f-strukturane ha størst
sjanse for å korrespondere med kvarandre. For kvart steg du går
innover må du multiplisere inn sjansen for å trå feil i
argumentpermutasjonane.

** SKRIV Rangering
\label{SEC:f-rangering}

\fxnote[inline,nomargin]{Rangering er ikkje implementert enno (akkurat no gir
rank(f-alignments) berre ut første samanstilling.)}
Rangering foregår etter ulike kriterium. Her er eit par forslag:
*** rekursivt lenkja > ulenkja, men LPT
    $aligntable$ seier om noko er rekursivt lenkja eller ikkje,
    plusspoeng viss me har klart å lenkje rekursivt.
*** argument-argument > argument-adjunkt
    Plusspoeng for argument-argument-lenkjer, burde vere eit bra
    kriterium, men me får sjølvsagt problem viss LPT ikkje seier noko
    i døme \ref{vedde} med \\
    =da-najleveba<Abrams,Browne,regne>= adjunkt: =sigarett=\\
    =bet<Abrams,sigarett,regne>= adjunkt: =Browne=
    
*** arg1-arg1 arg2-arg2 > arg1-arg2 arg2-arg1 (følgje)
    Dette kjem til å gi problem når me vil lenkje «behage» og «like»,
    viss me ikkje har motstridande LPT-informasjon (og argumentfølgje
    i leksikon ikkje er basert på semantikk, men syntaks). Men elles
    er det vel OK.

    Enklaste implementasjon: Levenshtein-avstand. Men burde visse
    argument vektast? (T.d. vekte subjekt om alt anna er likt.)

    Andre forslag: http://en.wikipedia.org/wiki/Edit_distance)
*** flest lenkja adjunkt
    Usikker på dette... avheng av om me tillèt lenkjer på tvers av
    f-strukturar.
*** Prioritet på rangeringskriterium
    Dette bør sjølvsagt testast empirisk, blir kanskje utanfor denne
    oppgåva (diskusjonsdel?), men kan jo prøve meg litt rundt.
** Lenkjing av c-strukturnodar
Samanstilling mellom f-strukturar treng i =lfgalign= ikkje informasjon
om c-strukturen, medan lenkjing av c-strukturnodar skjer på grunnlag
av f-struktursamanstillinga. Programmet utfører difor samanstilling av
c-strukturar sist[fn:8].

Funksjonen =c-align= har som inndata c-strukturanalysane av kjelde- og
målsetninga, og éi f-struktursamanstilling; utdata er ei mengd med
lenkjer. Ei lenkje er eit par der første element er ei mengd
c-strukturnodar på kjeldespråket, og andre element ei mengd nodar på
målspråket. Det er ingen overlapp mellom medlem av lenkjer (ein node
er aldri med i meir enn eitt par).

I \citet[s.~77]{dyvik2009lmp} er kravet for å lenkje to
c-strukturnodar er at dei dominerer same mengd med
ordlenkjer[fn:20]. Ein node /n/ dominerer ei mengd lenkjer /l/ viss
unionen av lenkjene dominert av døtrene til /n/ er lik /l/. I
=lfgalign= opererer eg ikkje med /ordlenkjer/ i seg sjølv;
f-struktursamanstillinga er basert på LPT-korrespondansar, som
definerer moglege ordlenkjer utan å sjå på kontekst, og
f-struktursamanstillinga avgrenser vidare moglege ordlenkjer gitt
f-strukturinformasjon. Preterminale nodar er dei mest ordnære nodane
som kan ha ei f-strukturlenkje (ved $\phi$); når formålet er å lenkje
c-strukturnodar kan me nytte f-strukturlenkja til den preterminale
noden i staden for ordlenkjer.  \fxnote[inline,nomargin]{To problem (kva vil me ha
med?)\\
1. me får \emph{ikkje} med LPT-korrespondansar som er OK, men
ikkje med i $f-alignment$;\\
2. me \emph{får} med LPT-korrespondansar
som er med i $f-alignment$ men ikkje $aligntable$ (ikkje er rekursivt
lenkja).}

#+BEGIN_LaTeX
  \fxnote{TODO: gammal implementasjon, er ganske annleis no.}
   \begin{algorithm}[]
     \caption{c-align(f-alignment, $tree_s$, $tree_t$)}
     \label{algo:c-align}
      
     c-alignments $\gets \emptyset$ \;
     $splits_s \gets$ new table \;
     add-links(f-alignment, $tree_s, splits_s)$  \;
     $splits_t \gets$ new table \;
     add-links(f-alignment, $tree_t, splits_t)$  \;
     \ForAll{$src$, $trg$ in f-alignment} {
       $top_s \gets$ topnode($src$) \;
       $top_t \gets$ topnode($trg$) \;
       add $(top_s,top_t)$ to c-alignments \;
       \ForAll{$f-link$ in keys of $splits_s$} {
         \uIf{$f-link$ in keys of $splits_t$ and $f-link \neq (src,trg)$} {
           $links_s \gets$ keys of $splits_s$ where $src$ is a value, minus $f-link$ \;
           $links_t \gets$ keys of $splits_t$ where $trg$ is a value, minus $f-link$ \;
           $nodes_s \gets splits_s[links_s]$ \;
           $nodes_t \gets splits_t[links_t]$ \;
           \uIf{$nodes_s$ and $nodes_t$ are non-empty} {
             add $(nodes_s,nodes_t)$ to c-alignments \;
           }
         }
        }
      }
      \Return c-alignments \;
      \end{algorithm}    
#+END_LaTeX      

Hjelpeprosedyren =add-links= utfører hovudjobben. Inndata er rotnoden
til c-strukturtreet for eitt av språka, og
f-samanstillinga. Prosedyren kappar opp treet i nodemengder, kor kvar
nodemengd dominerer same lenkjemengd (som definert over).
Nodemengdene blir lagra i ein tabell, indeksert på
lenkjemengdene. Prosedyren går rekursivt gjennom treet frå rot til
lauv; lenkjemengden for kvar node er unionen av lenkjemengdene
returnert av =add-links= kalt på kvar av døtrene. Viss ein node
dominerer ei lenkjemengd $links$, legg me til denne noden i tabellen
$splits[links]$. 

#+BEGIN_LaTeX
   \begin{algorithm}[]
   \caption{add-links(f-alignment, $node, splits$)}
   \label{algo:add-links}
      
        $links \gets \emptyset$\;
   \uIf{$node$} {
       \uIf{preterminal?($node$)} {
          let $link \in$ f-alignment s.t. $\phi(node) \in link$ \;
          \lIf{$link$} {$links \gets \{link\}$}
        }
        \uElse {
          $links \gets $add-links(f-alignment, left-branch($node$)) $\bigcup$ add-links(f-alignment, right-branch($node$)) \;
        }
        add $node$ to $splits[links]$ \;
       }
        \Return $links$ \;
  \end{algorithm}
#+END_LaTeX

Sidan =c-align= kallar =add-links= for kvar av sidene, får me to
tabellar $splits_s$ og $splits_t$. Me hentar så ut alle dei
lenkjemengdene som er i begge tabellane (dvs. snittet av oppslagsnøklene
til tabellen); nodane som er lagra med mengd med f-strukturlenkjer
skal lenkjast på c-strukturnivå. Alle desse mange-til-mange-lenkjene
blir til slutt returnert av =c-align=.

Prosessen er no ferdig, mange-til-mange-lenkjene mellom
c-strukturnodar definerer frasesamanstillinga

\fxnote[inline,nomargin]{til
diskusjonsdel:\emph{Det er ikkje berre ei N-gramsamanstilling; sidan
lenkjene er mellom c-strukturnodar kor kvar node dominerer ein
konstituent, kunne me kalt det ei} konstituentsamanstilling.}.


*** SKRIV viss me har LPT, men ikkje rekursiv f-lenkje
    Dette bør kanskje vere valfritt i programmet, for å sjå kva det
    fører til: vil du ta med LPT-korrespondansar som ikkje har
    f-lenkjer i =add-links=?

    Og omvendt, finst det LPT-korrespondansar som ikkje kjem med i
    f-alignment i det heile teke, men som likevel burde ha noko å seie
    for c-strukturlenkjinga? (Men burde dei ikkje då vere med i
    f-alignment au?)

\fxnote{Kan me \textbf{fjerne} visse f-samanstillingar pga. c-strukturinfo?
    dvs. disambiguere...
    (dette er vel heller stoff for diskusjonsdelen?)}


* Diskusjon, resultat av å automatisk samanstille norske og georgiske setningar :ROTETE:
\label{SEC:diskusjon}

   - om kjeldematerialet
   - manglar med implementasjonen
   - samanlikning av lenkjing basert på f-struktur og lenkjing basert
     på N-gram
   - bruksområde for samanstillingar

** Oppdage argumentstrukturalternasjon
\fixme{ref} I døme TODO i kapittel TODO viste eg at f-strukturar og
LPT-korrespondanse kanskje ikkje har nok informasjon til å kunne
handtere ulik følgje i argumentstruktur. Programmet mitt vil her gi
begge løysingar, ei rangering basert på lik argumentfølgje vil gi feil
løysing på topp.

Kanskje kan me nytte data frå fleire førekomstar med andre subjekt og
objekt til å lære slike argumentstrukturalternasjonar.  Om me
observerer /sie gefällt mir/jeg liker henne/ vil me jo ha
f-strukturinformasjon som kan nyttast til å informere
argumentstrukturalternasjon (/sie/henne/ er hokjønn, etc.), om det var
substantiv der ville LPT-korrespondanse kunne informere dette.
** Samanlikning med tremetodar og n-grammetodar
I tillegg til at ein kanskje kan få betre skåre på kvantitative mål
som presisjon og gjenkjenning, vil lenkjer mellom f-strukturar gi
informasjon som er kvalitativt forskjellig frå det ein kan få med å
berre sjå på lenkjer mellom ord, n-gram eller konstituentar.

*** c->f er mange-til-ein
Avbildinga frå c-strukturnodar til f-struktur er mange-til-ein, kan me
t.d. innanfor eitt tre ha fleire N-gram per f-strukturhovud; ein
metode som berre ser på enkle N-gramlenkjer vil ikkje registrere desse
relasjonane (t.d. metoden i \citet{samuelsson2007apa}).
 


*** TOGROK men korleis gjenfinne there is/es gibt? 		     :ROTETE:
1. N-gram kjem like ofte som heile konstruksjonen, då kan dette
   gjenfinnast
   - dvs., /there is NP/es gibt NP/-samanstilling kjem like ofte som
     /there is/ eller /es gibt/ førekjem. Eit TigerXML-type søk etter
     /there is NP/es gibt NP/ burde jo vere mogleg, sjekk om dette er
     delmengd av /there is/es gibt/. * Avslutning


** TOGROK korleis finn me /there is/-lenkjer då?		     :ROTETE:
(og kva skal me med dei?)

«Til gjengjeld vil me få lenkjer sjølv om me har mellomståande ord
(/There/ never /is/) som opptrer utanfor N-grammet på det andre
språket.»




* Avslutning
# tom inndeling for å halde bibliografien sist

\bibliographystyle{apacite}
\bibliography{master}

* Footnotes

[fn:1] Både omsetjingsmodellen og språkmodellane er reint
      N-grambaserte her, og har difor ikkje nytte av syntaktisk
      informasjon (i motsetning til syntaktisk informert generering
      slik \citet{riezler2006gmt} implementerer).

[fn:typetoken] \cite[s.~2]{thunes2003eal}: «Våre prinsipper er satt
       opp for å tjene et bestemt formål, nemlig å samle inn data som
       metoden i Semantic Mirrors skal anvendes på», ein metode for å
       automatisk finne WordNet-liknande relasjonar frå
       parallelltekst. I denne metoden vil det vere naturleg med høge
       krav til presisjon, men kanskje lågare krav til dekning:
       speilmetoden skal finne leksikalske semantiske forhold som held
       på /typenivå/, medan for trebanken er det viktigare korleis me
       kan annotere eit /token/ av t.d. eit verb i ein viss VP i ei
       gitt korpussetning.

[fn:3] \citet[Catford~(1965),~i][s.~61]{munday2001its} gir ein gjennomgang av
       slike /klasseskifte/, og andre typar omsetjingsskifte.

[fn:6] Sidan eg går ut frå at data er setningssamanstilt, kjem eg
       ikkje inn på diskurs-/pragmatiske verknader, med mindre dette
       fører til forskjellar innanfor setningane (sjå t.d. del
       \ref{SEC:ordkrav} om lenkjer mellom koreferente substantiv og
       pronomen).

[fn:9] I tillegg finst andre positive biverknader av ein LFG-basert
       frasesamanstilling for bruk i denne samanhengen, som at ein kan
       studere kor parallelle dei parallelle grammatikkane i
       ParGram-prosjektet \citep{butt2002pgp} faktisk er, på ulike
       nivå (leksikon og argumentstruktur, c-struktur, f-struktur).

[fn:10] Skal ein lenkje ordet /som/ (utan PRED) med ordet /which/ (med
        PRED)? Viss krava elles er oppfylt, kan det kanskje vere
        informativt med ein type «defekt» lenkje, sjølv om berre det
        eine ordet blir rekna for å vere eit innhaldsord. Frasane til
        deira funksjonelle domene vil uansett vere samanstilt via
        toppnodane (t.d. CP).

[fn:12] I del \ref{SEC:fnord} kjem eg tilbake til spørsmålet om me vil
        inkludere visse f-strukturar utan PRED-element i kandidatane
        for samanstilling.

[fn:14] Analysane er henta 18. mai, 2009, frå
        http://decentius.aksis.uib.no/logon/xle.xml, som implementerer
        LFG-grammatikkane frå ParGram-prosjektet \citep{butt2002pgp}.

[fn:15] 25 om ein inkluderer analysar kor minst eitt av argumenta
        ikkje hadde korrekt analyse (t.d. eit \textsc{PRO} der
        grammatikken burde funne eit substantiv).

[fn:2] Tilgjengeleg frå http://github.com/unhammer/lfgalign som fri og
       open programvare under GNU General Public License.

[fn:5] Formatet er dokumentert på
       http://www2.parc.com/isl/groups/nltt/xle/doc/xle.html. Importeringa
       til Lisp-strukturar handterer «pakka representasjonar» og
       kjenner igjen ekvivalensforhold (t.d. der fleire
       $\phi$-variablar refererer til same f-struktur, eller fleire
       Prolog-variabler refererer til same analyseval); men filene eg
       har testa utnyttar ikkje det fulle spennet til formatet, så det
       finst ganske sikkert feil.

[fn:16] Dette språkvalet kan gjere eventuell integrering med andre
        LFG-system lettare (Common Lisp er m.a. nytta i LFG
        Parsebanker \citep{rosen2009lpt}).

[fn:17] Når eg her skriv at to f-strukturar har LPT-korrespondanse,
        meiner eg sjølvsagt at ordformene til PRED-verdien til kvar
        f-struktur har LPT-korrespondanse.

[fn:18] Eigentleg eit slag avgjerdstre; kvart element er eit par, kor
        første element er lenkja mellom dei yttarste f-strukturane, og
        andre element er dei moglege samanstillingane for dei indre
        strukturane. Denne strukturen kan vere nyttig for å rangere
        samanstillingar, og =f-align= blir mykje meir oversiktleg av å
        jobbe med eit slikt tre. Ein funksjon =flatten= omformar det
        ferdige treet til ei enkel liste med samanstillingar, kor kvar
        samanstilling er ei flat liste med lenkjer mellom
        f-strukturar.

[fn:19] Ved c-struktur-f-strukturavbildinga $\phi$, ein funksjon som
        tek ein c-strukturnode og returnerer ein (delvis) f-struktur.

[fn:20] Dette er ein litt enklare måte å definere kravet på; ei
        /lenkje/ refererer til både kjelde og mål, dimed blir det
        mogleg å seie at ein node på kjeldespråket kan dominere same
        mengd som ein node på målspråket.

[fn:11] LFG tillèt som nemnt diskontinuerlege konstituentar, men dette
        er ikkje det same som ikkje-konstituentar av typen «es gibt» /
        «there is».

[fn:7] Eventuelt kunne me ha definert lenkjingskandidatane på
       f-strukturnivå som alle PRED-haldande f-strukturar, resultatet
       blir det same.

[fn:21] Eigentleg burde slike setningar ikkje vere lenkja på
        setningsnivå ein gong, men som me skal sjå i del
        \ref{SEC:lik-argstr} treng me kravet om lik tyding 
        sjølv innanfor setninga.

[fn:13] Me ville au fått ei mange-til-ein-lenkje om me tillot
        /komplekse predikat/ i analysane, t.d. slik
        \citet{butt1998merger} foreslår ved å la kombinasjonen av to
        ord endre argumentstrukturen til eitt PRED-element.

[fn:4] Eg har ikkje gjort noko forskjell på nodar som dominerer like
       mengder på same språk, dette kan tolkast som at alle dei
       ikkje-terminale nodane på georgisk er lenkja til IP på norsk.

[fn:22] Då kan me au representere mange-til-mange-ordlenkjer som
        «udelelege», $(\{\text{gaiGo}\},\{\text{det,åpnet,seg}\})$
        blir den einaste ordlenkja i dømet over, sidan me ikkje må
        samanlikne ordlenkjene frå $IP_t$, $I'_t$ og $Vfin_t$.

[fn:8] Som nemnt i del \ref{SEC:fnord} kan funksjonsord gjere
       f-strukturlenkjinga avhengig av forhold i c-strukturen,
       evt. krevje meir nyansert f-strukturlenkjing; dette har eg teke
       høgd for i implementasjonen.

