#+TITLE: Syntaktisk informert frasesamanstilling 
#+SEQ_TODO: ULEST SKRIV FERDIG
#+SEQ_TODO: TOGROK TODO DONE
#+TAGS: SPML(s) NORGLISH(n) ROTETE(r)
#+STARTUP: hidestars
#+AUTHOR: Kevin Brubeck Unhammer
#+EMAIL: Kevin.Unhammer hos student uib no
#+LANGUAGE: nn
#+OPTIONS: H:4 toc:t f:t skip:nil num:t
#+LaTeX_CLASS: masterdraft
#+LaTeX_HEADER: \newcommand{\xbar}{$\rm\overline{X}$}
#+LaTeX_HEADER: \newcommand{\F}[2]{\textsc{#1}\ensuremath{_{#2}}}
#+LaTeX_HEADER: \newcommand{\OBLben}{\F{obl}{ben}}
#+LaTeX_HEADER: \newcommand{\OBJben}{\F{obj}{ben}}
#+LaTeX_HEADER: \newcommand{\OBJ}{\F{obj}{}}
#+LaTeX_HEADER: \newcommand{\OBJs}{\F{obj~}{}}
#+LaTeX_HEADER: \newcommand{\ADJ}{\F{adj}{}}
#+LaTeX_HEADER: \newcommand{\ADJs}{\F{adj~}{}}
#+LaTeX_HEADER: \newcommand{\XCOMP}{\F{xcomp}{}}
#+LaTeX_HEADER: \newcommand{\XCOMPs}{\F{xcomp~}{}}
#+LaTeX_HEADER: \newcommand{\SUBJ}{\F{subj}{}}
#+LaTeX_HEADER: \newcommand{\SUBJs}{\F{subj~}{}}
#+LaTeX_HEADER: \newcommand{\PRED}{\F{pred}{}}
#+LaTeX_HEADER: \newcommand{\falign}{\ensuremath{\operatorname{\emph{falign}}}}
#+LaTeX_HEADER: \newcommand{\fpairs}{\ensuremath{\operatorname{\emph{fpairs}}}}
#+LaTeX_HEADER: \newcommand{\Bleu}{\textsc{Bleu}}

\listoffixmes

* COMMENT generell todo
Nytt denne før INNLEVERING:
# #+EXPORT_EXCLUDE_TAGS: ROTETE

nyttig sparse tree: SKRIV

[[file:~/Master/Master.org::*om%20samanstilling%20fr][skriv det om samanstilling frå forrige Xpar-møte]]

Konsekvent terminologi:
- samanstilling: ei mengd lenkjer mellom to setningar
- lenkje: éin korrespondanse mellom f-strukturar på kjelde- og
  målspråket, men dette inkluderer au kausativ-situasjonen der to på
  kjeldespråket korresponderer med éin på målspråket.

* Innleiing
\label{SEC:innleiing}

\fxnote{TODO: abstract/samandrag}

Denne masteroppgåva utforskar kva det vil seie at to uttrykk er
omsetjingar av kvarandre, og korleis me automatisk kan generere og
evaluere samanstilling (/alignment/) av uttrykk som
står i eit slikt omsetjingsforhold. 

Omsetjingsforhold finn me mellom setningar i kontekst på ulike språk,
men me kan au finne ulike typar ekvivalensforhold (samanstillingar)
mellom frasar innanfor setningane, og mellom lingvistiske
skildringar av setningane. I samanheng med XPar-prosjektet
\citep{xpar2008rcn} har eg sett på metodar for automatisk
frasesamanstilling – å finne omsetjingsforhold mellom grupper av
fleire ord. Resultatet blir ein /annotasjon/, endå ei lingvistisk
skildring av tekstene.


# to situerte setningar er omsetjingar av kvarandre, mellom
# lingvistiske skildringar finn me ekvivalens som me kan tolke i
# forhold til omsetjing...

Det at me kan omsetje mellom lingvistiske skildringar
(t.d. trekkstrukturane til dei grammatiske rammeverka HPSG eller LFG)
gjer det tydeleg at me arbeider med ein /modell/ av språket; ulike
skildringar kan vere sanne innanfor modellen, utan at modellen er lik
språket. Sjølve omsetjingsforholdet er au ein teoretisk storleik, og
me kan leggje ulike kriterium til grunn for å kalle to uttrykk
omsetjingar av kvarandre.

Kriteria avheng av formålet. Samanstillingsannotasjon kan t.d. nyttast
som grunnlag for statistisk eller eksempelbasert maskinomsetjing, i
tillegg til oppbygging av parallelle korpora for meir teoretiske
språkstudie.  For statistisk maskinomsetjing vil alle uttrykk vere
omsetjingar av kvarandre med eit visst sannsyn (kanskje null), ein
har vanlegvis ikkje kriterium som krev lingvistisk analyse. Når
samanstillinga skal nyttast i parallelle korpora for lingvistiske
undersøkingar vil ein kanskje ha krav om at uttrykk som skal lenkjast
er «like» på eit eller anna mål, utover at dei har opptredt saman
ofte; i den manuelle samanstillinga i \citet{samuelsson2006pap} har
dei t.d. ein del reint semantiske kriterium for å opprette
fraselenkjer i ein parallell trebank, men dei har ikkje krav om
syntaktisk likskap.

Xpar-prosjektet, som denne masteroppgåva er ein del av, har mellom
anna som mål å oppdage relasjonar mellom grammatiske funksjonar,
tematiske roller og kasusmarkering, ved hjelp av parallelle trebankar
annotert med djupe grammatiske analysar.  Samanstillinga planlagt der
krev i større grad syntaktisk likskap for å kalle to uttrykk
omsetjingar, men kan difor au tene på det at dei grammatiske analysane
er utvikla med tanke på å vere så parallelle som mogleg.  Dei
grammatiske analysane er gjort i leksikalsk-funksjonell grammatikk,
LFG \citep{bresnan2001lfs}. Ei grammatisk analyse i LFG involverer
både konstituentstruktur (c-struktur) og funksjonell struktur
(f-struktur). Konstituentstrukturen liknar på frasestrukturtrea frå
andre grammatiske tradisjonar. Dei funksjonelle strukturane er
trekkstrukturar, som mellom anna representerer avhengnadsforhold
mellom syntaktiske funksjonar som predikat, subjekt og objekt, i
tillegg til å halde informasjon om grammatiske trekk som genus, tal
eller kasus. Nodar i c-strukturen kan spesifisere informasjon på ulike
stader i f-strukturen[fn:19].

I XPar-prosjektet vil ein finne ut om metodar for frasesamanstilling
kan tene på det at LFG-grammatikkane for dei ulike språka er skrivne
med same prinsipp lagt til grunn; to parallellstilte setningar bør ha
f-strukturar som er like nok til at me kan samanstille frasar ved
hjelp av likskapen mellom f-strukturane. I \citet[s.~72]{dyvik2009lmp}
finn me følgjande hypotese:

\begin{quote}
On the basis of monolingual treebanks constructed from a parallel
corpus by means of parallel grammars it will be possible to achieve
automatic word and phrase alignment with significantly higher
precision and recall than hitherto achieved through other means.
\end{quote}
# todo: «precision and recall» ymtar jo om samanlikning med
# gullstandard som evalueringsgrunnlag

kor «parallel grammars» her krev parallellisme i både f-struktur og
c-struktur.

Men i tillegg til at ein kanskje kan få betre skåre på desse
kvantitative måla, vil lenkjer mellom f-strukturar gi informasjon som
er kvalitativt forskjellig frå det ein kan få med å berre sjå på
lenkjer mellom ord, N-gram eller konstituentar.

I denne masteroppgåva spesifiserer eg kva for lenkjer mellom
f-strukturar og c-strukturnodar me ønskjer, implementerer eit program
=lfgalign= som automatisk finn samanstillingar med slike lenkjer,
evaluerer resultatet av å køyre programmet mitt, og samanliknar dette
med kva me kan få frå andre metodar.

Programmet =lfgalign= opprettar frasesamanstillingar med hjelp av
f-strukturinformasjonen gitt av dei parallelle grammatikkane, og
bottom-up-informasjon om kva for ordsamanstillingar som er
moglege. F-strukturane avgrensar igjen kva for ordsamanstillingar som
er moglege, og kva for c-strukturnodar (syntaktiske frasar) som kan
lenkjast.


** Vegkart
I neste kapittel ser eg på andre metodar for frasesamanstilling.

I kapittel \ref{SEC:ideell} går eg gjennom kva me ønskjer av ei
frasesamanstilling når formålet m.a. er å oppdage relasjonane mellom
syntaktiske funksjonar, kasusmarkering og tematiske roller med hjelp
av ein parallell trebank. Dette ender opp i ei liste med «krav» som
samanstillingane må fylle for å vere lovlege, og som implementasjonen
av den automatiske frasesamanstillinga (kapittel
\ref{SEC:implementasjon}) må følgje.

Eg evaluerer samanstillingane som kjem ut av denne metoden i kapittel
\ref{SEC:diskusjon}, og samanliknar dei med det som er mogleg der me
berre har konstituentstruktur (syntaktiske tre) i tillegg til
ordsamanstilling.

Eg nyttar språka georgisk og norsk i evalueringa, hovudsakleg fordi
dei er svært ulike syntaktisk og morfologisk; Georgisk har t.d. mykje
friare ordfølgje og rikare morfologi.
\fxnote{fortelje om georgisk i kap.5 heller}

Sidan eg ikkje har tilgang på ferdig setningssamanstilt georgisk-norsk
parallelltekst, blir det vanskeleg å køyre den statistiske
ordsamanstillinga som er vanleg som første steg i N-grambaserte
metodar (utan ein god del forarbeid). Difor konsentrerer eg meg i
evalueringa om eit testkorpus kor eg manuelt gjer
ordsamanstillinga. Eg veit heller ikkje enno om nokon statistisk
parsar av høg kvalitet for georgisk, men testkorpuset er ferdig parsa
med LFG-parsaren frå \citet{meurer2008cgg}, c-strukturnodane avgrenser
då kva som er ein syntaktisk konstituent.


** SKRIV Frasesamanstilling frå f-struktur			     :ROTETE:
   \fxnote{limt inn frå prosjektskildringa, dette må omskrivast
   totalt/fjernast. Kan kanskje ta eit par setningar inn i kap.3, men
   innleiinga bør iallfall ha eit kort oversyn over metoden}

Om me har f-strukturane til to omsette setningar, burde det kanskje
vere mogleg å finne ei f-struktursamanstilling først og så finne
ordsamanstillinga ut frå denne. Tanken er at me frå to f-strukturar
som skildrar omsette setningar, kan
1. lage ei samanstilling mellom relevante deler av f-strukturane,
2. nytte denne funksjonelle samanstillinga til å finne ei
   frasesamanstilling, ved å følgje avbildinga frå f-struktur til
   c-struktur ($\phi{}^{-1}$).

Eitt problem som byr seg er hypotesemangfaldet: kva for «deler av
f-strukturane»? Korleis kan me avgrense søkjerommet? I det minste må
me kunne kople det opp mot c-strukturnodar; så \PRED-element bør i det
minste ha lenkjer, medan t.d. tempus og aspektuell informasjon kanskje
er mindre viktig. Men kva kan ignorerast? Vil det oppstå tilfelle då
me bør vekte visse element? (Dvs., må me nokon gong disambiguere med
slike andre element?)
# todo 

Vidare må me vite /korleis/ me samanstiller desse delene. Me kan
t.d. byrje med å kople ytterste \PRED{} frå kvart språk, og så
rekursivt kople \PRED{} i dei relevante
substrukturane\footnote{Dette~krev~sjølvsagt~at~ytre~\PRED{}~faktisk~korresponderer~i~samanstilte~setningar,~ein~ikkje-triviell~påstand.}. Gitt
ein funksjon $i$ som returnerer indeksen til ein f-(sub)struktur, kan
eit førsteutkast til ei /f-samanstilling/, samanstilling på
f-strukturnivå, sjå slik ut:

\[
\falign(f_{1}, f_{2}) =
\{ (i(f_{1}(\PRED)), i(f_{2}(\PRED))) \}
\cup
\bigcup_{g_{1},g_{2}\in \fpairs(f_{1},f_{2})} \falign(g_{1}, g_{2})
\]
# må eg skrive f_1(g_1) etc.?

\falign{} vil gi ei mengd av par av indeksar, kor kvart par altså er
samanstilt. Ein føresetnad her er at me i tillegg veit kva for par av
substrukturar som er «relevante» ($\fpairs(f_{1},f_{2})$).

#+BEGIN_LaTeX
Sjølv om f-strukturar abstraherer frå skilnadene i korleis ulike språk
nyttar ordgruppering og ordform til å kode syntaktiske forhold
\citep[s.~14]{bresnan2001lfs}, vil det likevel oppstå forskjellar i
f-strukturane til to parallellstilte setningar i eit korpus; både
pga. «omsetjarfridom» og det at ulike språk nyttar ulike syntaktiske
funksjonar til å uttrykkje det same konseptet. I
f-struktursamanstillinga til \citet[s.~40]{riezler2006gmt} får dei
t.d. ei lenkje frå ein \XCOMP{} på tysk til eit \OBJ{} på
engelsk. Skal ein algoritme gå frå f-strukturar til frasesamanstilling
må han i det minste vere robust nok til å takle slik mangel på
samsvar. Til å byrje med kan me tenkje oss at \fpairs{} gir alle par
av GF-ar som har same plass i
argumentstrukturen\footnote{Ved~å~nytte~argumentplass~kan~me~enkelt~få~til~lenkjer~mellom~GF-ar~med~ulike~namn,~som~vist~i~dømet.}
til predikatet, så viss 'sein$\langle$\SUBJ,\XCOMP$\rangle$' står i
$f_{1}$ og 'have$\langle$\SUBJ,\OBJ$\rangle$' i $f_{2}$, vil \fpairs{}
i det minste returnere
$\{(f_{1}(\SUBJ),f_{2}(\SUBJ)),(f_{1}(\XCOMP),f_{2}(\OBJ)),...\}$.
Men om me ikkje har slikt samsvar i argumentstrukturar, vil \fpairs{}
ha ein vanskelegare jobb.
#+END_LaTeX

Eit større problem er nok adverbial (elementa i \F{adjunct}{}), kor
f-strukturane ikkje gir like greie hint om kva for substrukturar som
høyrer
saman\footnote{Det~er~mogleg~at~f-samanstillinga~av~adverbial~kan~tene~på~informasjon~frå~(og~difor~bør~skje~etter)~samanstillinga~av~frasane~som~projiserer~argumentfunksjonane.}. Ein
del av masteroppgåva vil altså vere å komme med forslag til funksjonen
\fpairs{}.


f-samanstillinga kan nyttast til å gi ein samanstilling av frasane dei
representerer. $\phi^{-1}$ gir no ei samanstilling mellom funksjonelle
domene i c-strukturane, me har t.d. ei lenkje mellom domenet
$d_{1}=\{X, Y, Z\}$ på språk 1 og $d_{2}=\{U, V, W\}$ på språk 2. Kvar
node frå $d_{1}$ vil kunne (symmetrisk) samanstillast med ein (eller
ingen) frå $d_{2}$.

Her kan me utnytte det at frasestrukturane i dei ulike grammatikkane
er tufta på same X-bar-prinsipp. Ein $XP\in d_{1}$ skal sannsynlegvis
samanstillast med ein $YP\in d_{2}$ (der $X$ og $Y$ gjerne er same
symbol, men au kan vere t.d. $V$ og $I$). I tillegg skal høge nodar
sannsynlegvis samanstillast med andre høge nodar, der alt anna er
likt, medan mangel på samsvar i samanstillinga til døtre kan føre til
at mornodar ikkje skal samanstillast; ein formalisering dette steget,
med diskusjon rundt problema, vil au inngå i masteroppgåva.

* Bakgrunn og relaterte metodar
  \label{SEC:bakgrunn}
\fxnote{TODO:\\
   - reine N-gram-samanstillingar, dependensbaserte\\
   - ulike formål for samanstilling gir ulike metodar\\
   - kort introduksjon til LFG \\
}
** SKRIV Relaterte metodar
Automatisk frasesamanstilling er eit nytt felt. Det finst allereie
veldig gode system for automatisk setningssamanstilling, og automatisk
samanstilling av ord har komme langt, men nivåa mellom ord og setning
ser ut til å by på fleire problem. \fxnote[inline,nomargin]{«by på
fleire problem» -- weasel wording, TODO omskriv.} Dei ulike tilnærmingane
som finst er prega av formåla til utviklarane. Det er verdt å merkje
seg at ordet «frase» ofte blir nytta i litteraturen om strenger av ord
(N-gram) som ikkje treng vere syntaktiske konstituentar, igjen
avhengig av formålet med metoden.

Innanfor korpuslingvistikken har t.d. \citet{piao2001mwu} nytta enkel
kollokasjonsinformasjon for å først finne sannsynlege nominale frasar
på engelsk og kinesisk (dvs. «chunking»), og så samanstille desse; her
er evalueringsgrunnlaget rett og slett ein manuell gjennomgang av dei
mest sannsynlege omsetjingane dei får. \fxnote{fleire slike? meir om
dette, algoritmen}

Den manuelle frasesamanstillinga i \citet{samuelsson2006pap}, nemnt
over, blei nytta som evalueringsstandard for den automatiske metoden i
\citet{samuelsson2007apa}.  Her kjem frasesamanstillinga frå ei
ordsamanstilling, der berre N-gram som svarer til ein syntaktisk node
blir lenkja som frasar (meir om denne metoden nedanfor). Formålet er å
lage ein parallell trebank, kor det altså er unyttig å lenkje «frasar»
som /ikkje/ er konstituentar.

Sjølv om fraselenkjer kan vere nyttige i korpuslingvistikken er det
hovudsakleg innanfor statistisk maskinomsetjing at ein har forska på
samanstilling av frasar. \citet{koehn2003spb} gir ei grundig
evaluering av ulike statistiske metodar for frasesamanstilling til
bruk i stokastisk maskinomsetjing. Dei nyttar \Bleu-skåren til å
rangere resultata
\citep[Papineni~et~al.,~2001,~i][s.~51]{koehn2003spb}, som gir ei
rangering ved (N-grambasert) samanlikning med ferdig omsett tekst.

Den første metoden, /AP/, er reint N-grambasert. Dei nyttar verktøyet
Giza++ \citep[Och~og~Ney,~2000,~i][s.~50]{koehn2003spb} til å indusere
ordsamanstilling frå eit setningssamanstilt korpus (vha. «modell 4»
for ordsamanstilling, utvikla ved IBM av \citet{brown1993msm}). Denne
samanstillinga er 1-til-n (t.d. eitt engelsk ord til to franske), så
dei finn ordsamanstilling for begge retningar og tek så snittet av alle
moglege N-gramsamanstillingar som ikkje er i konflikt med
ordsamanstillingane. Dei føyer så på ord frå unionen av desse
vha. nokre enkle heuristikkar.

Den andre metoden, /Syn/, tek berre med dei frasane som står under
syntaktiske nodar i eit parsa korpus; frasesamanstillinga til /Syn/ er
ein delmengd av den i /AP/. Denne syntaktisk informerte modellen gav
ein mykje dårlegare \Bleu-skåre enn den reint N-grambaserte modellen
(faktisk dårlegare enn omsetjingane frå den opphavlege modell 4 for
ordsamanstilling, utan frasesamanstilling). Dei forklarer dette med
den store mengda uttrykk som ikkje utgjer syntaktiske konstituentar i
følgje parsaren deira, men likevel konsekvent blir omsett til visse
uttrykk på det andre språket (t.d. «es gibt» på tysk til «there is» på
engelsk).

Seinare resultat har vist at ein /kombinasjon/ av syntaktisk
informerte metodar med reint N-grambaserte modellar (dvs. i motsetning
til å berre fjerne samanstillingar mellom ikkje-konstituentar) kan
auke skåren i ein maskinomsetjingsevaluering, både om ein som i
/Syn/-modellen nyttar frasestrukturinformasjon, men i endå større
grad om ein nyttar dependendsinformasjon
\citep{tinsley2007ept,hearne2008ccd}. Dette er interessant med tanke
på at LFG-analysane gir begge typar informasjon.

\citet{riezler2006gmt} utvikla ein metode for å kombinere frasebasert
statistisk maskinomsetjing med LFG-basert setningsgenerering. Dei finn
ei n-til-m-ordsamanstilling med Giza++ som i metodane over, men parsar
i tillegg setningane i LFG. Dei to moglege f-strukturane som liknar
mest blir valt ut, og frå ordsamanstillinga finn dei
mange-til-mange-korrespondansar mellom substrukturane i
f-strukturane. Ved å leggje til LFG-basert generering fekk det
kombinerte systemet betre resultat på langdistanseavhengnader og
generalisering til nye uttrykk med strukturell likskap til tidlegare
observerte uttrykk.
\fxnote{Dette er motsett retning av det mitt program gjer, nemne
seinare?}

Så langt har eg ikkje kome over metodar som går i motsett retning,
altså prøver å finne eller betre på frase- og ordsamanstilling ut frå
ein LFG-parse; det er dette som er strategien til programmet
=lfgalign= i kapittel \ref{SEC:implementasjon}.


** SKRIV Eit kort oversyn over leksikalsk-funksjonell grammatikk
I dei følgjande kapitla nyttar eg ein del LFG-terminologi. Difor gir
eg her eit kort oversyn over det som kan vere nytt for dei som er meir
vand med andre grammatiske rammeverk.

- modellteoretisk (vs enumerativt) \fxnote[inline,nomargin]{TODO hente Pullum-del frå kap.3 og leggje inn her kanskje?}

- f-struktur

- c-struktur

- endosentrisitetsprinsippa

- \xbar

- $\phi$, $\phi^{-1}$

* Krav til frasesamanstilling
\label{SEC:ideell}

** Introduksjon
I denne delen prøver eg å finne fram til kva som er den best moglege
frasesamanstillinga. Eg argumenterer for at «best» her må tolkast i
forhold til eit formål, og tek utgangspunkt i visse krav for
ordsamanstilling gitt i \citet{thunes2003eal}. Eg kjem fram til at når
formålet er utvikling av fasesamanstilte trebankar må ein revidere
kravet om likskap i argumentstruktur, og gir eit forslag til krav for
frasesamanstilling i trebankar.

** Kva er formålet med ei frasesamanstilling?
I frasebasert statistisk maskinomsetjing (PBSMT) skal ei
fraselenkje[fn:11] forbetre maskinomsetjing på eitt eller anna mål,
t.d. \Bleu-skåren. \Bleu-skåren samanliknar ferdig
omsett tekst (ein gullstandard) med det automatisk omsette, ved å
sjekke kor mykje N-gram-overlapp det er mellom tekstene. Ei
fraselenkje mellom N-grammet /es gibt/ og /there is/ (dvs. eit auka
sannsyn for å nytte slike par i omsetjinga) kan gi ein høgare endeleg
skåre i \Bleu. Som vist i \citet{koehn2003spb} fekk dei ein
lågare \Bleu-skåre når dei fjerna lenkjer mellom nodar som, i
# todo: referere til den faktiske parsaren? det var Bikel kanskje?
følgje ein robust statistisk PCFG-parsar, ikkje var syntaktiske frasar
(konstituentar). Dvs. at i figur \ref{fig:ikkjenode} vil lenkja vist
ved den prikkete lenkja bli fjerna frå mengda over moglege lenkjingar
om ein berre held seg til syntaktiske konstituentar, og
$p(es~gibt,~there~is)$ vil ikkje bli tilsvarande auka i den
statistiske omsetjingsmodellen. Sidan PBSMT, som skildra i
\citet{koehn2003spb}, er agnostisk til syntaktiske høve i
omsetjingssteget[fn:1] er det for dei ingen grunn til å berre halde
seg til samanstilling mellom syntaktiske konstituentar; dei har i
utgangspunktet meir nytte av kollokasjonsinformasjon.

#+BEGIN_LaTeX
  \begin{figure}[htp]
    \vfill{} % how todo?
\begin{tikzpicture}
   \Tree [ [.\node(aDE){Es}; ]
    [.\node(pDE){XP};      
    \edge[roof]; \node(rDE){    gibt Frost an meiner Tür };  ] ] 
    \begin{scope}[shift={(2in,0in)}]
      \Tree [ [.\node(aEN){There};  ]
            [.\node(pEN){YP}; \edge[roof]; \node(rEN){ is frost at my door}; ] ]
          \end{scope}
          \draw[-] (pDE)..controls +(north:2) and +(north:2) .. (pEN); 
          \draw[dashed,-] (rDE.west)..controls +(south:2) and +(south:2) .. (rEN.west); 
          \draw[dashed,-] (aEN)..controls +(south west:1) and +(south:1) .. (rEN.north west); 
          \draw[dashed,-] (aDE)..controls +(south west:1) and +(south:1) .. (rDE.north west); 
\end{tikzpicture}
   \caption{N-gram-samanstilling versus syntaktiske frasar}
    \label{fig:ikkjenode}
  \end{figure}
#+END_LaTeX
# there's frost at my door
# es gibt Frost an meiner Tür

Men sett no at me ikkje har som formål å nytte frasesamanstillinga til
reint N-grambasert omsetjing. Kva for /lingvistiske/ krav kan me stille
til å kalle to frasar samanstilte? I einkvar større parallelltekst vil
parallellstilte setningar ha visse syntaktiske og semantiske[fn:6]
omsetjingsskifte, t.d. leksikalisering av syntaktiske konstruksjonar
eller omvendt, endring av ordklasse, presisering/depresisering,
endringar i leksikale trekk (t.d. telleleg/utelleleg),
osb. \citep[s.~56--62]{munday2001its}, slik at den einaste
fullstendige, «perfekte» samanstillinga vil vere
identitetsfunksjonen. Me må godta ein del mangel på samsvar; kor mykje
me godtek blir då avgjort av formålet med samanstillinga.

Eg føreset her at eitt av formåla med samanstillinga er å kunne
oppdage korleis ulike språk realiserer semantiske roller syntaktisk;
då spesielt i forhold til hypotesane gitt i \citet[s.~7]{xpar2008rcn},
t.d. at «case marking might be useful to further determine a given
argument's semantic role». (Skal me finne det siste, må me altså kunne
samanstille frasar med ulik kasusmarkering, men ha krav om lik
tildeling av semantiske roller.)

Eit anna mogleg formål er å nytte desse frasesamanstillingane til
maskinomsetjing. \citet{riezler2006gmt} nyttar ein stokastisk
frasesamanstilling til å oppdage transfer-reglar for bruk i LFG-basert
generering i maskinomsetjing. Dette er reglar som omsett fragment av
ein f-struktur på kjeldespråket til f-strukturfragment på
målspråket. (Eit krav på utforminga av moglege transfer-reglar hindrar
at ein får reglar som lenkjar ikkje-konstituentar, eg kjem tilbake til
dette nedanfor.)  Samanstillinga utvikla her burde au kunne nyttast
til å finne slike transfer-reglar.

Nedanfor utviklar eg eit forslag til krav for ei frasesamanstilling,
med desse formåla i tankane. Om alle krava er moglege å implementere,
er eit separat problem.

** Krav / skrankar for frasesamanstilling i ein LFG-trebank

Samanstilte frasar bør ha nok semantisk likskap til å kunne opptre som
omsetjingar i liknande omgivnader
\citep[s.~74]{dyvik2009lmp}. \citet{thunes2003eal} gir nokre passande prinsipp
for å fastslå det som kan kallast /omsetjingsmessig korrespondanse/, for
ordsamanstilling. Dette er prinsipp som skal gjelde for eit litt forskjellig
formål[fn:typetoken], men som au «ligger nær opp til det vi intuitivt
mener er riktig» \citep[s.~2]{thunes2003eal}. Prinsippa blir nytta til
å lage ein gullstandard for ordsamanstilling (hovudsakleg for dei opne
klassene), og er definert ved å vise til kva for rolle eit argumentord
speler, eller kva for rolletildeling eit predikat eller modifiserande
ord gir. Så for å t.d. samanstille to verb må dei ha like mange
semantiske argument (men argumenta treng ikkje alle realiserast
syntaktisk) og dei må /tildele same roller/; medan argumenta må /spele
same rolle/, og både argument og adjunkt må vere /koreferente/. Lenkja
ord må vere del av frasar som speler same rolle i «det som er felles i
interpretasjonene av [dei to setningane]» \citep[s.~3]{thunes2003eal}.

Viss me tek utgangspunkt i det siste, vil det vere naturleg å i
tillegg lenkje desse frasane som speler same rolle i «det som er
felles i interpretasjonene».

Krava for ordsamanstillinga må au vere fylt for at desse frasane kan
samanstillast. Ein ordsamanstilling er altså naudsynt for ein
frasesamanstilling, og omvendt. Dette er berre motsetningsfylt om me
føreset at det eine er derivert av det andre; men dette har me ingen a
priori grunn til å gjere. Krava eg her utviklar bør i staden sjåast på
som /skrankar/ på moglege samanstillingar, på same måte som dei
modellteoretiske tolkingane av LFG og HPSG.

\citet{pullum2001dbm} gir ein god gjennomgang av forskjellen
mellom derivasjonelle (enumerative) grammatikkar og skrankebaserte
modellteoretiske grammatikkar, kor førstnemnde definerer /mengder av
uttrykk/ ved avleiing frå startsymbol, medan sistnemnde gir skildringar
av /enkeltuttrykk/. Ein modellteoretisk grammatikk kan i tillegg skildre
strukturen (eller dei moglege strukturane) til /fragment/ av setningar,
og denne strukturen er lik det bidraget som fragmentet tilfører
skildringa av heile setninga. Det tilsvarande er ikkje mogleg å gjere
derivasjonelt. \citet[s.~32--33]{pullum2001dbm} gir t.d. eit fragment
som kjem midt i eit høgreforgreina tre; ein derivasjonell skildring
ville måtte skildre treet over eller under, men utan informasjon om
kva som kjem til høgre eller venstre kan me ikkje (på ein
ikkje-vilkårleg måte) skildre subtreet utanfor fragmentet heilt fram
til terminal- eller startsymbol. 

Sidan ei frasesamanstilling er ei skildring av forhold mellom
setningsfragment vil det vere naturleg å skildre dei ønskelege
forholda som skrankar på moglege samanstillingar. Dette let oss au
setje skrankar på både frase- og ordsamanstilling sameleis, utan å
måtte ha krav om at den eine samanstillinga er fullstendig avleiia av
den andre; noko me ikkje har eit /a priori/ grunnlag for å seie. 
# hermeneutisk kopling, SKRIV!
# og kan me lage fragmentariske lenkjingar??

Sidan metoden er mynta på bruk i ein LFG-parsa trebank, og delvis vil
nytte denne parsen som datagrunnlag, er det naturleg å nytte same
konsept som blir nytta i LFG[fn:9] (f-struktur, c-struktur,
endosentrisitetsprinsipp, \xbar{}-tre, osb.)  au i desse krava til den
«beste» frasesamanstillinga; i den grad LFG gir ein generaliserbar
skildring av syntaks, bør desse krava vere generaliserbare til andre
teoriar.

Eg byggjar vidare på krava frå \citet{thunes2003eal} nedanfor, men
kjem som nemnd med visse endringsforslag.
# todo

** Kva kan samanstillast?

Viss to uttrykk er samanstilt på setningsnivå (slik at me dimed kan gå
ut frå at dei er omsetjingar av kvarandre), og begge har ein
LFG-analyse, så har me iallfall tre ulike nivå kor me kan finne
ekvivalensforhold under setningsnivå:
1. mellom ord i setningane,
2. mellom f-strukturar, 
3. mellom c-strukturnodar.

Alle ord i setninga er /kandidatar/ for samanstilling med ord i
omsetjinga, men /a priori/ kan me ikkje utelukke at eit ord ikkje har ei
lenkjing, og me kan heller ikkje utelate mange-til-mange-lenkjing. Det
same gjeld nodane i c-strukturen.

\fxnote{i tillegg vil samanstilling av andre trekk vere endå eit steg
lenger vekk frå observerte data}

Når det gjeld f-strukturane er det ganske mange element me teoretisk
sett kunne ha samanstilt, t.d. enkelttrekk som bestemtheit eller dei
uordna mengdene med adjunkt, men det som er mest /nyttig/ er nok å
berre gjere samanstillingar der det er ei nær kopling til orda i
setninga. Sidan alle PRED-element i ein f-struktur unikt står for
predikerande ord, kan me -- gitt to samanstilte setningar -- la
\emph{kandidatane for samanstilling på f-strukturnivå} inkludere[fn:12]
alle desse PRED-elementa i f-strukturane til setningane. PRED-element
representerer semantiske bidrag som oftare er naudsyne på begge språk i
omsetjingar, medan andre f-strukturtrekk gjerne er valfrie på det eine
av språka; det er ikkje alle språk som har t.d. obligatorisk
kasusmarkering, og ein vil kanskje nytte trebanken til å oppdage
nettopp slik variasjon.  PRED-elementa er i tillegg gjerne enklare å
knyte direkte opp mot konkrete tekststrengen, medan t.d. aspekt
kanskje er umogleg å skilje frå tempus i affikset.

Eg føreslår følgjande føringar:

\ex. \label{f-links} Ei samanstilling av to PRED-element i f-strukturane tilseier at:
\a. \label{f-links-substr} f-strukturane til desse er lenkja,
\b. \label{f-links-words} orda i setningane som projiserer
   PRED-elementa tek del i ei samanstilling med kvarandre (kor andre
   ord kan vere involvert), og at
\c. \label{f-links-domain} iallfall dei øvste nodane i det funksjonelle
   domenet[fn:7] til f-strukturen er samanstilt.

(Underordna nodar i det funksjonelle domenet kan berre lenkjast om
visse krav, gitt nedanfor, er oppfylt. Me kan altså gjerne ha
c-strukturnodar som ikkje er lenkja til andre nodar.)

\fxnote{backe det med eksemplar i trebank; kople til adj-arg-lenkje}

Påstandane over må forsvarast. Punkt \ref{f-links-substr} og
\ref{f-links-domain} over seier at viss PRED-elementa projisert av
t.d. to verb i verbfrasar er lenkja, vil /heile/ VP-ane vere lenkja
(både VP-nodane som dominerer dei lenkja funksjonelle domena og
f-strukturane frå ytre PRED til verba), det er dette som gjer det til
ei fraselenkje; medan i følgje punkt \ref{f-links-words} vil denne
fraselenkja leie til at sjølve verba au er lenkja, ein sterkare
påstand sidan dette tilseier at /PRED-samanstilling impliserer
ordsamanstilling/. I visse tilfelle er dette heilt uproblematisk,
t.d. viss /I slept down by the river/ skal lenkjast med /Eg sov nede
med elva/ vil me uansett lenkje /slept/ og /sov/; dette kan gjelde
transitive verb au:

\ex. \a. The locusts have no king, just noise and hard language\\
     $\leftrightarrow$
     \b. Grashoppene har ingen konge, berre støy og krasse ord

\fxnote{der ADJUNKT ikkje er realisert, lenkjer me ikkje PRED.  skal
me då ikkje lenkje ord heller?}

\fxnote{PRED->ord :: iallfall\\
PRED<-ord :: ?\\
PRED<->ord\\
PRED, ord}

#+BEGIN_LaTeX
\emph{have/har} tek del i VP-samanstillinga \emph{have no king.../har ingen konge...}.

Som nemnd over; ordsamanstillinga treng ikkje vere ein-til-ein, det
punkt \ref{f-links-words} seier er at desse orda iallfall er ein del
av ein samanstilling med kvarandre (i \Last altså
VP-samanstillinga). Kanskje er dette ei mange-til-mange-lenkjing som
ikkje \emph{kan} reduserast til ein-til-ein-lenkjingar; eller kanskje er
det som i \Last mogleg å skilje ut delsamanstillingar, som
\emph{have/har}. Eg kjem tilbake til dette i del \ref{SEC:lik-argstr} om
argumentstruktur og adjunkt. 
#+END_LaTeX

\fxnote{avsnittet over er litt rotete TODO}

Alle nodar i c-strukturen (alle syntaktiske /frasar/konstituentar/ i
setninga) som kan koplast til PRED-haldande f-strukturar, vil altså
vere kandidatar for samanstilling på c-strukturnivå (dette inkluderer
diskontinuerlege konstituentar), men ikkje alle vil bli samanstilt.
*** TOGROK finst det tilfelle der ordlenkjer ikkje impliserer PRED-lenkjer?
   hypotese: det er alltid slik at \\
   ordlenkjing av predikerande ord => PRED-lenkje
** TOGROK kva med ekspletivar? ingen PRED men heller ikkje C/F/I     :ROTETE:
Kandidatane på f-strukturnivå må jo inkludere desse au...
** SKRIV LPT						     :ROTETE:
«a source word WS and a target word WT are taken to correspond
translationally only if (i) WT can in general (out of context) be
taken to be among the semantically plausible translations of WS, i.e.,
WT belongs to the set of 'linguistically predictable translations
(LPT)' of WS, and (ii) WS and WT occupy corresponding positions within
corresponding argument structures.»

«a source phrase PHS and target phrase PHT are taken to correspond if
(i) they contain corresponding words, (ii) PHS contains no word or
phrase corresponding to a target word or phrase outside PHT, and
similarly (iii) PHT contains no word or phrase corresponding to a
source word or phrase outside PH.»
** Funksjonsord
\label{SEC:fnord}
I tillegg kan me ha ord i setninga som ikkje tilsvarer PRED-element i
f-strukturen, typisk funksjonsord (t.d. /som/, /at/). Ved
endosentrisitetsprinsippa til \citet{bresnan2001lfs} er komplementet
til funksjonelle kategoriar (C, I, P) ein funksjonell ko-kjerne. 

\ex. \label{fnordkrav} Skal nodar for ord som ikkje projiserer
     PRED-element[fn:10] samanstillast, må følgjande krav vere oppfylt:
\a. det funksjonelle domenet (gitt ved komplementet) må vere
   samanstilt, og
\b. dei er begge c-strukturhovud.

#c-strukturen må vere tilstrekkeleg parallell \citep{dyvik2009lmp} til
#    å lenkje dei preterminale nodane, jf. krav \ref{subnodekrav} (gitt
#    i del \ref{SEC:subnode} nedanfor, om underordna c-strukturnodar).

Om \Last[a og -b] er oppfylt, kan me få samanstillinga vist i figur
\ref{fig:fnord}, og i dette tilfellet er \Last[b] oppfylt og \Last[a]
vil vere oppfylt om me kan samanstille /cvimda/ med /det regnet/.

#+BEGIN_LaTeX
  \begin{figure}[htp]
   \vfill{} % how todo?
  
  \begin{tikzpicture}
  \Tree
  [.IPfoc
    [.PROPP [.PROP abramsma ] ] 
    [.I' [.I \edge[roof]; {iCoda} ]
             [.S [.CPsub
                  [.\node(Csub){Csub};  rom ]
                  [.IP \edge[roof]; {cvimda} ]]]]]
      \begin{scope}[shift={(2in,0in)}]
  \Tree
  [.IP
    [.PROPP [.PROP Abrams ] ]
     [.I' [.Vfin visste ]
              [.S [.VPmain [.CPnom
                           [.\node(Cnom){Cnom};  at ] 
                            [.Ssub \edge[roof]; {det regnet} ]]]]] ]
  \end{scope}                      
  \draw[dashed,-] (Csub)..controls +(south west:3) and +(south:1) .. (Cnom) ;
  \end{tikzpicture}
  \caption{Mogleg samanstilling av funksjonsord mellom georgisk og norsk (bokmål)}
   \label{fig:fnord}
  \end{figure}
#+END_LaTeX
*** TOGROK cvimda<PRO> men regne<>expletive -- lenkje? 		     :ROTETE:

** Lenkjing av underordna c-strukturnodar
\label{SEC:subnode}

Toppnodane i eit lenkja funksjonelt domene i c-struktur (XP på språk
1, ZP på språk 2) vil ha ein informasjonsmessig korrespondanse, og kan
samanstillast. Men det er mogleg å samanstille to toppnodar i
funksjonelle domene i c-strukturen utan at nodane under (X', Z') er
samanstilt. Ein grunn til å ikkje samanstille desse underordna nodane,
vil vere viss spesifikator til X ikkje speler same rolle i tolkinga
som spesifikator til Z, dvs. viss YP og WP i figur \ref{fig:subnode}
ikkje er lenkja.


Me kan utelukke lenkjing av ikkje-konstituentar som /there is/ ved å
krevje at ei fullstendig samanstilling mellom to frasar må vere slik
at heile substrukturen au er samanstilt. /There is/ og /Es gibt/ i
figur \ref{fig:ikkjenode} kan då ikkje samanstillast åleine, men berre
som del av ei ytre frasesamanstilling.
Så når /kan/ me samanstille nodane som står under øvste node i
f-domenet?

#+BEGIN_LaTeX
\begin{figure}[htp]
   \vfill{} % how todo?
   \begin{tikzpicture}
  \Tree  [.\node(XP){XP};  \node(YP){YP};  
                                    \node(X'){X'};   ]
      \begin{scope}[shift={(2in,0in)}]
  \Tree  [.\node(ZP){ZP};  \node(WP){WP};  
                                    \node(Z'){Z'};   ]
\end{scope}
\draw[-] (XP)..controls +(north:1) and +(north:1) .. (ZP) ;
  \draw[dashed,-] (YP)..controls +(south:1) and +(south:1) .. (WP) ;

\end{tikzpicture}
   \caption{Lenkjing av underordna c-strukturnodar}
   \label{fig:subnode}
  \end{figure}
#+END_LaTeX

I figur \ref{fig:subnode} der XP og ZP er lenkja, vil YP og WP -- i
kraft av å vere toppnodar i sine domene -- måtte ha ei lenkje i
f-strukturen for at c-strukturnodane kan lenkjast (det kunne jo
t.d. hende at f-strukturen projisert av YP samsvarte med den projisert
av Z', eller ein struktur under Z').

Om me skal lenkje Z' og X' i figuren over må dei respektive
spesifikatornodane vere lenkja. Me får då følgjande krav:

\ex. \label{subnodekrav} Krav for lenkjing av underordna
c-strukturnodar:
\a. c-strukturnodar som ligg under øvste node i to funksjonelle
    domena kan berre samanstillast med nodar som ligg innanfor desse
    domena,
\b. c-strukturnodar kan berre samanstillast om deira funksjonelle
    domene er lenkja på f-strukturnivå,
\c. om ein c-strukturnode X' som ikkje er toppnode i det funksjonelle
    domenet har ein søsternode YP, må YP vere samanstilt med ein
    søsternode til Z' for å samanstille X' og Z'

# føresetnad at me berre har binære tre...hmm...

\Last[a] seier at om XP og ZP er samanstilt, der XP er t.d. OBJ til
IP, kan ikkje Z' samanstillast med SUBJ til IP osb., men berre til
nodar innanfor OBJ-domenet. \Last[c] påført figur \ref{fig:subnode}
seier altså at spesifikatornodane må vere lenkja for at X' og Z' skal
lenkjast (manglande søsternode på den eine sida vil au hindre
samanstilling).

I figur \ref{fig:fnord} er alle nodane under S vist i dei to trea i
same funksjonelle domene (kvar node under S er annotert med $\uparrow
= \downarrow$), så om dei funksjonelle domena er samanstilt (som krev
at /rom cvimda/ og /at det regner/ er samanstilt), vil \Last[a og -b]
vere oppfylt kva gjeld CP-komplementa -- lenkjinga går ikkje ut over
dei funksjonelle domena. Sidan Csub og Cnom er funksjonelle kategoriar
er dei au samanstilt via samanstillinga av S-nodane og føringane i
\ref{fnordkrav}, og \Last[c] er då oppfylt. \Last står altså ikkje i
vegen for å samanstille IP-en over /cvimda/ og Ssub.

I figur \ref{fig:ikkjesub} derimot \citep{mrs-suite}, kan me ikkje
samanstille I'-nodane. PRONP-noden, spesifikator på den norske sida,
er ikkje lenkja med nokon spesifikator på den georgiske sida. Den
informasjonen (her reint syntaktisk) som ordet /det/ tilfører IP, ligg
under I' på georgisk. Om me skulle lenkja I', måtte me altså hatt ein
georgisk spesifikator som var lenkja til den norske PRONP.

#+BEGIN_LaTeX
\begin{figure}[htp]
 \vfill{} % how todo?
\begin{tikzpicture}
\Tree [.\node(IPb){IP}; 
  [.PRONP \edge[roof]; {det} ] 
  [.\node(Ibarb){I'};  [.Vfin \node(åpnet){åpnet};  ]
       [.S \edge[roof]; {seg} ] ] ]
      \begin{scope}[shift={(2in,0in)}]
\Tree [.\node(IPk){IP}; 
  [.\node(Ibark){I'};  [.V    \node(gaiGo){gaiGo};  ]
  ] ]
\end{scope}
 \draw[-] (IPk)..controls +(north:1) and +(north:1) .. (IPb) ;
  \draw[dashed,-] (Ibark)..controls +(north:1) and +(north:1) .. (Ibarb) ;
 \draw[-] (gaiGo)..controls +(south:1) and +(south:1) .. (åpnet) ;

\end{tikzpicture}
\caption{Umogleg samanstilling av funksjonsord mellom bokmål og georgisk}
 \label{fig:ikkjesub}
\end{figure}
#+END_LaTeX

*** SKRIV døme!							     :ROTETE:
*** TOGROK me_OBJ gusta X_SUBJ // I_SUBJ like X_OBJ ??		     :ROTETE:
*** TOGROK korleis finn me /there is/-lenkjer då? 		     :ROTETE:
(og kva skal me med dei?)

«Til gjengjeld vil me få lenkjer sjølv om me har mellomståande ord
(/There/ never /is/) som opptrer utanfor N-grammet på det andre
språket.»

** TOGROK mange-til-mange-lenkjing i f-strukturane? 		     :ROTETE:
    Eg er litt usikker på om me skal ha slike
    mange-til-mange-korrespondansar i f-strukturane; eg har rekna med
    at ei f-strukturlenkje /impliserer/ ei slags lenkjing mellom det som
    er innanfor f-strukturane; men i \citet{riezler2006gmt} er det i
    staden berre eit krav om at desse f-strukturane er lenkja i same
    transfer-regel.

# Ikkje-komposisjonell mange-til-mange-lenkjing 

\citet[s.~40--41]{riezler2006gmt} tillet mange-til-mange-lenkjing
mellom f-strukturar, så lenge alle f-strukturane som blir lenkja til
slutt opptrer i same transfer-regel. Frå følgjande setningspar:

\ex. Dafür bin ich zutiefst dankbar \\
     I have a deep appreciation for that

lenkjar dei \{/zutiefst/\} med \{ /a, deep, appreciation/ \}, men
sidan \{/appreciation/\} er samanstilt med \{/dankbar/\}, må
transfer-regelen inkludere \{ /zutiefst, dankbar/ \} på den eine sida
og \{ /a, deep, appreciation/ \} på den andre.


*** SKRIV Kva inneber ei mange-til-mange-lenkjing?		     :ROTETE:

** SKRIV Mangel på samsvar i syntaks og semantikk		     :ROTETE:
\cite[s.~5]{kruijffkorbayova2006agc} gir følgjande døme: 
#+BEGIN_LaTeX
\ex.  nikdy nebyl \\
      never was.not\\
      `has never been'
#+END_LaTeX

/nebyl/ blir «svakt» samanstilt med /never/, men «sterkt» samanstilt med
\emph{has ... been} i deira system. I tillegg er det ein sterk samanstilling
mellom /never/ og /nikby/.

# Og i kvantitetsfrasar er talet det semantiske hovudet på tsjekkisk,
# medan einingen er det på engelsk (her følgjer dei semantikken i
# samanstilling).

** TOGROK Diskontinuerlege einingar				     :ROTETE:
   - diskontinuerlege einingar \cite[s.~4]{cheung2002scg}
     [[http://scholar.google.no/scholar.bib%3Fhl%3Dno&lr%3D&ie%3DUTF-8&q%3Dinfo:Qh_MRSftNZgJ:scholar.google.com/&output%3Dcitation&oe%3DMACINTOSH&oi%3Dcitation][@books.google]] -- skal dei eigentleg samanstillast? Kva for problem
     gir dei i forhold til c-strukturnivåsamanstilling?

*** TODO døme på diskontinuerlege konstituentar som er lenkja	     :ROTETE:
** TOGROK Er «compounds» frasar?	     :ROTETE:
 \citep[p.~1]{giegerich2006aea}


** Lik ordklasse?
Ulike språk leksikaliserer same konsept på ulike
måtar. \citet[s.~3]{cheung2002scg} skriv at det engelske ordet
/fulfilment/ meir naturleg blir omsett til eit verb på kinesisk. Det
same gjeld t.d. /solitude/ omsett til norsk. Eit georgisk
verbalsubstantiv (/masdar/) kan bli omsett til eit verb i infinitiv på
norsk[fn:13]. Slike skifte mellom ordklassar er svært vanlege i
omsetjing[fn:3].
# , sjå setning nr. 9 i MRS-suiten \citet{mrs-suite} for infinitiv
# (men ingen masdar der på georgisk no!)
# TODO: omformuler

Me kan opne for ordklasseoverskridande lenkjer der det er samsvar
mellom visse /trekk/, t.d. kan to predikerande ord lenkjast, eller to
«nominale» ord. Ein annan måte å gjere dette på er rett og slett å
krevje ein viss likskap i argumentstruktur. 


** Krav om lik argumentstruktur
\label{SEC:lik-argstr}

\citet{thunes2003eal} gir som nemnd eit krav om at /predikat må ha
tilsvarande semantiske argument/ for å samanstillast.

Om det alltid er slik at to predikat har like mange argument, som kjem i
same rekkjefølgje i argumentstrukturen, vil det gjere den praktiske
oppgåva med å samanstille predikata, og argument med argument, mykje
enklare. Men kan me stille så sterke krav?

Sett at ein setning på språk 1 har ei /at/-setning som adjunkt, medan
denne setninga på språk 2 er eit argument, og at desse setningane
ville vore samanstilte om dei opptredde åleine. Om dei uttrykkjer same
proposisjon og \emph{speler same rolle i verbsituasjonen},
synest det naturleg å lenkje desse.  

Omsetjingsrelasjonar gir data for verbsituasjon, på eit meir generelt
grunnlag enn det me kan få frå einspråklege analysar åleine. Om me har
gode semantiske grunnar for å kalle ein deltakar i ein verbsituasjon
eit argument på eitt språk, vil dei same grunnane gjelde for
omsetjingsmessig korresponderande verb på andre språk. Ein kan då
nytte unionen over alle argument til korresponderande verb til å
karakterisere kva ein meiner med /deltakarane i
verbsituasjonen/. Syntaktiske forhold i språket kan sjølvsagt gi
grunnar til å /ikkje/ kalle dette eit argument (om det er mogleg å
finne akseptable syntaktiske grunnar for å kalle noko ein adjunkt
heller enn eit argument).
 
For å gjere dette konkret kan me sjå på setning 7 i MRS-suiten
\citep{mrs-suite}[fn:4]:

\exg.  abramsi brouns       daenajleva sigaretze, rom cvimda \\
      Abrams.NOM Brown.DAT vedde.3SG sigarett.om, at  regne.3SG.IMP \\
     `Abrams veddet en sigarett med Brown på at det regnet' 

I følgje LFG-parsen til desse setningane har hovudpredikata svært ulik
argumentstruktur[fn:14]. Det norske /vedde/ har _fire_ argument, medan
\emph{da-najleveba} har _to_ (/Abrams/ og /Browne/), kor at-setninga på
norsk og /rom cvimda/ uttrykkjer same proposisjon og speler same rolle
i verbsituasjonen. Den engelske LFG-parsen av den tilsvarande setninga
(mine omsetjingar) gir _tre_ argument, /with/ blir her adjunkt, medan
den tyske grammatikken, som au har _tre_ argument, gjer /at/-setninga
til adjunkt. I \Next nedanfor har eg representert dei omsetjingsmessig
korresponderande frasane i f-strukturane med dei norske omsetjingane
for å illustrere dette:

#+BEGIN_LaTeX
{\avmoptions{}
\ex. \label{vedde}
\a. Adams veddet en sigarett med Browne \hfill{} (norsk bokmål)\\ på at det regnet.\\
    $\\\begin{avm}\[pred & `{\bf{}vedde}<Abrams, sigarett, Browne, regne>' \\
                 adjunct & \{\}\]\end{avm}\\$
\b. abramsi brouns daenajleva sigaretze, rom cvimda. \hfill{} (georgisk)\\
    $\\\begin{avm}\[pred &  `{\bf{}da-najleveba}<Abrams, Browne, regne>'\\
    adjunct &  \{ \rm sigarett \}\]\end{avm}\\$ 
\c. Abrams hat mit Browne um eine Zigarette gewettet, \hfill{}(tysk)\\
    daß es regnet.\\
    $\\\begin{avm}\[pred & `{\bf{}wetten}<Abrams, sigarett>' \\
                  adjunct & \{ \rm Browne, sigarett \}\]\end{avm}\\$
\d. Abrams bet a cigarette with Brown that it was raining. \hfill{}(engelsk)\\
    $\\\begin{avm}\[pred & `{\bf{}bet}<Abrams, sigarett, regne>'\\
                  adjunct & \{ \rm Browne \}\]\end{avm}$

}
#+END_LaTeX

Om ein skal ha grammatikkane som datagrunnlag er det altså eit reellt
problem kva ein skal gjere med mangel på samsvar i
argumentstruktur. Om det alltid var fullstendig samsvar i
argumentstruktur, ville det vore trivielt å lenkje argument: viss to
korresponderande verb hadde tre argument, ville me lenkja det første
med det første, det andre med det andre og det tredje med det
tredje. Men om me har analysar som dei over, ser det ut til at me
treng bottom-up-informasjon om kva for adjunkt og argument som
samsvarer.

Det same gjeld forøvrig lenkjing av adjunkt til adjunkt. Adjunkt
plukker ut si eiga rolle der argument får rolla tildelt frå verbet, og
f-strukturane har ingen hierarkisk inndeling av desse slik me har for
verb og argument, dei er i staden representert som /uordna mengder/.

*** forsvare «tilsvarande» 					     :ROTETE:
Tilsvarande på engelsk: [fn:8]

[fn:8] "wagered * with * that *" på Google gir 215 treff, kor 9 av dei
første 10 følgjer det intenderte mønsteret.
*** TODO Sitere eigen korpusundersøking av variasjon i arg-str?
Ei undersøking av den frasesamanstilte trebanken SMULTRON
\citep{samuelsson2006pap} mot LFG-grammatikkane for engelsk og tysk
fann at 2 av 15 korresponderande verbtoken[fn:15] for høgfrekvente
innhaldsverb fekk analysar kor argument korresponderte med adjunkt
\citep{unhammer2009aaa}.

\fxnote{LCS, dorr}
*** SKRIV kvifor lik arg-str er bra, så kvifor det er eit problem    :ROTETE:
*** TODO Ulik følgje i argumentstruktur
I tillegg til at argument kan lenkjast til adjunkt, kan koreferente
argument ha ulik følgje i argumentstrukturen. Det er klart at me vil
lenkje objektet til /gefallen/ (eller bokmål: /behage/) med subjektet
til /like/, og omvendt.  Men rekkjefølgje i argumentstrukturane i
ParGram-prosjektet er ofte basert på syntaktisk funksjon heller enn
rolle, slik at eit verb som har opplevar som objekt og tema som
subjekt vil ha opplevar nedanfor tema i argumentstrukturen, medan ei
omsetjing av dette verbet kan ha tema nedanfor:

#+BEGIN_LaTeX
{\avmoptions{}
\ex. \a. sie$_j$ gefallen ihnen$_i$ \\
     $\begin{avm}\[pred & `{\bf{}gefallen}<de$_j$, de$_i$>' \]\end{avm}$
    $\\\\\leftrightarrow$\\
     \b. de$_i$ liker dem$_j$ \\
     $\begin{avm}\[pred & `{\bf{}like}<de$_i$, de$_j$>' \]\end{avm}$

}
#+END_LaTeX

Argumentstrukturane i \Last har omvendt intern følgje, og som vist ved
dette dømet er det heller ikkje noko f-strukturinformasjon me kunne
nytta til å sikre lenkjinga /sie/dem/ og /ihnen/de/. Igjen ser det ut
til at bottom-up-informasjon trengst.



**** c- og f-strukturar for dømet over				     :ROTETE:
#+BEGIN_LaTeX
\begin{tikzpicture}
\Tree
[.CP
  [.DP \edge[roof]; {sie} ]   [.C'
    [.V
 \edge[roof]; {gefallen} ]     [.DP \edge[roof]; {ihnen} ]  
]]
\begin{scope}[shift={(2in,0in)}]
\Tree
[.IP
  [.PRONP \edge[roof]; {de} ] 
  [.I'
    [.V \edge[roof]; {liker} ] 
    [.S \edge[roof]; {dem} ] 
]]
  \end{scope}
\end{tikzpicture}

\avmoptions{}
\begin{avm}
\sort{$^{0}$}{\[ {\sc pred} `{\bf gefallen}<[1:{\it pro}],[2:{\it pro}]>'\\
{\sc topic} \sort{$^{1}$}{\[ {\sc pred} `{\it pro}'\\
{\sc ntype} \sort{$^{7}$}{\[ {\sc nsyn} pronoun\]}
\\
{\sc pron-type} pers, {\sc pron-form} sie, {\sc pers} 3,\\
{\sc num} pl, {\sc case} nom\]}
\\
{\sc tns-asp} \sort{$^{4}$}{\[ {\sc tense} pres, {\sc mood} indicative\]}
\\
{\sc obj-th} \sort{$^{2}$}{\[ {\sc pred} `{\it pro}'\\
{\sc ntype} \sort{$^{10}$}{\[ {\sc nsyn} pronoun\]}
\\
{\sc pron-type} pers, {\sc pron-form} sie, {\sc pers} 3,\\
{\sc num} pl, {\sc case} dat\]}
\\
{\sc subj} \[1\]\\
{\sc vtype} main, {\sc stmt-type} decl,\\
{\sc passive} -, {\sc clause-type} decl\]}
\end{avm}




\begin{avm}
\sort{$^{0}$}{\[ {\sc pred} `{\bf like}<[10:de],[11:de]>NULL'\\
{\sc tns-asp} \sort{$^{13}$}{\[ {\sc tense} pres, {\sc mood} indicative\]}
\\
{\sc topic} \sort{$^{10}$}{\[ {\sc pred} `{\bf de}'\\
{\sc ntype} \sort{$^{18}$}{\[ {\sc nsyn} pronoun\]}
\\
{\sc def} +, {\sc case} nom, {\sc ref} +,\\
{\sc pron-type} pers, {\sc pron-form} de, {\sc pers} 3,\\
{\sc num} pl\]}
\\
{\sc obj} \sort{$^{11}$}{\[ {\sc pred} `{\bf de}'\\
{\sc ntype} \sort{$^{45}$}{\[ {\sc nsyn} pronoun\]}
\\
{\sc ref} +, {\sc pron-type} pers, {\sc pron-form} de,\\
{\sc pers} 3, {\sc num} pl, {\sc def} +,\\
{\sc case} obl\]}
\\
{\sc subj} \[10\]\\
{\sc vtype} main, {\sc vform} fin, {\sc stmt-type} decl\]}
\end{avm}

#+END_LaTeX

*** SKRIV døme med wager/3 og vedde/4 og gewettet/3 		     :ROTETE:

*** SKRIV (reinskriv) 						     :ROTETE:
Same globale tyding krev i det minste at, i situasjonen verbet
denoterer, speler deltakarane same rolle. Men dette er endå meir
abstrakt/semantisk enn (semantisk) argumentstruktur...

Problem: ikkje-komposisjonell omsetjing. Same globale tyding. Det
treng ikkje vere berre pragmatisk forskjell--type /kan du lukke døra/
vs /lukk døra/, kor situasjon gjer setningane like--sidan me kan ha
konvensjonaliserte konstruksjoner på L1 kor heile tilsvarer enkeltord
på L2, a la japansk /viss eg ikkje går på skulen så kan det ikkje
vere/ ~= /eg må gå på skulen/. 

Ein føresetnad eg har, er at setningar som er samanstilte faktisk har
ein omsetjingsmessig korrespondanse (dette er min data). Så om eit par
av ytre predikat ikkje korresponderer er det au ein type data; nemleg
at me har ein omsetjingsmessig korrespondanse der det var ein mismatch
i ytre argumentstruktur. (Algoritmen bør då lagre slike mismatches
eksplisitt, ikkje berre la vere å lenkje, for det kan vere andre
grunnar til at det ikkje kom ei lenkjing. A la ekspertsystem: forklare
resonnementet.)

Alternativt ein konstruksjonslenkjing... 

Kan au ha eit krav om at argstr til $PRED_{L1}$ er ein slags delmengd av
argstr til $PRED_{L2}$. 
*** SKRIV True Arguments vs True Adjuncts, Pustejovsky 		     :ROTETE:
   - Treng døme først...
   - Er «with Browne» eit Default Argument for «wager»?
     - D-ARG: he built a house _out of bricks_
   - Adjunkt plukker ut sine eigne roller, per definisjon, ved
     vedde/4 og wager/3 har me ein slik situasjon:
     : vedde <—————wager >———<———wetten
     :        \____with_/     \__dass
     Bottom-up-informasjon vil au vere naudsynt for dei 3 rollene
     som /er/ argument, sidan me kan ha vedde<1,2,3,4> og
     wager<a,b,c>with<d>, kor det er umogleg å seie om d skal på plass
     1,2,3 eller 4 (dvs. me kan ha vedde<a,b,c,d>, vedde<a,b,d,c>,
     vedde<a,d,b,c> og vedde<d,a,b,c> -- men sannsynlegvis er altså
     a,b,c i same rekkjefølgje uansett...)

** SKRIV Kan adjunkt lenkjast til nodar _under_ mor-lenkja?
\label{SEC:merge-daughters}

Krav (vi) i \citet[s.~75]{dyvik2009lmp} krev at viss F_s og F_t er
lenkja, så kan ingen adjunkt D_s til F_s vere lenkja til nodar utanfor
F_t. Men kan ein D_s lenkjast til ei dotternode av argument eller
adjunkt til F_t?

R_t er dotter til F_t, og må då vere lenkja til ei dotter av F_s,
A_s. Då må au alle argument til R_t vere lenkja til døtre av A_s, så
D_s kan ikkje lenkjast til argument av dotternodar til F_t. Kva med
adjunkt? Om me finn eit ulenkja adjunkt til R_t kan me heller ikkje
lenkje dette til D_s ved krav (vi) igjen, sidan D_s står utanfor
A_s.

Men om D_t er ei ulenkja \emph{adjunkt}dotter av F_t, så vil døtre av
D_t kunne lenkjast til D_s, så lenge D_t forblir ulenkja. Me kan altså
sjå ned i adjunktdøtre av F_t for å lenkje D_s. 

På same måte bør ein kunne rekursivt sjå ned i ulenkja adjunktdøtre av
R_t, men ein bør kanskje ikkje kunne lenkje så djupt uansett? Ikkje
automatisk, uansett.



Programmet mitt vil, gitt to initielle f-strukturar med
LPT-korrespondanse, finne alle moglege kombinasjonar av lenkjer som
inneheld alle argument og kanskje adjunkt, dvs. om me har

: F_s [ PRED p<1,2> ADJUNCT { 3 } ]

: F_t [ PRED p<4> ADJUNCT { 5,6 } ]

vil dette vere logisk moglege samanstillingar av «f-strukturdøtre»:

:    (((1 . 4) (2 . 5)) ((1 . 4) (2 . 6)) ((1 . 5) (2 . 4))
:     ((1 . 5) (2 . 6) (3 . 4)) ((1 . 6) (2 . 4)) ((1 . 6) (2 . 5) (3 . 4)))

Me luker ut kombinasjonar som bryt med LPT-korrespondanse. Med full
informasjon bør me sjølvsagt berre ende opp med éin kombinasjon,
t.d. =((1 . 4) (2 . 5))=.

Så langt bør altså krav (i-iv) frå \citet{dyvik2009lmp} vere dekkja.

Me _kan_ krevje at f strukturane-til f strukturdøtre-kan lenkjast
rekursivt for at F_s og F_t skal lenkjast, t.d. både =(1 . 4)= og =(2
. 5)=. Men her kjem det (iallfall) to problem.


*** 1. Kausativar og inkorporering
Om me har 

: F_s [ PRED p<SUBJ, 1, 2> XCOMP 2[ PRED q<1> ] ]

: F_t [ PRED pq<SUBJ,OBJ> ]

kor pq er t.d. ein kausativ som tilsvarer =p<..., q>=, så vil me ikkje
kunne lenkje F_s og F_t sidan det bryt med krav (iii), F_s har eit
argument for mykje. Men her vil det kanskje vere naturleg å ha ei
ein-mange-lenkje:

: ((F_s 2) . F_t)

No kan me sjå på unionen av argument av F_s (minus XCOMP) og argument
av XCOMP, alle argument i denne unionen må då ha LPT-korrespondanse
med argument/adjunkt av F_t, og alle argument av F_t må ha
LPT-korrespondanse med argument/adjunkt av unionen.

Det same bør kanskje skje ved vanleg inkorporering av substantiv, då
må det altså vere mogleg å føye saman t.d. verb og objekt; ein
kombinasjon av dette og kausativ bør vel vere mogleg, t.d.

: F_s [ PRED la<SUBJ, 1>  XCOMP 2[ få<1, 3:pengar> ] ]

: F_ t [ PRED belønn<SUBJ, 1> ]

Igjen ser me på argument frå unionen av =(F_s 2 3)= minus 2 og 3, og
om det er mogleg å lenkje dei til argument/adjunkt av F_t, og omvendt.

Men det bør kanskje vere grenser for kor langt samanføying kan gå… eg
kan ikkje tenkje meg at me vil lenkje =((F_s 2) . F_t)= eller =((F_s
1 2) . F_t)= her:

: F_s [ PRED p<…, 1> XCOMP 1[ PRED q<…, 2> XCOMP 2[ PRED r<…> ] ] ]

: F_t [ PRED pr<…> ]

...men det kan jo hende det finst situasjonar der dette au vil vere
rett. Problemet er altså kor me skal setje grensene i
implementasjonen. Om me skal prøve å samanføye på alle moglege måtar
(altså, der me ikkje har informasjon om LPT), i tillegg til «vanlege»
lenkjer, blir det fort komputasjonelt vanskeleg. Me kan sjølvsagt snu
på LPT-kravet her, og seie at dette er berre lov der me har positiv
informasjon om LPT-korrespondanse, i staden for at det ikkje er lov om
me har motstridande LPT-informasjon, det vil nok hjelpe, men det er
vanskeleg å finne prinsipelle avgrensingar her. 
**** TOGROK adjunkt bør ikkje samanføyast? eller?
Det einaste eg kan
tenkje meg er at adjunkt ikkje bør vere kandidatar for samanføying (i
såfall burde dei vel heller vore analysert som argument?).

*** 2. Adposisjonsobjekt

I følgjande setningspar har me eit objekt «sigarett» som svarer til
PP-en «sigaretze» («sigareti» + «ze»), eit adjunkt:

: Abrams veddet en sigarett med Browne på at det regnet.
: abramsi brouns daenajleva sigaretze, rom cvimda.

: F_s [ PRED sigarett ]

: F_t [ PRED ze<1> 1[ PRED sigareti ] ]

F_s og F_t er døtre av dei ytre predikata i kvar setning, krav (iii)
seier at det må vere LPT-korrespondanse mellom desse for at me skal
kunne lenkje «veddet» og «daenajleva».  Her synest det feil å føye
saman «sigareti» og «ze», =(F_s . (F_t 1))=, sidan «sigarett» ikkje
inneheld informasjonen gitt av «ze».

Det finst då to løysingar. Me kan slakke på LMT-kravet ved å la
=L'(F_t) = {sigaretze, ze}= (evt. ={sigaret, ze}=), då kan me lenkje
=(F_s . F_t)=, medan 1 er ulenkja.

Eller me kan lenkje =(F_s . 1)=, kor me har skikkeleg
LMT-korrespondanse, men då må me slakke på (iii) og (iv), og altså ha
lov til å «hoppe over» ein f-struktur for å lenkje «veddet» og
«daenajleva». F_t er då ulenkja. Det er løysinga valt i
\citet[s.~75,~fotnote~3]{dyvik2009lmp}, og den løysinga eg følgjer
nedanfor.

** TOGROK kva var poenget med dette?				     :ROTETE:
«etter og uten er dei einaste prep som tek setn utan å vere arg»
** ULEST Cyrus, FuSe-prosjektet					     :ROTETE:
\citet{cyrus2004apa}
«Abstract: We report on a recently initiated project which aims at
building a multi-layered parallel treebank of English and
German. Particular attention is devoted to a dedicated
predicate-argument layer which is used for aligning translationally
equivalent sentences of the two languages. We describe both our
conceptual decisions and aspects of their technical realisation. We
discuss some selected problems and conclude with a few remarks on how
this project relates to similar projects in the field.»
** TODO Konstruksjonar og komposisjonell inekvivalens
# eg siterer her alsina frå min eigen artikkel..heller sitere min??
\xbar-teori føreset at det finst éi dotter i kvart ledd som kan
reknast som predikatet for dette leddet. Ei utfordring for
\xbar-baserte teoriar er då handsaming av /komplekse predikat/. Desse
har fleire grammatiske element innanfor same ledd som alle bidrar med
«a non-trivial part of the information of the complex predicate»
\citep{alsina1997cp}. I LFG er det ein føresetnad at me berre har éin
\textsc{pred} ytterst i kvar f-struktur; ulike mekanismar har blitt
føreslått for å handsame dette fenomenet.
# \citep[eg~gir~ein~gjennomgang~i][]{unhammer2008cps}

I omsette tekster kan me få eit analogt problem:

\ex. It can't be done \\
     Det lar seg ikke gjøre

Her vil ytre predikat i f-strukturen på norsk vere
'la<det_1,XCOMP>PRO', kor XCOMP[PRED 'gjøre<NULL,det_1>NULL'].

På engelsk får me 'can<XCOMP,it_2>', kor
XCOMP[PRED 'do<NULL,it_2>']. 

# 'la' er eit 3-plasspredikat, medan 'can' er 2-plass; som strid mot
# kravet nemnd over om like mange argument;
# SEMANTISKE argument! og siter/xref meg på kravet om like mange argument

Skal me lenkje orda /can/ og /la/? På /heile konstruksjonen/ finn me
iallfall eit omsetjingsforhold:
# TODO: presiser/ekpliser analogien mellom CP og
# konstruksjonssamanstilling!

| It can't be done                 | Det lar seg ikke gjøre            |    |
| can't be done                    | lar seg ikke gjøre                |    |
| be done                          | gjøre                             | s? |
| _ can't be VPASS                 | _ lar seg ikke VPASS              | ?? |
| \_$_{1}$ can \_$_{2}$ be VPASS_3 | \_$_{1}$ lar seg \_$_{2}$ VPASS_3 | ?? |

# TODO: skrankebaserte skildringar bør iallfall kunne gi samanstilling
# av deltre; type [ can't [be [ ] ] ] opp mot [ lar [ seg ikke ] ] ,
# kopling opp mot modellteori, Pullum&Scholz.

(kan me få den siste generaliseringa frå trebanken?)


** SKRIV definer sitering frå MRS-suiten			     :ROTETE:
** SKRIV setning 7 i MRS-suiten					     :ROTETE:
# setning 31: her har relativpronomenet (romeli) ingen (anaforisk)
# kopling til hunden... manglar dette?

# eh, betre tittel

# II.bøyingsklasse i aorist-serien har nominativ-subjekt og
# dativ-DO/IO som vanleg, medan
# I.bøyingsklasse-aroist-serie-subjektet står i ergativ, og får
# nominativ-DO og dativ-IO. danajleva må altså vere i
# II.bøyingsklasse, og brouns er indirekte objekt? Applikativ?
  

Ein samanstilling bør i det minste gi følgjande:

# TODO: høgrestill venstre kolonne
| abramsi brouns daenajleva sigaretze, rom cvimda | Abrams veddet en sigarett med Brown på at det regnet |
| abramsi brouns daenajleva sigaretze             | Abrams veddet en sigarett med Brown                  |
| brouns daenajleva sigaretze                     | veddet en sigarett med Brown                         |
| daenajleva sigaretze                            | veddet (en) sigarett (på)                            |
| daenajleva                                      | veddet                                               |
| sigaretze                                       | (en) sigarett (på)                                   |
| rom cvimda                                      | at det regnet                                        |
| cvimda                                          | (det) regnet                                         |
| abramsi                                         | Abrams                                               |
| brouns                                          | Brown                                                |
|                                                 |                                                      |
 
** TOGROK og så finst jo større forskjellar, stilistiske osb...	     :ROTETE:

** TOGROK prosessering, kognitive modellar?			     :ROTETE:
finne empiri frå korleis menneske samanstillar? (dvs., korleis skjer
omsetjing)

- \citet{maier2009sis}, http://linguistlist.org/issues/20/20-1786.html
«cross-linguistic structural phenomena in the language production of
bilinguals in the specific context of translation.»

- http://www.linguistlist.org/pubs/diss/browse-diss-action.cfm?DissID=143

- [[http://books.google.com/books%3Fhl%3Dno&lr%3D&ie%3DUTF-8&id%3DhHFoJguRE4oC&oi%3Dfnd&pg%3DPA141&dq%3Dprocessing%2Btranslation%2Bpsycholinguistic%2Bsyntax&ots%3DNUlz1ebVnE&sig%3DrkMwuX59RoIikvTYGq23HNkYtzc][books.google bialystok????lpb]]: «Translation has been called
  "interlanguage paraphrase"», «a metalinguistic skill». «Paraphrasing
  consists in finding the meaning of two compared sequences and
  showing its equivalence, and this identification constitutes a
  judgment on the sequences»[s.~151]

- [[http://books.google.com/books%3Fhl%3Dno&lr%3D&ie%3DUTF-8&id%3DCZXcTzFLDuwC&oi%3Dfnd&pg%3DPA17&dq%3Dprocessing%2Btranslation%2Bpsycholinguistic%2Bsyntax&ots%3DFUm_X5VCeu&sig%3DNoHLNrNxq7bGNAcsRda8RWNDyOY][books.google house????iic]]: «The process of translation, particularly
  if successful, necessitates a complex text and discourse
  processing. The process of interpretation performed by the
  translator on the source text might lead to a TL text which is more
  redundant than the SL text. This argument may be stated as "the
  explicitation hypothesis", [...] especially marked in the work of
  "non professional" translators» [s.~19--20]

- Hutchinson: «What is a grammatical sentence?» (vanskeleg å unngå
  /talaren/ i akseptabilitetvurderingar); kva _er_ ei frasesamanstilling,
  sånn ute i naturen? 
** TOGROK Retningslinjer for samanstilling			     :ROTETE:
Ved korpusbygging er det vanleg at retningslinjer for samanstilling
blir utvikla /etter kvart som ein finn problem/... (det er vanskeleg å
seie noko /a priori/ om kva for vanskar ein kan finne).



* Implementasjonen av =lfgalign=
\label{SEC:implementasjon}

For å finne ut av kor godt krava i forrige kapittel fungerer til å
avgrense kva for lenkjer som er moglege, har eg implementert dei etter
beste evne i eit Lisp[fn:16]-program.

\fxnote{intro TODO, kanskje noko om kva eg faktisk har fått ut av
implementasjonen} Ei implementering gjer det svært synleg om det finst
manglar i eit formelt krav, eller om noko ikkje er godt nok
spesifisert.

Programmet \texttt{lfgalign}[fn:2] tek inn LFG-analysane av to
setningar som me av uavhengige grunnar trur er omsetjingar av
kvarandre. LFG-analysane må vere disambiguerte og i Prolog-formatet
frå XLE[fn:5]. Programmet les inn dei to filene og opprettar ein
intern representasjon av LFG-analysen.  \fxnote{treng eg ein eigen del
om LPT i dette kapittelet? Implementasjonen er jo veldig enkel
iallfall.}

Me kan i tillegg gi programmet informasjon om kva for ord-omsetjingar
me ser på som lingvistisk prediktable. Intensjonen er at dette kan
vere informert av omsetjingstabellen frå eit automatisk
ordsamanstillingsprogram, eller av handskrivne omsetjingsordbøker.

Programmet byrjar lenkjinga med f-strukturane. Ei
f-struktur\emph{samanstilling} er ei mengd med /lenkjer/ mellom
individuelle f-strukturar. Resultatet av lenkjinga på dette nivået kan
vere tvitydig: sidan det ofte finst fleire måtar å lenkje argument og
adjunkt på, får me i første omgang mange samanstillingar mellom
kjelde- og mål-f-strukturar.

Difor rangerer me f-struktursamanstillingane, og den beste sender me
vidare til c-struktursamanstillinga. Denne delen av programmet gir ut
éi, utvitydig mengd med mange-til-mange-lenkjer mellom c-strukturane
(her treng me ingen rangering). Nodane i kvar av desse
mange-til-mange-lenkjene definerer no den endelege
frasesamanstillinga.

Nedanfor går eg gjennom detaljane rundt dei relevante delene av
programmet.

** Lenkjer mellom f-strukturar
\label{SEC:impl-f-lenkjing}

Hovudalgoritmen for lenkjing mellom f-strukturar er vist i kodefigur
\ref{algo:f-align}. Funksjonen =f-align= returnerer ei mengd med
moglege samanstillingar. Kvar samanstilling er ei mengd med par av
f-strukturar[fn:18]. Eit par $(F_s,F_t)$ representerer ei lenkje frå
ein f-struktur på kjeldespråket, til ein f-struktur på målspråket. Me
føreset at dette paret har LPT-korrespondanse[fn:17], dette blir
sjekka før alle kall på =f-align=. Der me ikkje har informasjon om
LPT-korrespondanse mellom to ord (orda er ukjende), er lenkjing
lov. Pro-element og substantiv kan alltid lenkjast med kvarandre.

Hjelpefunksjonen =argalign= (som igjen kallar =argalign-p=, vist i
kodefigur \ref{algo:argalign-p}) gir alle moglege
«argumentpermutasjonar», dvs. moglege kombinasjonar av lenkjer mellom
argumenta til $F_s$ og $F_t$ som tilfredsstiller kravet om
LPT-korrespondanse, men utan å sjekke at desse argumenta igjen kan
samanstillast. Funksjonen prøver å lenkje kvart argument til eit
argument eller eit adjunkt, men gir ingen lenkjer mellom to adjunkt
(sjå del \ref{SEC:impl-adjalign} nedanfor om dette). Funksjonen gir
heller ikkje kombinasjonar der minst eitt argument ikkje er lenkja --
alle kombinasjonane må inkludere alle argument frå $F_s$ og $F_t$,
jf. krav (iii) og (iv) i \citet[s.~75]{dyvik2009lmp}. Elles er krav
(i) er tautologisk oppfylt, medan me som nemnt føreset at krav (ii) er
oppfylt før alle kall på =f-align=.

Eit døme: viss $F_s$ har argumenta \SUBJs og \OBJs og ingen adjunkt,
og $F_t$ har argumentet \SUBJs og eitt adjunkt \ADJ, der alle
ord-omsetjingar er moglege, vil =argalign= gi dei to samanstillingane
$\{(\SUBJ,\SUBJ), (\OBJ,\ADJ)\}$ og $\{(\SUBJ,\ADJ),
(\OBJ,\SUBJ)\}$. Viss adjunktet til $F_t$ ikkje fantest, eller ikkje
hadde LPT-korrespondanse med nokon av argumenta til $F_s$, ville me
ikkje fått nokon samanstillingar; medan viss paret $(\SUBJ,\SUBJ)$
ikkje hadde LPT-korrespondanse og alt anna var likt, ville me berre
fått den siste samanstillinga.

Funksjonen =f-align= går så gjennom kvar lenkje i kvar
argumentpermutasjon, og prøver å kalle =f-align= på alle
lenkjene. Sidan lenkjene som =argalign= gir har LPT-korrespondanse,
vil alle f-strukturane i dei rekursive kalla i =f-align= ha
LPT-korrespondanse. Eit rekursivt kall kan gi nye samanstillingar i
dei indre f-strukturane, viss dei relevante krava er oppfylte.

Det er mogleg at ei lenkje frå éi samanstilling kan finnast i andre
samanstillingar, me unngår dobbeltarbeid ved å lagre alle delvise
samanstillingar i tabellen $aligntable$. Dette føreset at
\texttt{f-align}$(s,t)$ er uavhengig av konteksten rundt; t.d. må
mengda av samanstillingar som kjem ved å lenkje subjektet til $F_s$
mot subjektet til $F_t$ vere uavhengig av om objektet til $F_s$ er
lenkja mot eit objekt eller eit adjunkt osb. av $F_t$. \fxnote{TODO:
nemne føresetnaden om uavhengnad i kapittel 3}

#+BEGIN_LaTeX
      \SetKwComment{Comment}{ // }{}
     \SetKwInOut{Input}{usage}
  
     \begin{algorithm}[]
      \caption{f-align($F_s$, $F_t$)}
      \label{algo:f-align}
      
      $alignments \gets \emptyset$  \;
      \ForAll{argperm in argalign($F_s$, $F_t$)} {
        $p \gets \emptyset$ \;
         \ForAll{$A_s$, $A_t$ in argperm} {
           \uIf{not(aligntable[$A_s$,$A_t$])} {
           aligntable[$A_s$,$A_t$] $\gets$ f-align($A_s$, $A_t$)\;
           }
          \uIf{aligntable[$A_s$,$A_t$]}{add aligntable[$A_s$,$A_t$] to $p$\;}
          \uElse{add $(A_s, A_t)$ to $p$}
        }
        add $p$ to $alignments$ \;
        \ForAll{adjperm in adjalign(argperm, $F_s$, $F_t$)} {
          $a \gets$ copy-of($p$) \Comment*[r]{optional adjunct links}
          \ForAll{$A_s$, $A_t$ in adjperm}{
            \uIf{not(aligntable[$A_s$,$A_t$])} {
              aligntable[$A_s$,$A_t$] $\gets$ f-align($A_s$, $A_t$)\;
            }
            \uIf{aligntable[$A_s$,$A_t$]}{add aligntable[$A_s$,$A_t$] to $a$\;}
            \uElse{add $(A_s, A_t)$ to $a$}
          }
          add $a$ to $alignments$ \;
        } % adjperm in adjalign
       } % argperm in argalign
       \Comment{loop through adjalign if no arguments exist}
       \lIf {$alignments=\emptyset$}{ \Return $\emptyset$ \Comment*[l]{Fail} }
       \lElse{ \Return $((F_s, F_t), alignments)$ \; }
       \end{algorithm}    
    
    
      \begin{algorithm}[]
      \caption{argalign-p($args_s$, $adjs_s$, $args_t$, $adjs_t$)}
      \label{algo:argalign-p}
    
      \Input{Kalt av argalign slik: \\ argalign-p(arguments($F_s$),
      adjuncts($F_s$), arguments($F_t$), adjuncts($F_t$))}
      \BlankLine
      
     $a \gets \emptyset$\;
     \uIf{$args_s$} {
           $s \in args_s$\;
           \ForAll{$t \in args_t$ \textbf{where} LPT($s$,$t$)} {
               \lForAll{$p \in$ argalign-p($args_s-\{s\}$, $adjs_s$, $args_t-\{t\}$,$adjs_t$)}{
  add $\{(s,t)\} \bigcup p$ to $a$\;
             }
            }
           \ForAll{$t \in adjs_t$ \textbf{where} LPT($s$,$t$)} {
               \lForAll{$p \in$ argalign-p($args_s-\{s\}$, $adjs_s$, $args_t$,$adjs_t-\{t\}$)}{
  add $\{(s,t)\} \bigcup p$ to $a$\;
                }
           }
             \Return $a$\;
         }
          \uElseIf{$args_t$} {
            \uIf{$adjs_s$}{
                $s \in adjs_s$\;
           \ForAll{$t \in args_t$ \textbf{where} LPT($s$,$t$)} {
               \lForAll{$p \in$ argalign-p($args_s$, $adjs_s-\{s\}$, $args_t-\{t\}$,$adjs_t$)}{
  add $\{(s,t)\} \bigcup p$ to $a$\;
             }
            }
             \Return $a$\;
        }\uElse{
              \Return $\emptyset$  \Comment*[l]{Fail}
            }
          }
        \uElse {
          \Return \{$\emptyset$\} \Comment*[l]{End}
        }     
      \end{algorithm}
#+END_LaTeX

Sjølv om det er krav om LPT-korrespondanse mellom kvart argument og
eit argument/adjunkt for å lenkje $F_s$ og $F_t$, er det ikkje noko
krav om at alle para i ein argumentpermutasjon tilfredsstiller alle
lenkjingskrava. Viss \texttt{f-align}$(\OBJ,\ADJ)$ frå dømet over gir
null, og ikkje kan lenkjast (t.d. fordi \ADJs hadde eitt argument, og
\OBJs ingen argument/adjunkt), medan \texttt{f-align}$(\SUBJ,\SUBJ)$
kan lenkjast, vil =f-align= likevel returnere samanstillinga som
inneheld $(\OBJ,\ADJ)$ og $(\SUBJ,\SUBJ)$. Me kan sjå i $aligntable$
for å finne ut av om kvar av f-strukturane kunne lenkjast; i dette
tilfellet vil $aligntable[\OBJ,\ADJ]$ vere tom.

\fxnote{TODO: forskjellen mellom LPT-krav og rekursjonskrav på argument må
inn i kapittel 3}

Om me i tillegg krev at substrukturar kan samanstillast kan me
utelukke lenkjing av f-strukturane $F_s$ og $F_t$ i \Next under:

#+BEGIN_LaTeX
{\avmoptions{}

\ex. \a.  \begin{avm}  \sort{$F_s$}{\[ {\sc pred} `{\bf planlegge}<{\it eg},[1:{\it gi}]>'\\
  {\sc xcomp} \sort{$^{1}$}{\[ {\sc pred} `{\it gi (opp)}'\]} \]}  \end{avm}
  \b.\begin{avm} \sort{$F_t$}{\[ {\sc pred} `{\bf plan}<{\it I},[2:{\it give}]>'\\
  {\sc xcomp} \sort{$^{2}$}{\[ {\sc pred} {\bf give}<{\it I},{\it him},{\it it}>' \]} \]} \end{avm}

}
#+END_LaTeX

Men det kan vere at me ikkje /vil/ krevje dette i alle moglege
tilfelle. Ei tryggare løysing er å rangere ulike løysingar i
etterkant, ved å spørje etter dei argumentsamanstillingane som har
flest medlem i $aligntable$, dette kjem eg tilbake til i
\ref{SEC:f-rangering} nedanfor.
*** Overflødige adverbial
   \label{SEC:impl-adjalign}

Argumentpermutasjonane frå =argalign= prøver som nemnt ikkje reine
adjunkt-adjunkt-lenkjer, sidan me ikkje vil forkaste lenkjing av $F_s$
og $F_t$ berre på grunn av at ikkje alle adjunkt kunne lenkjast. Men
når me har prøvd ein argumentpermutasjon, kan me lage ein kopi av
denne som i tillegg inneheld lenkjer mellom «overflødige» adverbial,
altså dei adjunkt-adjunkt-lenkjene som =argalign= ikkje
prøver. Hjelpefunksjonen =adjalign= (ikkje vist her
\fxnote[inline,nomargin]{TODO: implementere :->}) konstruerer moglege
permutasjonar av lenkjer mellom adjunkt som ikkje er inkludert i
$argperm$, og =f-align= prøver desse rekursivt på same måte som med
argumentlenkjene. \fxnote{og så er det spørsmålet om me kan lenkje
adjunkt på ulike nivå i f-strukturane} Lenkjene blir lagt til ein
/kopi/ av argumentpermutasjonane, sidan det ikkje er sikkert at me
ønskjer å lenkje alle adjunktdøtre. Viss me har to overflødige adjunkt
på kvar side, og kravet om LPT-korrespondanse er dekkja for alle fire
moglege par, får me seks moglege permutasjonar, sidan me inkluderer
dei fire permutasjonane der eitt adjunktpar er ulenkja.

Viss $F_s$ og $F_t$ ikkje hadde argument i det heile teke, går me au
gjennom moglege permutasjonar av adjunktdøtre, på same måte (ikkje
vist i kodefigur \ref{algo:f-align}).

*** SKRIV Når f-lenkjene ikkje er 1-1
\fxnote{Dette må 1. spesifiserast (kap.3), og 2. implementerast...}
**** kausativ
**** preposisjonsobjekt
"sigaretten" og "sigaretze" er ikkje på same nivå i dei respektive
f-strukturane nedanfor:
: 0[ PRED vedde<28,29,27,30>
:    29[ PRED sigarett<> ] ]

: 0[ PRED da-najleveba<37,10,46>
:    ADJUNCT { 2 }
:    2[ ze<5>
:       OBJ 5[ sigareti ] ] ]

Men dette er fordi sigaretze er _adjunkt_, og i følgje fotnote 3 i
\citet{dyvik2009lmp} er P(ADJ) lik den semantiske formen til
_preposisjonsobjektet_ til ADJ. (Er dette heilt enkelt? Kan me ha
adjunkt med fleire «preposisjonsargument»?)

I motsetning til å endre på P(ADJ) slik at pred-verdien til eit
adjunkt hoppar over preposisjonar og inn i preposisjonsobjekt, har eg
i implementasjonen min gjort det slik at funksjonen som henter ut /f-strukturen/ til adjunkt-døtre av ein f-struktur hoppar over
preposisjonsobjekt (m.a. fordi ved eit kall P(X) kan ikkje P vite om X
er eit adjunkt eller argument).

Sjå au del \ref{SEC:merge-daughters}.

**** notat 							     :ROTETE:
filene 
: ((tab_s (open-and-import "dev/TEST_argadj_s.pl"))
:  (tab_t (open-and-import "dev/TEST_argadj_t.pl")))
viser at me kan trenge samanføying av pred på ulike nivå.
*** Kan me gjere f-struktursamanstillinga bottom-up?
#+BEGIN_LaTeX
  %     \begin{quotation}
  %    Any sufficiently complex problem needs to be coded three times.\\
  % \begin{minipage}{0.8\textwidth}
  % \begin{flushright}
  %        (ukjend, via Steve Gibson)
  % \end{flushright}
  % \end{minipage}
  %    \end{quotation}
#+END_LaTeX
Ein alternativ metode for lenkjing av f-strukturane er å byrje med
alle logisk moglege permutasjonar av LPT-korrespondansar, og så sile
ut dei som ikkje svarer til krava. Prosessen ville nok blitt mykje
meir oversiktleg på denne måten, sidan det då berre er snakk om å
sjekke krav for kvar enkelt lenkje.  Men ein slik metode er vanskeleg
i praksis; når avskjeringa skjer så seint, blir det alt for mange
moglege kombinasjonar for lengre setningar med mange ukjende ord til
at ein vanleg datamaskin kan halde styr på dei.

Me må i alle tilfelle vere klar for ei setning der alle ord er ukjende
(me har ingen informasjon om LPT-korrespondanse), slik at kvart
kjeldeord kan lenkjast til kvart målord. Viss begge setningane er 4 ord,
får me 16 moglege samanstillingar der alle ord er med i nøyaktig éi
lenkje ($2^l$, kor $l$ er setningslengd). Men ofte har me
null-lenkjer, me må altså i tillegg tillate samanstillingar der minst
eitt ord er ulenkja, utan at me treng å vite kva for ord det er; med
desse kortare listene inkludert får me endå fleire moglege
samanstillingar per setning (4 ord gir 26, 8 ord gir 2186 moglege
samanstillingar). Sjølv om me heile tida vel dei samanstillingane som
lenkjar flest ord, ville maskinen raskt fått problem. I tillegg har me
problemet med 1-mange-lenkjer, som skaper endå fleire moglege
samanstillingar.

Ein sideverknad av å byrje med ytre lenkjer og gå innover (prosessen
skildra i del \ref{SEC:impl-f-lenkjing}) er at me automatisk unngår å
prøve «kryssande» lenkjer, t.d. å lenkje $F_s$ med \XCOMPs av $F_t$, og
\XCOMPs av $F_s$ med $F_t$ (denne kombinasjonen av lenkjer vil jo vere
ein del av alle logisk moglege permutasjonar). Me får au prioritert å
lenkje ytre element, som jo er sikrare lenkjer: gitt to f-strukturar
for setningar der alt me veit om lenkjinga er at /setningane/ er
omsetjingar av kvarandre, vil dei to ytre f-strukturane ha størst
sjanse for å korrespondere med kvarandre. For kvart steg du går
innover må du multiplisere inn sjansen for å trå feil i
argumentpermutasjonane.

** SKRIV Rangering
\label{SEC:f-rangering}

\fxnote[inline,nomargin]{Rangering er ikkje implementert enno (akkurat no gir
rank(f-alignments) berre ut første samanstilling.)}
Rangering foregår etter ulike kriterium. Her er eit par forslag:
*** rekursivt lenkja > ulenkja, men LPT
    $aligntable$ seier om noko er rekursivt lenkja eller ikkje,
    plusspoeng viss me har klart å lenkje rekursivt.
*** argument-argument > argument-adjunkt
    Plusspoeng for argument-argument-lenkjer, burde vere eit bra
    kriterium, men me får sjølvsagt problem viss LPT ikkje seier noko
    i døme \ref{vedde} med \\
    =da-najleveba<Abrams,Browne,regne>= adjunkt: =sigarett=\\
    =bet<Abrams,sigarett,regne>= adjunkt: =Browne=
    
*** arg1-arg1 arg2-arg2 > arg1-arg2 arg2-arg1 (følgje)
    Dette kjem til å gi problem når me vil lenkje «behage» og «like»,
    viss me ikkje har motstridande LPT-informasjon (og argumentfølgje
    i leksikon ikkje er basert på semantikk, men syntaks). Men elles
    er det vel OK.

    Enklaste implementasjon: Levenshtein-avstand. Men burde visse
    argument vektast? (T.d. vekte subjekt om alt anna er likt.)

    Andre forslag: http://en.wikipedia.org/wiki/Edit_distance)
*** flest lenkja adjunkt
    Usikker på dette... avheng av om me tillèt lenkjer på tvers av
    f-strukturar.
*** Prioritet på rangeringskriterium
    Dette bør sjølvsagt testast empirisk, blir kanskje utanfor denne
    oppgåva (diskusjonsdel?), men kan jo prøve meg litt rundt.
** Lenkjing av c-strukturnodar
Samanstilling mellom f-strukturar treng i =lfgalign= ikkje informasjon
om c-strukturen, medan lenkjing av c-strukturnodar skjer på grunnlag
av f-struktursamanstillinga. Programmet utfører difor samanstilling av
c-strukturar sist.

Funksjonen =c-align= har som inndata c-strukturanalysane av kjelde- og
målsetninga, og éi f-struktursamanstilling; utdata er ei mengd med
lenkjer. Ei lenkje er eit par der første element er ei mengd
c-strukturnodar på kjeldespråket, og andre element ei mengd nodar på
målspråket. Det er ingen overlapp mellom medlem av lenkjer (ein node
er aldri med i meir enn eitt par).

I \citet[s.~77]{dyvik2009lmp} er kravet for å lenkje to
c-strukturnodar er at dei dominerer same mengd med
ordlenkjer[fn:20]. Ein node /n/ dominerer ei mengd lenkjer /l/ viss
unionen av lenkjene dominert av døtrene til /n/ er lik /l/. I
=lfgalign= opererer eg ikkje med /ordlenkjer/ i seg sjølv;
f-struktursamanstillinga er basert på LPT-korrespondansar, som
definerer moglege ordlenkjer utan å sjå på kontekst, og
f-struktursamanstillinga avgrenser vidare moglege ordlenkjer gitt
f-strukturinformasjon. Preterminale nodar er dei mest ordnære nodane
som kan ha ei f-strukturlenkje (ved $\phi$); når formålet er å lenkje
c-strukturnodar kan me nytte f-strukturlenkja til den preterminale
noden i staden for ordlenkjer.  \fxnote{To problem (kva vil me ha
med?)\\
1. me får \emph{ikkje} med LPT-korrespondansar som er OK, men
ikkje med i $f-alignment$;\\
2. me \emph{får} med LPT-korrespondansar
som er med i $f-alignment$ men ikkje $aligntable$ (ikkje er rekursivt
lenkja).}

#+BEGIN_LaTeX
 \begin{algorithm}[]
   \caption{c-align(f-alignment, $tree_s$, $tree_t$)}
   \label{algo:c-align}
    
   c-alignments $\gets \emptyset$ \;
   $splits_s \gets$ new table \;
   add-links(f-alignment, $tree_s, splits_s)$  \;
   $splits_t \gets$ new table \;
   add-links(f-alignment, $tree_t, splits_t)$  \;
   \ForAll{$links$ being the keys in $splits_s$} {
       \uIf{($links$ in $splits_t$)} {
             add $(splits_s[links],splits_t[links])$ to c-alignments \;
        }
    }
    \Return c-alignments \;
    \end{algorithm}    
#+END_LaTeX      

Hjelpeprosedyren =add-links= utfører hovudjobben. Inndata er rotnoden
til c-strukturtreet for eitt av språka, og
f-samanstillinga. Prosedyren kappar opp treet i nodemengder, kor kvar
nodemengd dominerer same lenkjemengd (som definert over).
Nodemengdene blir lagra i ein tabell, indeksert på
lenkjemengdene. Prosedyren går rekursivt gjennom treet frå rot til
lauv; lenkjemengden for kvar node er unionen av lenkjemengdene
returnert av =add-links= kalt på kvar av døtrene. Viss ein node
dominerer ei lenkjemengd $links$, legg me til denne noden i tabellen
$splits[links]$. 

#+BEGIN_LaTeX
   \begin{algorithm}[]
   \caption{add-links(f-alignment, $node, splits$)}
   \label{algo:add-links}
      
        $links \gets \emptyset$\;
   \uIf{$node$} {
       \uIf{preterminal?($node$)} {
          let $link \in$ f-alignment s.t. $\phi(node) \in link$ \;
          \lIf{$link$} {$links \gets \{link\}$}
        }
        \uElse {
          $links \gets $add-links(f-alignment, left-branch($node$)) $\bigcup$ add-links(f-alignment, right-branch($node$)) \;
        }
        add $node$ to $splits[links]$ \;
       }
        \Return $links$ \;
  \end{algorithm}
#+END_LaTeX

Sidan =c-align= kallar =add-links= for kvar av sidene, får me to
tabellar $splits_s$ og $splits_t$. Me hentar så ut alle dei
lenkjemengdene som er i begge tabellane (dvs. snittet av oppslagsnøklene
til tabellen); nodane som er lagra med mengd med f-strukturlenkjer
skal lenkjast på c-strukturnivå. Alle desse mange-til-mange-lenkjene
blir til slutt returnert av =c-align=.

Prosessen er no ferdig, mange-til-mange-lenkjene mellom
c-strukturnodar definerer frasesamanstillinga

\fxnote[inline,nomargin]{til
diskusjonsdel:\emph{Det er ikkje berre ei N-gramsamanstilling; sidan
lenkjene er mellom c-strukturnodar kor kvar node dominerer ein
konstituent, kunne me kalt det ei} konstituentsamanstilling.}.


*** SKRIV viss me har LPT, men ikkje rekursiv f-lenkje
    Dette bør kanskje vere valfritt i programmet, for å sjå kva det
    fører til: vil du ta med LPT-korrespondansar som ikkje har
    f-lenkjer i =add-links=?

    Og omvendt, finst det LPT-korrespondansar som ikkje kjem med i
    f-alignment i det heile teke, men som likevel burde ha noko å seie
    for c-strukturlenkjinga? (Men burde dei ikkje då vere med i
    f-alignment au?)

\fxnote{Kan me \textbf{fjerne} visse f-samanstillingar pga. c-strukturinfo?
    dvs. disambiguere...
    (dette er vel heller stoff for diskusjonsdelen?)}


* Diskusjon, resultat av å automatisk samanstille norske og georgiske setningar
\label{SEC:diskusjon}

   - om kjeldematerialet
   - manglar med implementasjonen
   - samanlikning av lenkjing basert på f-struktur og lenkjing basert
     på N-gram
   - bruksområde for samanstillingar

** Oppdage argumentstrukturalternasjon
\fixme{ref} I døme TODO i kapittel TODO viste eg at f-strukturar og
LPT-korrespondanse kanskje ikkje har nok informasjon til å kunne
handtere ulik følgje i argumentstruktur. Programmet mitt vil her gi
begge løysingar, ei rangering basert på lik argumentfølgje vil gi feil
løysing på topp.

Kanskje kan me nytte data frå fleire førekomstar med andre subjekt og
objekt til å lære slike argumentstrukturalternasjonar.  Om me
observerer /sie gefällt mir/jeg liker henne/ vil me jo ha
f-strukturinformasjon som kan nyttast til å informere
argumentstrukturalternasjon (/sie/henne/ er hokjønn, etc.), om det var
substantiv der ville LPT-korrespondanse kunne informere dette.
** Samanlikning med tremetodar og n-grammetodar
I tillegg til at ein kanskje kan få betre skåre på kvantitative mål
som presisjon og gjenkjenning, vil lenkjer mellom f-strukturar gi
informasjon som er kvalitativt forskjellig frå det ein kan få med å
berre sjå på lenkjer mellom ord, n-gram eller konstituentar.

*** c->f er mange-til-ein
Avbildinga frå c-strukturnodar til f-struktur er mange-til-ein, kan me
t.d. innanfor eitt tre ha fleire N-gram per f-strukturhovud; ein
metode som berre ser på enkle N-gramlenkjer vil ikkje registrere desse
relasjonane (t.d. metoden i \citet{samuelsson2007apa}).
 


*** TOGROK men korleis gjenfinne there is/es gibt? 		     :ROTETE:
1. N-gram kjem like ofte som heile konstruksjonen, då kan dette
   gjenfinnast
   - dvs., /there is NP/es gibt NP/-samanstilling kjem like ofte som
     /there is/ eller /es gibt/ førekjem. Eit TigerXML-type søk etter
     /there is NP/es gibt NP/ burde jo vere mogleg, sjekk om dette er
     delmengd av /there is/es gibt/. * Avslutning




* Avslutning
# tom inndeling for å halde bibliografien sist

\bibliographystyle{apacite}
\bibliography{master}

* Footnotes

[fn:1] Både omsetjingsmodellen og
språkmodellane er reint N-grambaserte her, og har difor ikkje nytte av
syntaktisk informasjon (i motsetning til syntaktisk informert
generering slik \citet{riezler2006gmt} implementerer).

[fn:typetoken] \cite[s.~2]{thunes2003eal}: «Våre prinsipper er satt
opp for å tjene et bestemt formål, nemlig å samle inn data som metoden
i Semantic Mirrors skal anvendes på», ein metode for å automatisk
finne WordNet-liknande relasjonar frå parallelltekst. I denne metoden
vil det vere naturleg med høge krav til presisjon, men kanskje lågare
krav til dekning: speilmetoden skal finne leksikale semantiske forhold
som held på /typenivå/, medan for trebanken er det viktigare korleis
me kan annotere eit /token/ av t.d. eit verb i ein viss VP i ei gitt
korpussetning.

[fn:3] \citet[Catford~(1965),~i][s.~61]{munday2001its} gir ein gjennomgang av
slike /klasseskifte/, og andre typar omsetjingsskifte.

[fn:4] Setningane i første og tredje linje i døma er direkte henta frå
MRS-suiten, med mindre anna er opplyst.

[fn:6] Sidan eg føreset setningssamanstilte data, kjem eg ikkje inn på
 diskurs-/pragmatiske verknader, med mindre det kan vere mogleg
 å handsame desse innanfor setningen.
# SKRIV omformulere! og ekspliser...

[fn:7] Det funksjonelle domenet til ein f-struktur er gitt ved
 $\phi^{-1}$, inversen av c-til-f-strukturavbildinga, og tilsvarer dei
 nodane i c-strukturen som projiserer denne f-strukturen, t.d. ein
 VP-node med dominerande IP og CP
 \citep[s.~126]{bresnan2001lfs}. Sidan dette er inversen av ein
 funksjon, kan me ha diskontinuerlege konstituentar i same
 funksjonelle domene (fleire funksjonsargument som gir same verdi).

[fn:9] I tillegg finst andre positive biverknader av ein LFG-basert
 frasesamanstilling for bruk i denne samanhengen, som at ein kan
 oppdage kor parallelle dei parallelle grammatikkane i
 ParGram-prosjektet \citep{butt2002pgp} faktisk er, på ulike nivå
 (leksikon og argumentstruktur, c-struktur, f-struktur).

[fn:10] Skal ein lenkje ordet /som/ (utan PRED) med ordet /which/ (med
 PRED)? Viss begge står under C i treet, kan det kanskje vere
 informativt med ein type «defekt» lenkje, sjølv om berre det eine
 ordet blir rekna for å vere eit innhaldsord. Frasane til deira
 funksjonelle domene vil uansett vere samanstilt via toppnodane
 (t.d. CP).

[fn:11] Eg nyttar her termane /lenkjing/ og /samanstilling/ om
 kvarandre, i same tyding som det engelske /alignment/; dette er
 ekvivalensforhold som me kan finne mellom lingvistiske
 /representasjonar/ (f-struktur, c-struktur) eller /uttrykk/ (ord,
 setningar). Lenkjing mellom dei siste altså er meir ateoretisk / datanært.

[fn:12] I del \ref{SEC:fnord} kjem eg tilbake til spørsmålet om me vil
        inkludere visse f-strukturar utan PRED-element i kandidatane
        for samanstilling.

[fn:13] Det georgiske verbalsubstantivet (/masdar/) er i følgje
        \citet[kap.~2.5]{aronson1990grg} ein /nominal/ form, det kan i
        motsetning til norske verbalsubstantiv og engelske gerundium
        ikkje ta objekt, men kan ha modifiserande substantiv i
        genitiv.

[fn:14] Analysane er henta 18. mai, 2009, frå
        http://decentius.aksis.uib.no/logon/xle.xml, som implementerer
        LFG-grammatikkane frå ParGram-prosjektet \citep{butt2002pgp}.

[fn:15] 25 om ein inkluderer analysar kor minst eitt av argumenta
        ikkje hadde korrekt analyse (t.d. eit \textsc{PRO} der
        grammatikken burde funne eit substantiv).

[fn:2] Tilgjengeleg frå http://github.com/unhammer/lfgalign som fri og
       open programvare under GNU General Public License.

[fn:5] Formatet er dokumentert på
       http://www2.parc.com/isl/groups/nltt/xle/doc/xle.html. Importeringa
       til Lisp-strukturar handterer «pakka representasjonar» og
       kjenner igjen ekvivalensforhold (t.d. der fleire
       $\phi$-variablar refererer til same f-struktur, eller fleire
       Prolog-variabler refererer til same analyseval); men filene eg
       har testa utnyttar ikkje det fulle spennet til formatet, så det
       finst ganske sikkert feil.

[fn:16] Dette språkvalet kan gjere eventuell integrering med andre
        LFG-system lettare (Common Lisp er m.a. nytta i LFG
        Parsebanker \citep{rosen2009lpt}).

[fn:17] Når eg her skriv at to f-strukturar har LPT-korrespondanse,
        meiner eg sjølvsagt at ordformen til PRED-verdien til kvar
        f-struktur har LPT-korrespondanse.

[fn:18] Eigentleg eit slags avgjerdstre; kvart element er eit par, kor
        første element er lenkja mellom dei yttarste f-strukturane, og
        andre element er dei moglege samanstillingane for dei indre
        strukturane. Denne strukturen kan vere nyttig for å rangere
        samanstillingar, og =f-align= blir mykje meir oversiktleg av å
        jobbe med eit slikt tre. Ein funksjon =flatten= omformar det
        ferdige treet til ei enkel liste med samanstillingar, kor kvar
        samanstilling er ei flat liste med lenkjer mellom
        f-strukturar.

[fn:19] Ved c-struktur-f-strukturavbildinga $\phi$, ein funksjon som
        tek ein c-strukturnode og returnerer ein (delvis) f-struktur.

[fn:20] Dette er ein litt enklare måte å definere kravet på; ei
        /lenkje/ refererer til både kjelde og mål, dimed blir det
        mogleg å seie at ein node på kjeldespråket kan dominere same
        mengd som ein node på målspråket.

